### ISSUE TITLE
Impacket import error & pyasn1.type.univ import noValue

### ISSUE THREAD

**Issue by raManSecurity** [SecureAuthCorp/impacket#1006]
Hey guys, just spent a good 4 hours trying to solve an Impacket issue. Thought I'd share the fix:

### Configuration  
Target OS:  Distro (2020.4): 5.9.0-kali2-amd64 #1 SMP Debian 5.9.6-1kali1 (2020-11-11) x86_64 GNU/Linux

### Debug Output With Command String  
Traceback (most recent call last):
  File "send_and_execute.py", line 2, in <module>
    from impacket import smb, smbconnection
ImportError: No module named impacket

Another error I also encountered later on:
from impacket import smb, smbconnection
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 49, in <module>
    from pyasn1.type.univ import noValue
```

### Additional context  
**FIX**
sudo rm -rf /opt/impacket
sudo rm -rf /usr/local/lib/python2.7/dist-packages/impacket*
sudo git clone https://github.com/SecureAuthCorp/impacket.git /opt/impacket
sudo pip3 install -r /opt/impacket/requirements.txt
python3 setup.py install

**Comment by 4NDRETTi** [comment]
did you fix the 2nd problem you ran into? I am currently stuck on the same thing

**Comment by hikenroot** [comment]
it still doesn't work

./wmiexec.py 
Traceback (most recent call last):
  File "./wmiexec.py", line 31, in <module>
    from impacket.examples import logger
ImportError: No module named impacket.examples

**Comment by ZacharyETaylor** [comment]
Working on this fix as well, these 3 are rabbit holes:
apt-get --reinstall install python-pyasn1 python-pyasn1-modules

sudo pip install pyasn1
Requirement already satisfied: pyasn1_modules in /usr/lib/python3/dist-packages (0.2.1)
sudo pip install pyasn1_modules
Requirement already satisfied: pyasn1_modules in /usr/lib/python3/dist-packages (0.2.1)


I then attempted to download the egg file from: https://pypi.org/project/pyasn1/#modal-close
pyasn1-0.4.8-py2.7.egg (174.9 kB) 
unzip and copy the extracted pyasn1 folder to /usr/lib/python2.7/dist-packages/

after running 
python ./smbserver.py share /folder
I have a new problem: (sigh)

Traceback (most recent call last):
  File "./smbserver.py", line 47, in <module>
    from impacket import smb, nmb, ntlm, uuid
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 54, in <module>
    from impacket.krb5.gssapi import KRB5_AP_REQ
  File "/usr/local/lib/python2.7/dist-packages/impacket/krb5/gssapi.py", line 20, in <module>
    from Cryptodome.Hash import HMAC, MD5
ImportError: No module named Cryptodome.Hash

working on this now...

**Comment by 0xdeaddood** [comment]
Hi guys, 
These look like installation issues. Please check the README file and follow the instructions in the Installation section.

**Comment by l3ra** [comment]
> Working on this fix as well, these 3 are rabbit holes: apt-get --reinstall install python-pyasn1 python-pyasn1-modules
> 
> sudo pip install pyasn1 Requirement already satisfied: pyasn1_modules in /usr/lib/python3/dist-packages (0.2.1) sudo pip install pyasn1_modules Requirement already satisfied: pyasn1_modules in /usr/lib/python3/dist-packages (0.2.1)
> 
> I then attempted to download the egg file from: https://pypi.org/project/pyasn1/#modal-close pyasn1-0.4.8-py2.7.egg (174.9 kB) unzip and copy the extracted pyasn1 folder to /usr/lib/python2.7/dist-packages/
> 
> after running python ./smbserver.py share /folder I have a new problem: (sigh)
> 
> Traceback (most recent call last): File "./smbserver.py", line 47, in from impacket import smb, nmb, ntlm, uuid File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 54, in from impacket.krb5.gssapi import KRB5_AP_REQ File "/usr/local/lib/python2.7/dist-packages/impacket/krb5/gssapi.py", line 20, in from Cryptodome.Hash import HMAC, MD5 ImportError: No module named Cryptodome.Hash
> 
> working on this now...

@ZacharyETaylor how did you solve the ImportError: No module named Cryptodome.Hash? Going through this now
