### ISSUE TITLE
Sometimes the execution of wmiexec.py will get stuck without returning any information

### ISSUE THREAD

**Issue by zhouhaocheng** [SecureAuthCorp/impacket#1008]
When I execute wmiexec.py, no information is returned, and it feels like it is stuck. This phenomenon only appears on some Windows servers. Is it related to the antivirus programs installed on some servers?

**Comment by mohemiv** [comment]
Hi @zhouhaocheng,

Kaspersky Anti-Virus blocks wmiexec.py, and it can be bypassed by modifying the execute_remote method.

**Comment by zhouhaocheng** [comment]
Hi @mohemiv,
Thank you for your reply. Is there a corresponding solution, or is it possible to set a whitelist policy on the antivirus program?

**Comment by zhouhaocheng** [comment]
Hi @mohemiv,
How to modify the execute_remote method？

**Comment by zhouhaocheng** [comment]
As shown in the screenshot below, it will be stuck at this stage and cannot return to the cmd interactive shell.
![image](https://user-images.githubusercontent.com/31977621/101113132-b1342900-3619-11eb-8a71-3276fc36e891.png)

**Comment by mohemiv** [comment]
For example, you can try to make the following modification:
```
- OUTPUT_FILENAME = '__' + str(time.time())
+ OUTPUT_FILENAME = str(time.time())

-            command += ' 1> ' + '\\\\127.0.0.1\\%s' % self.__share + self.__output  + ' 2>&1'
+            command += ' > C:\\Windows\\%s 2>&1' % self.__output
```
