### ISSUE TITLE
Impacket for Python2

### ISSUE THREAD

**Issue by Neusier** [SecureAuthCorp/impacket#1012]
Hi there, hola, 

Need the impacket package for a script running on python2. I managed to get a old version for 2.7 to 2.8 but gives me dependency errors. 

Having impacket installed for python3, is there any way I could use it for python?

Thanks

**Comment by asolino** [comment]
You can install `impacket` for Python 2.7 by running `pip install . ` at the impacket directory. Please check our [README](https://github.com/SecureAuthCorp/impacket/blob/master/README.md) file, in particular `Quick Install` and `Installing`
