### ISSUE TITLE
smbserver.py : SyntaxError

### ISSUE THREAD

**Issue by 3isenHeiM** [SecureAuthCorp/impacket#1038]
### Configuration  
impacket version:  latest 
Python version:  3.9.2
Target OS:  Kali 2021.1

### Debug Output With Command String  
smbserver.py TEST /folder/ -debug

```
smbserver.py TEST /folder/ -debug
Traceback (most recent call last):
  File "/usr/local/bin/smbserver.py", line 19, in <module>
    from impacket import smbserver, version
  File "/usr/local/lib/python3.9/dist-packages/impacket/smbserver.py", line 84
    except Exception, e:
                    ^
SyntaxError: invalid syntax

```

Impacket has been installed in a venv.

**Comment by 0xdeaddood** [comment]
Hi @3isenHeiM. I can't reproduce it. Are you sure you are using the latest version of impacket? Seems like an old bug before porting to Python3.

**Comment by 0xdeaddood** [comment]
No answer, closing. Reopen if needed.
