### ISSUE TITLE
ntlmrelayx --delegate-access without creating host

### ISSUE THREAD

**Issue by p3nt4** [SecureAuthCorp/impacket#1041]
### Configuration  
impacket version:  v0.9.23.dev1
Python version:  3.9
Target OS:  Windows

### Additional context  
Apologies if this isnt the right place to raise this issue. 
I am trying to use the --delegate-access attack of ntlmrelayx, unfortunately the relayed host does not have enough privileges to create a computer. 

Given that I control other computers, would it be possible to use something like --delegate-access "hostname" to delegate access to the host that I already control without creating a new one?

**Comment by p3nt4** [comment]
Anyone looking for this, this is accomplished by --escalate-user already

**Comment by vysecurity** [comment]
Wasn't intuitive. Thanks for documenting it in issues.
