### ISSUE TITLE
LDAP library SimplePagedResultsControl usage results in record skipping

### ISSUE THREAD

**Issue by shellster** [SecureAuthCorp/impacket#1043]
### Configuration  
impacket version:  0.9.22 (PyPI)
Python version:  3.8
Target OS:  Ubuntu

### Issue

Providing I am doing things correctly, there appears to be a bug with the paging code in the LDAP library.
If I comment out the "searchControls" section of my code, all records are returned.  However, suppose I set a `SimplePagedResultsControl` size of "50". If there are 103 records, only 100 records will be returns, (the number that equally devices into the page control size). The last three records do not get returned.

Below is a cutdown sample of my code (I removed everything that I didn't think was relevant and made it a bit more generic, so it is possible I screwed something up in the process).

### Relevant Code

```
from impacket.ldap import ldap

server = "redacted"
basedn = "redacted"
username = "redacted"
password = "redacted"
domain = "redacted"

conn = ldap.LDAPConnection(server, basedn, None)
conn.login(username, password, domain)

sc = ldap.SimplePagedResultsControl(size=50)

conn.search(searchFilter=search, attributes=["cn", "mail"], sizeLimit=0, searchControls=[sc], perRecordCallback=my_callback)

def my_callback(entry):
    '''handle entry here'''
    pass
```

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
I have 103 users within my domain, when I try the following code, 103 results are returned (tested with `pip install impacket` in a fresh env)
```python
from impacket.ldap import ldap, ldapasn1

def my_callback(entry):
    '''handle entry here'''
    print(entry)
    pass

ldap_connection = ldap.LDAPConnection('ldap://172.16.0.1', 'dc=aaaaaaaa,dc=org', '172.16.0.1')
ldap_connection.login('username', 'password', 'domain', '', '')
paged_search_control = ldapasn1.SimplePagedResultsControl(size=50)
attributes=["cn", "mail"]
search_filter = '(samAccountType=805306368)'
search_results = ldap_connection.search(searchFilter=search_filter,searchControls=[paged_search_control],attributes=attributes, perRecordCallback=my_callback)
```

```shell
$ python3 test.py | grep SetOf | wc -l
103
```

Are you sure you have the latest release ? 0.9.22 includes #840 which fix this issue.

:sunflower:

**Comment by 0xdeaddood** [comment]
Thanks for the clarification @ThePirateWhoSmellsOfSunflowers! 

@shellster, please check you are using the latest release.

**Comment by shellster** [comment]
Hey guys.  Thanks for the quick responses.  I went back and retested.  I had pinned impacket 0.9.22 in my project, but for some reason I guess I must have been on an older version. I went back and tested again and it appears to be working correctly, so I'm going to close this issue out.
