### ISSUE TITLE
SMBServer issues handling NULL SMBv2 client connections

### ISSUE THREAD

**Issue by alexisbalbachan** [SecureAuthCorp/impacket#1048]
### Configuration  
impacket version:  0.9.22
Python version:  2.x, 3.x
Target OS:  Windows 10

### Description 
Related to #835, SMB clients running on Windows 10 fail to connect to the SMBServer when trying to authenticate with a NULL session.

### Steps to reproduce:

1. Start the SMB server: `python examples/smbserver.py -smb2support -debug share_name /path/to/share`
2. On Windows 10, connect to the server providing a NULL session: `net use * \\SERVER_IP\IPC$ "" /user:`

### Expected behavior
The client should be able to connect to the server

### Actual behavior
The client fails to connect:
![image](https://user-images.githubusercontent.com/8486486/113772824-9a9efb00-96fb-11eb-8bef-2acafbac0c77.png)

SMBServer's log:
![screen](https://user-images.githubusercontent.com/8486486/113773249-2add4000-96fc-11eb-9821-8855e96ad95b.jpg)

### Additional Information

- The problem only seems to be happening on Windows 10, smbclient on Ubuntu is able to connect with a NULL session:
![screen4](https://user-images.githubusercontent.com/8486486/113774403-9d9aeb00-96fd-11eb-8f2c-2c1b7a801e81.jpg)
![screen5](https://user-images.githubusercontent.com/8486486/113774557-d044e380-96fd-11eb-8327-bc33323063ce.jpg)

### PCAP

- Connection request using a NULL session:
![screen2](https://user-images.githubusercontent.com/8486486/113775564-439b2500-96ff-11eb-9504-61472bf7df9b.jpg)

- Impacket's response:
![screen](https://user-images.githubusercontent.com/8486486/113775877-b0aeba80-96ff-11eb-9e6c-ec9d69690dc7.png)

- Expected response (captured while connecting to a windows share with a NULL session):
![screen2](https://user-images.githubusercontent.com/8486486/113776260-1d29b980-9700-11eb-946f-cd6621fa9cbc.png)

- Contrary to the result listed above, the SMB2 specification indicates that when a user has been authenticated as an anonymous user (NULL session) then the NULL flag should be set:  https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/0324190f-a31b-4666-9fa9-5c624273a694

### Proposed Fix
- SMBServer defaults to guest access if no credentials were set: https://github.com/SecureAuthCorp/impacket/blob/a16198c3312d8cfe25b329907b16463ea3143519/impacket/smbserver.py#L2802-L2824
- Instead of defaulting to guest by setting isGuest to True, there should be an extra condition that should check whether the "Negotiate Anonymous" flag is set. If that is the case then it should set (a new) isAnonymous variable to True
- Session flags are set to 1 if isGuest is True: https://github.com/SecureAuthCorp/impacket/blob/a16198c3312d8cfe25b329907b16463ea3143519/impacket/smbserver.py#L2848-L2849
- Another condition should be added that checks if isAnonymous is True and then set sessionFlags to either 0 or 2 (Windows sets it to 0, the SMB2 specification indicates that it should be set to 2)

**Comment by noraj** [comment]
I have the exact same behavior

- Impacket v0.9.22
- Python 3.9
- Target OS: Windows Server 2016 (build 17763)

**Comment by 0xdeaddood** [comment]
Thanks @alexisbalbachan for reporting and proposing the solution! It should be fixed in https://github.com/SecureAuthCorp/impacket/commit/0efdf7c03737152f80c85f3b990df548c651baee.
