### ISSUE TITLE
OSError: [Errno 113] No route to host

### ISSUE THREAD

**Issue by abbashaide** [SecureAuthCorp/impacket#1050]
I have tried different releases of impacket cant seem to get around this error

python3 mssqlclient.py ARCHETYPE/sql_svc:M3g4c0rp123@10.10.10.17 -windows-auth

Impacket v0.9.23.dev1+20210315.121412.a16198c3 - Copyright 2020 SecureAuth Corporation

Traceback (most recent call last):
File "/opt/impacket/examples/mssqlclient.py", line 173, in
ms_sql.connect()
File "/home/jinjer/.local/lib/python3.9/site-packages/impacket/tds.py", line 532, in connect
sock.connect(sa)
OSError: [Errno 113] No route to host

**Comment by martingalloar** [comment]
Hey @abbashaide! Can you please try to run it with the `-debug` option and provide more information?

**Comment by martingalloar** [comment]
Closing, please reopen if you still have issues with this!

**Comment by mitsukiyouko555** [comment]
I'm still getting the error after using -debug

python mssqlclient.py ARCHETYPE/sql_svc@10.129.161.59 -windows-auth -debug
/usr/share/offsec-awae-wheels/pyOpenSSL-19.1.0-py2.py3-none-any.whl/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
Impacket v0.9.19 - Copyright 2019 SecureAuth Corporation

Password:
Traceback (most recent call last):
  File "mssqlclient.py", line 171, in <module>
    ms_sql.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/tds.py", line 531, in connect
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 113] No route to host

**Comment by rudrprasad05** [comment]
im getting the same error output. any help will be appreciated
