### ISSUE TITLE
 unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by zAbuQasem** [SecureAuthCorp/impacket#1052]
### Configuration  
impacket version:  0.9.23
Python version:  Python 3.9.2
Target OS:  parrot

### Debug Output With Command String  

impacket-secretsdump -system sys.bin -ntds data.dit LOCAL
Impacket v0.9.23.dev1+20210315.121412.a16198c3 - Copyright 2020 SecureAuth Corporation

[-] unpack requires a buffer of 4 bytes
[*] Cleaning up... 

```

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  

![image](https://user-images.githubusercontent.com/74984708/114304433-98092080-9ac2-11eb-85ab-36e613eeb851.png)

**Comment by 0xdeaddood** [comment]
Hi @zAbuQasem! Could you please try to run it with the -debug option and provide more information? What is the Windows target? Have you verified that the SYSTEM hive file is correct?

**Comment by 0xdeaddood** [comment]
No answer, closing. Reopen if needed.
