### ISSUE TITLE
Issue Installing Impacket 0.9.22 on Kali Linux 2021

### ISSUE THREAD

**Issue by revronja** [SecureAuthCorp/impacket#1065]
trying to do this

1. grab https://github.com/SecureAuthCorp/impacket/releases/tag/impacket_0_9_22
2. cd impacket
3. sudo pip3 install .
4. cd examples
5. python3 GetNPUSers.py

the error is always for python3

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("%s" % msg, end=" ")?
                     

and this for python2

ImportError: No module named pyasn1.codec.der

**Comment by nuschpl** [comment]
Without exact error messages,with line numbers and paths which is reason of your issues is hard to debug. 

Also try my method here instead of your point 3:
https://github.com/SecureAuthCorp/impacket/pull/1060/commits/4cf864f2e076df89267130864d8cc278392c3173

**Comment by spacepetunia** [comment]
Have the same problem, but in other file!

Traceback (most recent call last):
  File "./GetUserSPNs.py", line 39, in <module>
    from pyasn1.codec.der import decoder
ImportError: No module named pyasn1.codec.der

**Comment by 0xdeaddood** [comment]
Hi guys! 
Please check your setups (it seems that pip3 and python3 are not in the same path), and reinstall it. You can also try the @nuschpl's method.

Closing. Reopen if needed.

**Comment by revronja** [comment]
this fails still

┌──(kali㉿kali)-[~/impacket-0.9.22/examples]
└─$ which python3                                                                        1 ⨯
/usr/bin/python3


└─$ which pip3   
/usr/bin/pip3


┌──(kali㉿kali)-[~/impacket-0.9.22/examples]
└─$ sudo python3 -m pip install .

└─$ python3 GetNPUsers.py                                                                1 ⨯
Traceback (most recent call last):
  File "/home/kali/impacket-0.9.22/examples/GetNPUsers.py", line 39, in <module>
    from impacket.dcerpc.v5.samr import UF_ACCOUNTDISABLE, UF_DONT_REQUIRE_PREAUTH
  File "/home/kali/.local/lib/python3.9/site-packages/impacket/dcerpc/v5/samr.py", line 303
    print "%s" % msg,
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("%s" % msg, end=" ")?

**Comment by 0xdeaddood** [comment]
Hi @revronja! 
That error is from a version prior to porting to python 3 (it was addressed here: https://github.com/SecureAuthCorp/impacket/commit/0a4c7872b4626bb1ec4fbd750b7573a850f8195a). It looks like you are using a new version of the GetNPUsers.py script with an old version of Impacket. 

You need to install the latest version of the Impacket library. Try again following [this](https://github.com/SecureAuthCorp/impacket/blob/master/README.md#installing) and check the output to rule out problems in your setup. Related issue: #969

Alternatively, you can try to test impacket cloning and installing the library into a [Virtual Environment](https://docs.python.org/3/tutorial/venv.html). This helps to avoid any potential mix of different versions.

**Comment by RubensZimbres** [comment]
For me, works with Python 3:

$ pip3 install .

$ python3 GetUserSPNs.py .....

**Comment by SudoIndividual** [comment]
> For me, works with Python 3:
> 
> $ pip3 install .
> 
> $ python3 GetUserSPNs.py .....

this works thanks
