### ISSUE TITLE
No module named 'impacket.examples.utils'

### ISSUE THREAD

**Issue by hueychopper** [SecureAuthCorp/impacket#1078]
thats it. Thats the problem.

I looked around in the files and there was no utils folder containing "**parse_target**".

**Comment by martingalloar** [comment]
Hey! Can you check please if you're working out of tree or your python environment isn't pointing to a different installation path?

**Comment by hueychopper** [comment]
If by tree you mean that I am using the entirety of impacket then yes. But I am using Linux and I am a beginner so I don't know about the python environment it has.

**Comment by 0xdeaddood** [comment]
Hi @hueychopper!
That module was added a few weeks ago ([here](https://github.com/SecureAuthCorp/impacket/commit/a45f331360ce2abdb1c517a35a1c407725b0d761)). It looks like you are using a new version of the mssqlclient.py script with an old version of Impacket. You can check this in the version banner when you run the script. If that is the case, try installing the latest version of the Impacket library following [this](https://github.com/SecureAuthCorp/impacket#installing).

**Comment by hueychopper** [comment]
Thanks. I will try it out.

**Comment by knobrazz** [comment]
ModuleNotFoundError: No module named 'impacket.msada_guids'
