### ISSUE TITLE
psexec remote execution shows garbled characters

### ISSUE THREAD

**Issue by Litter117** [SecureAuthCorp/impacket#1079]
target OS:  Windows Server 2008 R2 zh-cn;中文(中国)

root@test:~/impacket# python2.7 psexec.py -ts -debug -hashes :518B98AD4178A53695DC997AA02D455C test/administrator@192.168.159.12 'query user'
Impacket v0.9.23.dev1 - Copyright 2020 SecureAuth Corporation

[2021-05-13 10:17:48] [+] Impacket Library Installation Path: /usr/local/lib/python2.7/site-packages/impacket
[2021-05-13 10:17:48] [+] StringBinding ncacn_np:192.168.159.12[\pipe\svcctl]
[2021-05-13 10:17:48] [*] Requesting shares on 192.168.159.12.....
[2021-05-13 10:17:48] [*] Found writable share Address
[2021-05-13 10:17:48] [*] Uploading file ZpwrymCb.exe
[2021-05-13 10:17:48] [*] Opening SVCManager on 192.168.159.12.....
[2021-05-13 10:17:48] [*] Creating service FJnw on 192.168.159.12.....
[2021-05-13 10:17:48] [*] Starting service FJnw.....
[!] Press help for extra shell commands

 ╙├╗º├√                ╗ß╗░├√             ID  ╫┤╠¼    ┐╒╧╨╩▒╝Σ   ╡╟┬╝╩▒╝Σ
 administrator         console             1  ╘╦╨╨╓╨      ╬▐     2021/5/11 14:25

[2021-05-13 10:17:48] [*] Process query user finished with ErrorCode: 0, ReturnCode: 1
[2021-05-13 10:17:48] [*] Opening SVCManager on 192.168.159.12.....
[2021-05-13 10:17:48] [*] Stopping service FJnw.....
[2021-05-13 10:17:49] [*] Removing service FJnw.....
[2021-05-13 10:17:49] [*] Removing file ZpwrymCb.exe.....

**Comment by p0dalirius** [comment]
I see in your logs `Windows Server 2008 R2 zh-cn` maybe the target system is in Simplified Chinese (zh-CN) ?
This would explain the garbage decoded output.

**Comment by p0dalirius** [comment]
Hi @Litter117,

I recreated your environment and tested this on Windows Server 2008 R2 with simplified Chinese (zh-CN) characters. There is indeed a problem with how [psexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/psexec.py) handles the encodings for `stdin` and `stderr` pipes. It works fine with [smbexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/smbexec.py).

I created a file containing simplified Chinese (zh-CN) characters, and I put it on the Windows Server 2008 R2:

![2021-10-03_10-38](https://user-images.githubusercontent.com/79218792/135751003-1e10666f-50df-4d94-b0ed-e62cd071b487.png)

## With psexec.py

When characters are printed to `stdin` and `stderr` pipes, [psexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/psexec.py) decodes them as `cp437` encoding. Therefore multi-bytes characters such as simplified Chinese (zh-CN) alphabet would decode incorrectly as shown here:

```
psexec.py -ts -debug 'WIN2008/Administrator:Admin123!@192.168.2.108'
```
![2021-10-03_10-37](https://user-images.githubusercontent.com/79218792/135750970-bf1c51f2-2008-446a-9134-aab29a5a9e2a.png)

## With smbexec.py

It works fine in the latest version of [smbexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/smbexec.py):

```
smbexec.py 'WIN2008/Administrator:Admin123!@192.168.2.108'
```

![2021-10-03_10-40](https://user-images.githubusercontent.com/79218792/135751017-3d72eb6d-3ce2-43b8-98ad-242b512511a0.png)

## Solution

I fixed the encoding problems in [psexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/psexec.py) in [pull request xxxx](https://github.com/SecureAuthCorp/impacket/pull/1174). I refracted the print loop in `stdin` and `stderr` pipes to handle encodings and added a `-codec` option like in [smbexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/smbexec.py) if you need to force an encoding:

```
psexec.py -ts -debug 'WIN2008/Administrator:Admin123!@192.168.2.108' -codec utf-8
```

It now works fine:

![2021-10-03_12-56](https://user-images.githubusercontent.com/79218792/135751018-ef607c9a-5c88-4e23-95fb-dabd5d26a22d.png)

Best regards,
**Podalirius**
