### ISSUE TITLE
Unable to install impacket with pip2 and impacket is not found in python 2.7.18

### ISSUE THREAD

**Issue by Fox0nTheRun** [SecureAuthCorp/impacket#1080]
### Configuration  
impacket version:  0.9.22
Python version:  Python 2.7.18
Target OS:  Kali linux (Debian)

### Debug Output With Command String  
└─$ python -m pip install impacket
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.                                                                     
Defaulting to user installation because normal site-packages is not writeable
Collecting impacket
  Downloading impacket-0.9.22.tar.gz (1.4 MB)
     |████████████████████████████████| 1.4 MB 9.4 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bPR8zT/impacket/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bPR8zT/impacket/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bz9BZ2                                                  
         cwd: /tmp/pip-install-bPR8zT/impacket/                                            
    Complete output (10 lines):                                                            
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extras_require'                                                                              
      warnings.warn(msg)                                                                   
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'                                                                            
      warnings.warn(msg)                                                                   
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]                  
       or: setup.py --help [cmd1 cmd2 ...]                                                 
       or: setup.py --help-commands                                                        
       or: setup.py cmd --help                                                             
                                                                                           
    error: invalid command 'egg_info'                                                      
    ----------------------------------------                                               
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.   

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
I tried to install with pip3 and impacket module can only be used with python3 and not python command.
This is the error with python command:
Traceback (most recent call last):
  File "xxx.py", line 3, in <module>
    from impacket import smb, ntlm
ImportError: No module named impacket

**Comment by Fox0nTheRun** [comment]
The same error occurs for 'pip install .'.

**Comment by Fox0nTheRun** [comment]
Aight will take a look and respond back

**Comment by gg0h** [comment]
@0xdeaddood I had the exact same issue and this fixed it, thank you!

**Comment by Fox0nTheRun** [comment]
@0xdeaddood Thank you so much! It worked!
