### ISSUE TITLE
ModuleNotFoundError: No module named 'impacket.examples.utils'

### ISSUE THREAD

**Issue by mayben0x** [SecureAuthCorp/impacket#1083]
Traceback (most recent call last):
  File "mssqlclient.py", line 25, in <module>
    from impacket.examples.utils import parse_target
ModuleNotFoundError: No module named 'impacket.examples.utils'

### Configuration  
impacket version:  mssqlclient.py
Python version:  3.8 and 2.7 both not working
Target OS:  

### Debug Output With Command String  
i.e.  
smbexec -debug domain/user:password@127.0.0.1  
```
smbexec -debug domain/user:password@127.0.0.1
[+] StringBinding ncacn_np:127.0.0.1[\pipe\svcctl]
[+] Executing %COMSPEC% /Q /c echo cd  ^> \\127.0.0.1\C$\__output 2^>^&1 > %TEMP%\execute.bat & %COMSPEC% /Q /c %TEMP%\execute.bat & del %TEMP%\execute.bat
[!] Launching semi-interactive shell - Careful what you execute
C:\Windows\system32>net group
[+] Executing %COMSPEC% /Q /c echo net group ^> \\127.0.0.1\C$\__output 2^>^&1 > %TEMP%\execute.bat & %COMSPEC% /Q /c %TEMP%\execute.bat & del %TEMP%\execute.bat
Traceback (most recent call last):
  File "/usr/lib64/python3.7/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'RemoteShell' object has no attribute 'do_net'
```

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
Space for additional context, investigative results, suspected issue.

**Comment by martingalloar** [comment]
Hi! Can you please check this recent https://github.com/SecureAuthCorp/impacket/issues/1078#issuecomment-840709679?

**Comment by PrinceofChum** [comment]
I'm still having the issue..
`from impacket.examples.utils import parse_target
ModuleNotFoundError: No module named 'impacket.examples.utils'
`

**Comment by Hackndo** [comment]
I had the same issue, because of concurrent impacket installs. You should clean all of your impacket installations and try a fresh install.
```bash
# First uninstall all impacket versions
pip uninstall impacket
pip3 uninstall impacket
python -m pip uninstall impacket
python3 -m pip uninstall impacket
sudo apt-remove python-impacket

# Then install the latest version, either from source
python setup.py install
# OR (but not both) from pip
pip install impacket
```
