### ISSUE TITLE
please release a new version

### ISSUE THREAD

**Issue by blshkv** [SecureAuthCorp/impacket#1091]
https://src.fedoraproject.org/rpms/python-impacket/tree/rawhide
https://www.cvedetails.com/vulnerability-list/vendor_id-24515/product_id-95007/version_id-657819/opec-1/Secureauth-Impacket-%2A.html

The current release is vulnerable and does not support python 3.9.
You can help a lot to all Linux maintainers if you could start releasing it regularly, so we won't need to monitor and push all these additional patches

**Comment by 0xdeaddood** [comment]
Hi @blshkv!
We are planning to release a new version this week.
