### ISSUE TITLE
Wildcard searching with objectGUID not working 

### ISSUE THREAD

**Issue by daddycocoaman** [SecureAuthCorp/impacket#1110]
### Configuration  
impacket version:  0.9.23
Python version:  3.9.5
Target OS:  Windows

Thanks for maintaining this library. My issue is that wildcard searching with objectGUID does not work. For example, `(&(objectCategory=computer)(objectGUID=\\00*))` should return all objects where the fourth byte in big endian is 00 but nothing returns. Searching by that byte might seem strange but it's in my best interest. :)

Anyway, this is a valid query and is confirmed with `Get-ADObject -LDAPFilter "(&(objectCategory=computer)(objectGuid=\00*))"` which returns the objects expected.

It looks like the parse doesn't account for this particular case but I'm not sure the best way to handle that or if I would break anything if I tried to fix and PR it. But basically, there should be some additional logic for any LDAP property that's stored in big endian like objectGUID and objectSIDs are.

Here is the filter after the string is parsed. The reason double backslashes has to be used is to prevent the single backlash from being parsed into an ascii `5C`. But if the double backslash is sent to the server, it's not really a valid query.

```
(&(objectCategory=computer)(objectGUID=\\00*))
Filter:
 and=SetOf:
  Filter:
   equalityMatch=AttributeValueAssertion:
    attributeDesc=objectCategory
    assertionValue=computer

  Filter:
   substrings=SubstringFilter:
    type=objectGUID
    substrings=SequenceOf:
     Choice:
      initial=\\00
```

https://github.com/SecureAuthCorp/impacket/blob/142cacb649b8c6441df9330ac22fe4d15a0d1bbc/impacket/ldap/ldap.py#L582

**Comment by daddycocoaman** [comment]
For some wild reason, the solution was to not follow the guidance for backslash. I was able to accomplish this search with something like:

```python
for num in range(0, 255):
    search_filter = f"(&(objectCategory=computer)(objectGUID={chr(num)}*))"
```

Wild.

Closing and leaving this for future lurkers.

**Comment by 0xdeaddood** [comment]
Hi @daddycocoaman! There is an issue creating LDAP filters #975. It's something I'll be working on shortly.
Thanks for reporting.
