### ISSUE TITLE
list command returns "'NoneType' object has no attribute 'upper'"

### ISSUE THREAD

**Issue by XSchelin** [SecureAuthCorp/impacket#1111]
### Configuration  
impacket version:  v0.9.23
Python version: 3.9.4
Target OS:  Windows 10

### Command and results

I run the command `services list`, and I immediately get back the following:

```
Impacket v0.9.23 - Copyright 2021 SecureAuth Corporation

Traceback (most recent call last):
  File "C:\Users\User.Name\AppData\Local\Programs\Python\Python39\Scripts\services.py", line 350, in <module>
    services = SVCCTL(username, password, domain, options, int(options.port))
  File "C:\Users\User.Name\AppData\Local\Programs\Python\Python39\Scripts\services.py", line 39, in __init__
    self.__action = options.action.upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

I got around it temporarily by adding this to services.py at line 325:

```
    if options.target == 'list':
        options.action = 'list'
```

(Right after options is set to the parser args.)

But I'm not a programmer and so I'm not certain that's a valid fix.

**Comment by 0xdeaddood** [comment]
Hi @XSchelin! How are you running `services`? If you try something like this: `services domain/username:password@targetName list` , it should work fine.

**Comment by 0xdeaddood** [comment]
No answer, closing. Reopen if needed.
