### ISSUE TITLE
Error: local variable 'bytesNeeded' referenced before assignment

### ISSUE THREAD

**Issue by derrickberg-dev** [SecureAuthCorp/impacket#1116]
It looks like this function, hRpcAsyncEnumPrinterDrivers is referencing 'bytesNeeded' before its assigned to anything? 

Where's the value of bytesNeeded supposed to come from when this function is called? An exception?

https://github.com/SecureAuthCorp/impacket/blob/4821d64e3a078a79e60c0b03f08d0984d9a17728/impacket/dcerpc/v5/rprn.py#L636-L675

https://github.com/SecureAuthCorp/impacket/blob/6da655ca9ac4f9c2a207ea47e79d089044accd78/impacket/dcerpc/v5/par.py#L546-L585

**Comment by 0xdeaddood** [comment]
Hi @derrickberg-dev. The parameter 'cbBuf' represents the size in bytes of the buffer. As we don't know this value, we do two calls with the function. The first one will fail (ERROR_INSUFFICIENT_BUFFER. 122 (0x7A)) and return a pointer 'pcbNeeded' with the required size. Catching this exception, the bytesNeeded parameter is populated and we can make the final request with all the proper values.

**Comment by 0xdeaddood** [comment]
Closing. Re-open if needed.
