### ISSUE TITLE
Ntlmrelayx stuck at  "Downgrading to standard security"

### ISSUE THREAD

**Issue by basketas** [SecureAuthCorp/impacket#1126]
I am testing the new PetitPotam attack, and the hashes are successfully captured using Responder, but not with NTLMrelayX.
It just outputs "Downgrading to standard security" and nothing else happens...

 Configuration  
impacket version:  0.9.23
Python version: 3 
Target OS:  Ubuntu 20.04

 Debug Output With Command String  
```
ntlmrelayx.py -debug
[+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket
[*] Protocol Client MSSQL loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client DCSYNC loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[+] Protocol Attack DCSYNC loaded..
[+] Protocol Attack RPC loaded..
[+] Protocol Attack HTTP loaded..
[+] Protocol Attack HTTPS loaded..
[+] Protocol Attack MSSQL loaded..
[+] Protocol Attack SMB loaded..
[+] Protocol Attack LDAP loaded..
[+] Protocol Attack LDAPS loaded..
[+] Protocol Attack IMAP loaded..
[+] Protocol Attack IMAPS loaded..
[*] Running in reflection mode
[*] Setting up SMB Server
[*] Setting up HTTP Server
[*] Setting up WCF Server

[*] Servers started, waiting for connections
[+] Downgrading to standard security
[+] Downgrading to standard security
```

![image](https://user-images.githubusercontent.com/16399561/126821025-c1bba1f7-4ce7-43eb-ad0b-ebaab89b6657.png)

**Comment by 0xdeaddood** [comment]
Hi @basketas! 

Are you trying to do a reflection attack? PetitPotam triggers an NTLM auth over SMB that you are trying to reflect to the same machine. SMB->SMB reflection attack is patched since MS08-068. 

If you want to relay this auth, run `ntlmrelayx.py` defining a target machine with `-t` (it has to be a different machine than the one you are targeting with PetitPotam).

**Comment by basketas** [comment]
I am just trying to catch and display the net-ntlm machine account hashes.. 
Responder is showing them just fine with the same attack

**Comment by mpgn** [comment]
then use responder ;)

**Comment by basketas** [comment]
The question is only if ntlmrelayx supports grabbing and presenting the hashes like e.g. Responder does, or it must be further relayed.. 
If it does support it, then I am doing something wrong or there is a bug..

**Comment by mpgn** [comment]
What are you trying to achieve ?

**Comment by lnaphade** [comment]
where can be get impacket version: 0.9.24 stream

**Comment by 0xdeaddood** [comment]
> The question is only if ntlmrelayx supports grabbing and presenting the hashes like e.g. Responder does, or it must be further relayed..
> If it does support it, then I am doing something wrong or there is a bug..

`ntlrmelayx.py` is not intended for _passive use_, where you can just capture and show the intercepted hashes. However, if you set a target machine to relay the credentials, you can use the option `--output-file FILE_NAME` where the encrypted hashes will be saved.
 
Something like this should work: `ntlrmelayx.py -t SOME_MACHINE -smb2support --output-file HASHES`

**Comment by 0xdeaddood** [comment]
No answer, closing. Reopen if needed.
