### ISSUE TITLE
Bug in dpapi.py module - CREDENTIAL_BLOB dump() function

### ISSUE THREAD

**Issue by w0rmh013** [SecureAuthCorp/impacket#1129]
There's a bug in the dpapi.py module - CREDENTIAL_BLOB struct - dump() function.
Dumping errors are caused due to use of wrong enum type in a print statement.

I've submitted a PR to fix it.
[Pull Request - dpapi.py bug fix](https://github.com/SecureAuthCorp/impacket/pull/1073)

**Comment by 0xdeaddood** [comment]
Fixed in #1073. Thanks @w0rmh013!
