### ISSUE TITLE
Blackeye issue - No hyperlinks

### ISSUE THREAD

**Issue by cooperpro62** [SecureAuthCorp/impacket#1148]
Hi Guys, I'm experiencing issue with Blackeye. I tried several versions and updates which should resolve the issue, but nothing to do... I didn't find any hyperlinks to send to the target. 
Is there somebody who has a solution?
Thanks much in advance for your help.
Have a nice day

**Comment by martingalloar** [comment]
Hey @cooperpro62! This repository is about Impacket and we do not support third party tools. I suggest you to check out their contact and try to report to their devs/maintainers/community. Good look with the tool!
