### ISSUE TITLE
[feature request] Invoke-ShareFinder equivalent in impacket

### ISSUE THREAD

**Issue by CaledoniaProject** [SecureAuthCorp/impacket#1176]
Is anyone interested in creating an equivalent of this [Invoke-ShareFinder](https://github.com/darkoperator/Veil-PowerView/blob/master/PowerView/functions/Invoke-ShareFinder.ps1) script? Looks quite useful to me.

P.S: please consider add a Feature Request to your bug report template.

**Comment by CaledoniaProject** [comment]
@p0dalirius Hi there!

Invoke-ShareFinder is capable to find all shares in a domain, but FindUncommonShares targets specific computer only.

Invoke-ShareFinder first launches LDAP query to find all computers, then enum all the shares on the target computer, can you add this logic?
* https://github.com/darkoperator/Veil-PowerView/blob/master/PowerView/functions/Invoke-ShareFinder.ps1#L821
* https://github.com/darkoperator/Veil-PowerView/blob/master/PowerView/functions/Invoke-ShareFinder.ps1#L907

**Comment by p0dalirius** [comment]
@CaledoniaProject you can open an issue in my project if you want.

I think it was a DNS issue in your case. My latest commit should solve the problem since I perform DNS lookups directly from the domain controller in the script.

**Comment by CaledoniaProject** [comment]
I confirm this issue is resolved, and I'll open issue in your repo if I found anymore issues, thanks p0dalirius!
