### ISSUE TITLE
Malware detection on example files secretsdump.py

### ISSUE THREAD

**Issue by jax79sg** [SecureAuthCorp/impacket#1191]
Hi, 

The file https://github.com/SecureAuthCorp/impacket/blob/master/examples/secretsdump.py is being detected by multiple vendors as malware. Is this expected to be because of the script's behaviour?

**Comment by 0xdeaddood** [comment]
Hi @jax79sg!

We received some reports related to malware detection on some example scripts, including secretsdump.py. If the detection occurs during execution, you can try modifying the code (as it's mentioned [here](https://github.com/SecureAuthCorp/impacket/issues/777#issuecomment-1048253251)). 

Closing. Reopen if you need more help whit this.

**Comment by asadzz** [comment]
I can't find the code on `Impacket v0.10.0 `

**Comment by michael-o** [comment]
Windows Defender just flagged the soure tarball as `Trojan:Win32/IngressImpacket!BV`, ZScaler also qualifies https://pkgmir.geo.freebsd.org/FreeBSD:13:amd64/quarterly/All/py311-impacket-0.12.0.pkg as malware.
