### ISSUE TITLE
Keep errors for SVCManager

### ISSUE THREAD

**Issue by superdale007** [SecureAuthCorp/impacket#1218]
Apologize if this is a n00b issue.

impacket version:  v0.9.24
Python version:  I've tried v2.7 and v3
Target OS:  Windows 10

kali> impacket-psexec -hashes aad3b435b51404eeaad3b435b51404ee:27fb740470ffab5a507301477c0fdf14 bwayne@172.31.37.20 cmd.exe
Impacket v0.9.22 - Copyright 2020 SecureAuth Corporation

[*] Requesting shares on 172.31.37.20.....
[-] share 'ADMIN$' is not writable.
[-] share 'C$' is not writable.
[*] Found writable share dev
[*] Uploading file HvuoTwPR.exe
[*] Opening SVCManager on 172.31.37.20.....
[-] Error opening SVCManager on 172.31.37.20.....
[-] Error performing the installation, cleaning up: Unable to open SVCManager

**Comment by mubix** [comment]
Your user doesn't have permission to write to the C$ or ADMIN$ directories, this means they are not an Admin, generally you need to be an Admin to open the Service Manager.

**Comment by superdale007** [comment]
Hey mubix! 
Bwayne is a local admin
![user](https://user-images.githubusercontent.com/18034473/144117742-6e2aa6d8-ec3c-493b-821d-66f78bebec15.png)
.

**Comment by superdale007** [comment]
That got me a little further....after a 30-45 second wait, it shows
![user](https://user-images.githubusercontent.com/18034473/144122606-56082bed-c021-431f-b3ea-ba2b978b0865.png)
:

**Comment by superdale007** [comment]
Got it...had to join the computer to the domain..once you do that (even though it was disabled beforehand) I had to return off "real-time protection" on the box. THANKS EVERYONE!

**Comment by 0xdeaddood** [comment]
Thanks for the confirmation. Closing...
