### ISSUE TITLE
addcomputer (SAMR method) doesn't set SPNs

### ISSUE THREAD

**Issue by ShutdownRepo** [SecureAuthCorp/impacket#1223]
Hello everyone, I just noticed addcomputer.py doesn't set the `dNSHostName` and `servicePrincipalName` attributes when creating an account using the SAMR method, while it does so when relying on LDAPS.

![Screenshot from 2021-12-10 21-41-57](https://user-images.githubusercontent.com/40902872/145638942-d34ae9f3-f964-4fd4-b829-074775ca79c4.png)

**Comment by 0xdeaddood** [comment]
Hi Charlie!

We were discussing this point [`here`](https://github.com/SecureAuthCorp/impacket/issues/1077). The final steps in the SAMR flow are executed via LDAP. For that reason, both methods were kept separated. @jagotu explained the different scenarios we support and some possible solution to set the missing attributes. At the moment, we don't implement any changes.

Closing this one, but feel free to join the discussion in the other thread.
