### ISSUE TITLE
Name o Serice Not known Python, Python2, Python3

### ISSUE THREAD

**Issue by AlecWhyte** [SecureAuthCorp/impacket#1232]
Traceback (most recent call last):
  File "/home/kali/impacket/examples/mssqlclient.py", line 169, in <module>
    ms_sql.connect()
  File "/home/kali/.local/lib/python3.9/site-packages/impacket/tds.py", line 531, in connect
    af, socktype, proto, canonname, sa = socket.getaddrinfo(self.server, self.port, 0, socket.SOCK_STREAM)[0]
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Not sure if this is normal, tried install with pip2 and pip3 python, python2, python3 can't seem to get it to work.**

**Comment by 0xdeaddood** [comment]
Hi @AlecWhyte!

How are you running the script? `[Errno -2] Name or service not known` means that the name resolution is failing for the domain/machine that you define as the target. Check your DNS settings and verify that you are defining the correct target name.

**Comment by 0xdeaddood** [comment]
No answer, closing. Please re-open if needed.
