### ISSUE TITLE
Installation error: pylnk3

### ISSUE THREAD

**Issue by christianbj87** [SecureAuthCorp/impacket#1244]
python3 -m pip install .
                                                 
Processing /home/admin123/impacket
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220119.101925.12de27dc) (4.0.0)
Requirement already satisfied: flask>=1.0 in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220119.101925.12de27dc) (2.0.1)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220119.101925.12de27dc) (0.18.2)
Requirement already satisfied: ldap3!=2.5.0,!=2.5.2,!=2.6,>=2.5 in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220119.101925.12de27dc) (2.8.1)
Requirement already satisfied: ldapdomaindump>=0.9.0 in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220119.101925.12de27dc) (0.9.3)
Requirement already satisfied: pyOpenSSL>=0.16.2 in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220119.101925.12de27dc) (21.0.0)
Requirement already satisfied: pyasn1>=0.2.3 in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220119.101925.12de27dc) (0.4.8)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220119.101925.12de27dc) (3.11.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220119.101925.12de27dc) (1.16.0)
Building wheels for collected packages: impacket
  Building wheel for impacket (setup.py) ... done
  Created wheel for impacket: filename=impacket-0.9.25.dev1+20220119.101925.12de27dc-py3-none-any.whl size=1433877 sha256=9b86d735d27afcfdb9ae709bf95e4a366949cfc9c9cf186ab2b0047312313da0
  Stored in directory: /tmp/pip-ephem-wheel-cache-sc37oedg/wheels/ec/c1/66/2c232bb334f21da0bc0c7c5aa64e3b2ee18cfcf37f071d11f5
Successfully built impacket
Installing collected packages: impacket
  Attempting uninstall: impacket
    Found existing installation: impacket 0.9.25.dev1+20220119.101925.12de27dc
    Uninstalling impacket-0.9.25.dev1+20220119.101925.12de27dc:
      Successfully uninstalled impacket-0.9.25.dev1+20220119.101925.12de27dc

**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.                                                                     
crackmapexec 5.2.2 requires pylnk3<0.4.0,>=0.3.0, but you have pylnk3 0.4.2 which is incompatible.**   
                                                             
Successfully installed impacket-0.9.25.dev1+20220119.101925.12de27dc

Then i can run smbserver.py wiothout problems, but have that error when installing.

**Comment by 0xdeaddood** [comment]
Hi @christianbj87!

`pylnk3` is not a package required by Impacket. I don't know why pip warns that, maybe it's a new behavior of its dependency resolver or a bug... 

Closing.
