### ISSUE TITLE
cannot import name 'RAWRelayServer' from 'impacket.examples.ntlmrelayx.servers'

### ISSUE THREAD

**Issue by 0xGreen** [SecureAuthCorp/impacket#1250]
Hi,

Just updated kali with apt update and apt upgrade and start getting error for ntlmrelayx.py

### Configuration  
impacket version:  0.9.24
Python version:  3.9
Target OS:  Windows 7
Main OS: Kali 

```
㉿examples# python3 ntlmrelayx.py -h
Traceback (most recent call last):
  File "/root/temp/impacket/examples/ntlmrelayx.py", line 51, in <module>
    from impacket.examples.ntlmrelayx.servers import SMBRelayServer, HTTPRelayServer, WCFRelayServer, RAWRelayServer
ImportError: cannot import name 'RAWRelayServer' from 'impacket.examples.ntlmrelayx.servers' (/usr/lib/python3/dist-packages/impacket/examples/ntlmrelayx/servers/__init__.py)
```

Also tried the git version and same errot.

Other tools like smarelayx, smbserver, wmiexec etc are working fine.

**Comment by mpgn** [comment]
On impacket folder: `python3 -m pip install . --user`

**Comment by 0xdeaddood** [comment]
Hi @0xGreen!

That module was added yesterday. It seems there is a mismatch version between the example scripts and the installed impacket library in your environment. Try what @mpgn mentions.

**Comment by 0xGreen** [comment]
Thank you @mpgn and @0xdeaddood!

It works, below is the output when i ran `python3 -m pip install . --user`

```bash
Processing /root/Downloads/impacket
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220201.191645.d8679837) (4.0.0)
Requirement already satisfied: flask>=1.0 in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220201.191645.d8679837) (1.1.2)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220201.191645.d8679837) (0.18.2)
Requirement already satisfied: ldap3!=2.5.0,!=2.5.2,!=2.6,>=2.5 in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220201.191645.d8679837) (2.8.1)
Requirement already satisfied: ldapdomaindump>=0.9.0 in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220201.191645.d8679837) (0.9.3)
Requirement already satisfied: pyOpenSSL>=0.16.2 in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220201.191645.d8679837) (21.0.0)
Requirement already satisfied: pyasn1>=0.2.3 in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220201.191645.d8679837) (0.4.8)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220201.191645.d8679837) (3.11.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from impacket==0.9.25.dev1+20220201.191645.d8679837) (1.16.0)
Building wheels for collected packages: impacket
  Building wheel for impacket (setup.py) ... done
  Created wheel for impacket: filename=impacket-0.9.25.dev1+20220201.191645.d8679837-py3-none-any.whl size=1441700 sha256=0c33b42398bed581f6e4a8cf6f1a5416986e144be0eca6c90de134d6cd48adb1
  Stored in directory: /tmp/pip-ephem-wheel-cache-lhf4_44i/wheels/56/9f/00/5efb6b12f8bec118a26b1314efb9535abcbc86e96021c99664
Successfully built impacket
Installing collected packages: impacket
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
crackmapexec 5.2.2 requires bs4<0.0.2,>=0.0.1, which is not installed.
crackmapexec 5.2.2 requires lsassy>=3.0.0, but you have lsassy 2.1.2 which is incompatible.
crackmapexec 5.2.2 requires neo4j<5.0.0,>=4.1.1, but you have neo4j 1.7.0.dev0 which is incompatible.
crackmapexec 5.2.2 requires pylnk3<0.4.0,>=0.3.0, but you have pylnk3 0.4.2 which is incompatible.
crackmapexec 5.2.2 requires pywerview<0.4.0,>=0.3.2, but you have pywerview 0.2.0 which is incompatible.
Successfully installed impacket-0.9.25.dev1+20220201.191645.d8679837
```

Is there something going on between impacket and cme behind the scene?

**Comment by mpgn** [comment]
pip related no worry

**Comment by 0xGreen** [comment]
Thank you!

**Comment by georgiabasser** [comment]
@mpgn I'm trying to follow your instructions "On impacket folder: python3 -m pip install . --user" and I get the following error: 

┌──(python3-venv)(root💀remote-sentinel-032)-[/home/pentester/app/impacket]
└─# python3 -m pip install . --user
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

what am I doing wrong???

**Comment by NgoHuy** [comment]
> @mpgn I'm trying to follow your instructions "On impacket folder: python3 -m pip install . --user" and I get the following error:
> 
> ┌──(python3-venv)(rootskullremote-sentinel-032)-[/home/pentester/app/impacket] └─# python3 -m pip install . --user ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
> 
> what am I doing wrong???

in virtualenv, no user home, then remove --user

**Comment by georgiabasser** [comment]
Sorry, sir but I'm still lost. "no user home"? I'm logged in as root on my
system and the /home/pentester/app/impacket directory where the impacket
scripts are. Prior to moving to that location I invoke a
virtual environment, i.e. my python3-venv. I've already installed impacket
and used other scripts successfully so still at a loss? Thanks in advance
for your help.

rc

Richard Coleman
(601) 209-4057

**Comment by 0xGreen** [comment]
Hi Richard,

When you are running Impacket within a virtual environment you don't need --user flag because there is no user home directory available inside the virtual environment.

So instead of `python3 -m pip install . --user`  run `python3 -m pip install .`

**Comment by thibon** [comment]
FYI when using piping, after installing with python3 -m pip install . I get the following error :
> [*] Protocol Client IMAP loaded..
> [*] Protocol Client DCSYNC loaded..
> Traceback (most recent call last):
>   File "/Users/thibaut/Github/Windows/impacket/examples/ntlmrelayx.py", line 384, in <module>
>     from impacket.examples.ntlmrelayx.attacks import PROTOCOL_ATTACKS
>   File "/Users/thibaut/.local/share/virtualenvs/impacket-dE9kthX5/lib/python3.9/site-packages/impacket/examples/ntlmrelayx/attacks/__init__.py", line 56, in <module>
>     __import__(package + '.' + os.path.splitext(file)[0])
>   File "/Users/thibaut/.local/share/virtualenvs/impacket-dE9kthX5/lib/python3.9/site-packages/impacket/examples/ntlmrelayx/attacks/smbattack.py", line 23, in <module>
>     from impacket.examples.smbclient import MiniImpacketShell
>   File "/Users/thibaut/.local/share/virtualenvs/impacket-dE9kthX5/lib/python3.9/site-packages/impacket/examples/smbclient.py", line 40, in <module>
>     import pyreadline as readline
>   File "/Users/thibaut/.local/share/virtualenvs/impacket-dE9kthX5/lib/python3.9/site-packages/pyreadline/__init__.py", line 12, in <module>
>     from . import logger, clipboard, lineeditor, modes, console
>   File "/Users/thibaut/.local/share/virtualenvs/impacket-dE9kthX5/lib/python3.9/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
>     from .win32_clipboard import GetClipboardText, SetClipboardText
>   File "/Users/thibaut/.local/share/virtualenvs/impacket-dE9kthX5/lib/python3.9/site-packages/pyreadline/clipboard/win32_clipboard.py", line 39, in <module>
>     from pyreadline.keysyms.winconstants import CF_UNICODETEXT, GHND
>   File "/Users/thibaut/.local/share/virtualenvs/impacket-dE9kthX5/lib/python3.9/site-packages/pyreadline/keysyms/__init__.py", line 23, in <module>
>     raise ImportError("Could not import keysym for local pythonversion", x)
> NameError: name 'x' is not defined

Related to #1098

Looks like adding 
``
x = "blah" to __init__.py
``
is working somehow

**Comment by gr33nr4t** [comment]
You can delete line 52 of the code 

`from impacket.examples.ntlmrelayx.servers import SMBRelayServer, HTTPRelayServer, WFCRelayServer,RawRelayServer`

And replace it with 

`from impacket.examples.ntlmrelayx.servers.httprelayserver import HTTPRelayServer
from impacket.examples.ntlmrelayx.servers.smbrelayserver import SMBRelayServer
from impacket.examples.ntlmrelayx.servers.wcfrelayserver import WCFRelayServer
from impacket.examples.ntlmrelayx.servers.rawrelayserver import RAWRelayServer`

this worked for me.
