### ISSUE TITLE
NTLMRelayx add option to concurrently dump NET-NTLM Hashes, as in responder

### ISSUE THREAD

**Issue by falkebo** [SecureAuthCorp/impacket#1263]
During a pentesting, while trying to relay possible domadmin credentials, it would be great to also dump the collected NET-NTLM Hashes, for possible offline cracking (just like responder does). Currently you have to choose. Either enable SMB Server in responder and collect hashes, or try to relay hashes. Both is not possible.

**Comment by 0xdeaddood** [comment]
Hi @falkebo!

You can capture anything that is relayed with the `--output-file` option: https://github.com/SecureAuthCorp/impacket/issues/653#issuecomment-617991250

**Comment by falkebo** [comment]
Hi @0xdeaddood does this includes the "raw" NTLMv1 / NTLMv2 Hashes, just like they can be captured with responder?

**Comment by falkebo** [comment]
Nevermind, you are right.
Thanks @0xdeaddood
