### ISSUE TITLE
Ccache to Kirbi conversion issue, missing hostname part in sname

### ISSUE THREAD

**Issue by ShutdownRepo** [SecureAuthCorp/impacket#1264]
### Configuration  
impacket version:  Impacket v0.9.25.dev1+20220208.122405.769c3196
Python version:  Python 3.9.10

### Issue

When obtaining a service ticket with getST, converting the `.ccache` ticket to `.kirbi`, and then doing `.kirbi` to `.ccache` results in a ticket missing a part in `sname`'s hostname.

![Screenshot from 2022-02-20 11-58-41](https://user-images.githubusercontent.com/40902872/154839256-1faf2a9b-c9b6-4851-aca9-98be27bb4941.png)

The issue also happens without the `-impersonate` flag.

I have located the error to be on the Ccache to Kirbi conversion.

![Screenshot from 2022-02-19 14-20-33](https://user-images.githubusercontent.com/40902872/154839438-47305c03-92ac-4577-b17e-5a4e1a0c9c2e.png)

![Screenshot from 2022-02-19 14-41-26](https://user-images.githubusercontent.com/40902872/154839439-2b729e50-0b98-4ef4-b7b5-2a73ff919ee1.png)

### Additional context

Issue raised there: https://github.com/SecureAuthCorp/impacket/pull/1260#issuecomment-1046168265

**Comment by wqreytuk** [comment]
I don't think this is a problem, it has no negative impact on the use of tickets

**Comment by ShutdownRepo** [comment]
It clearly has a negative impact, and you were the one who demonstrated it.

**Comment by wqreytuk** [comment]
> It clearly has a negative impact, and you were the one who demonstrated it.

you mean can not be imported directly?

**Comment by wqreytuk** [comment]
and you have solved this problem by modifying ticketConvertrt.py?

**Comment by wqreytuk** [comment]
> 

if you mean this, then it is not ticketConvert.py's fault, my ticket after converted can be imported and used even the description of it is not correct

**Comment by ShutdownRepo** [comment]
@wqreytuk worked together on the issues we faced with the service substitution and ticket conversion. 

The issues are now fixed (https://github.com/SecureAuthCorp/impacket/pull/1202#issuecomment-1046315551). The initial issue with the conversion from Ccache to Kirbi was fixed in #1265 

The other issue with incomplete service substitution was fixed in two separate PRs commits: https://github.com/SecureAuthCorp/impacket/pull/1202/commits/8953d05192565d9949f463e421fd2da78dd82e39 and https://github.com/SecureAuthCorp/impacket/pull/1256/commits/f71c3bbaeb4f8f9adda0efdc59450c8529d1f805

**Comment by 0xdeaddood** [comment]
Fixed. Thanks @ShutdownRepo and @wqreytuk!

**Comment by wqreytuk** [comment]
> Thanks

glad to make some contributions
