### ISSUE TITLE
Installation Issue on py3.10.2

### ISSUE THREAD

**Issue by bntr00t** [SecureAuthCorp/impacket#1266]
### Configuration  
impacket version:  impacket-0.9.24
Python version:  Fresh Install 3.10.2
Target OS:  Win10 21H2

### Additional context  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> impacket

Full output:
[https://8n1.org/raw/20335/09d1](url)

**Comment by 0xdeaddood** [comment]
Hi @bntr00t!

From what I can see in the log you shared, there should be an antivirus blocking the installation (it's failing when the mimikatz.py script is copied). We received some reports about [this](https://github.com/SecureAuthCorp/impacket/issues/911#issuecomment-693266814). Did you get any alert from your AV?

**Comment by bntr00t** [comment]
Nope, no reports and I'm using standard Win Defender

**Comment by 0xdeaddood** [comment]
I'd have bet on that... 

I tried to replicate your issue in my environment (Win10 20H2 19042.985 and Python 3.10.2) and the installation was successfully. There should be another thing in your setup.

Take into account that Impacket doesn't "officially" support Python 3.10 (it's experimental for now). Try with a lower version of Python.  Additionally, try using a virtual environment for the installation.

**Comment by bntr00t** [comment]
*21H2 but that's fine

Probably the support issue, I'll downgrade to 3.9 thanks :D

**Comment by 0xdeaddood** [comment]
> *21H2 but that's fine
> 
> Probably the support issue, I'll downgrade to 3.9 thanks :D

Tested on a `Win10 21H2`, it works too. Let me know how it goes with version 3.9.

**Comment by bntr00t** [comment]
https://8n1.org/raw/20338/f018

3.9.10 getting this right after fresh python install

**Comment by bntr00t** [comment]
after a fresh install of windows, defender was finally able to show me that it did sum, 

file: C:\Users\bnt\AppData\Local\Temp\pip-install-8399hbu9\impacket_8bae9bcffde349658c537d8669c31adf\examples\mimikatz.py

i allowed it and everything worked, goddamn windows, using 3.9.10
