### ISSUE TITLE
getST.py KDC_ERR_WRONG_REALM error when get a referral ticket without dns

### ISSUE THREAD

**Issue by 12end** [SecureAuthCorp/impacket#1277]
### Configuration  
impacket version:  0.9.24
Python version:  3.9.7
Target OS:  windows server 2012 r2(dc01.sub.local.com);windows server 2012 r2(dc.local.com)
Target IP: 192.168.31.210(dc01.sub.local.com);192.168.31.200(dc.local.com)
### Debug Output With Command String  
```
getST.py -dc-ip 192.168.31.210 -spn cifs/dc.local.com@local.com sub.local.com/administrator -k -no-pass -debug
[+] Impacket Library Installation Path: /usr/local/lib/python3.9/site-packages/impacket
[+] Using Kerberos Cache: administrator.ccache
[+] Returning cached credential for KRBTGT/SUB.LOCAL.COM@SUB.LOCAL.COM
[*] Using TGT from cache
[*] Getting ST for user
[+] Trying to connect to KDC at 192.168.31.210
[+] Trying to connect to KDC at 192.168.31.210
[+] Server time (UTC): 2022-03-14 06:19:57
Traceback (most recent call last):
  File "/usr/local/bin/getST.py", line 748, in <module>
    executer.run()
  File "/usr/local/bin/getST.py", line 655, in run
    tgs, cipher, oldSessionKey, sessionKey = getKerberosTGS(serverName, domain, self.__kdcHost, tgt, cipher, sessionKey)
  File "/usr/local/lib/python3.9/site-packages/impacket/krb5/kerberosv5.py", line 468, in getKerberosTGS
    return getKerberosTGS(serverName, domain, kdcHost, r, cipher, newSessionKey)
  File "/usr/local/lib/python3.9/site-packages/impacket/krb5/kerberosv5.py", line 438, in getKerberosTGS
    r = sendReceive(message, domain, kdcHost)
  File "/usr/local/lib/python3.9/site-packages/impacket/krb5/kerberosv5.py", line 91, in sendReceive
    raise krbError
impacket.krb5.kerberosv5.KerberosError: Kerberos SessionError: KDC_ERR_WRONG_REALM(Reserved for future use)
Kerberos SessionError: KDC_ERR_WRONG_REALM(Reserved for future use)
```

### Additional context  
in this case,I want generate a SIDHistory cross-domain golden ticket(no dns)
`ticketer.py -nthash [krbtgt] -domain sub.local.com -dc-ip 192.168.31.210 -domain-sid  S-1-5-21-3246485242-2847592758-390507984 administrator -extra-sid S-1-5-21-3699338023-2969729399-3120287155-519`
then when use getST.py,some error occur.
first time get a referral ticket,and the realm from sub.local.com to local.com. But impacket still use parameter dc-ip to get ST,and I think it's necessary to allow user manually formulate new KDC-IP(in this case,it shoud be 192.168.31.200) or resolve new KdcHost auto,otherwise in this case it would retrieve an error KDC_ERR_WRONG_REALM

### fix
do dns resolve from dc-ip,and use the result as the new KdcHost
### ugly fix
impacket/kerberosv5.py#467~#471
```python
        new_domain = spn.components[1]
        if new_domain != domain:
            print("Referral TGT's domain(%s) is different from %s",domain,new_domain)
            kdcHost = input("enter KDC IP")
        return getKerberosTGS(serverName, new_domain, kdcHost, r, cipher, newSessionKey)
```

**Comment by 0xdeaddood** [comment]
Hi @12end!

Impacket doesn't support inter-realm tickets (a.k.a. referral tickets) yet. There are a couple of opened tickets where we're discussing the best approach to address it (https://github.com/SecureAuthCorp/impacket/issues/315 and https://github.com/SecureAuthCorp/impacket/pull/541). 

Closing this one. Please let's continue the discussion there.
