### ISSUE TITLE
ImpactDecoder fails with a padded TCP options field

### ISSUE THREAD

**Issue by avivbrg** [SecureAuthCorp/impacket#1285]
### Configuration  
impacket version:  v0.9.24
Python version:  3.9
Target OS:  

### Debug Output With Command String  

```
.../impacket/ImpactPacket.py", line 1579, in get_padded_options
    array_frombytes(op_buf, "\0" * num_pad)
.../impacket/ImpactPacket.py", line 33, in <lambda>
    array_frombytes = lambda array_object, bytes: array_object.frombytes(bytes)
TypeError: a bytes-like object is required, not 'str'
```

### Additional context  

In ImpactPacket.py:1579, there's a missing 'b' before "\0"
`array_frombytes(op_buf, "\0" * num_pad) --> array_frombytes(op_buf, b"\0" * num_pad)`

**Comment by 0xdeaddood** [comment]
Hi @avivbrg! Nice catch. It should be fixed now. Thanks!!

**Comment by avivbrg** [comment]
Thanks for the quick fix :-), any idea when you'll have a new release with the fix?

**Comment by 0xdeaddood** [comment]
Hey @avivbrg! We are targeting next week for the new release
