### ISSUE TITLE
What is the equivalent to `Rubeus.exe asktgt /certificate`?

### ISSUE THREAD

**Issue by CaledoniaProject** [SecureAuthCorp/impacket#1321]
### Configuration  
impacket version:  Impacket v0.9.25.dev1+20220429.192148.b37fd99d - Copyright 2021 SecureAuth Corporation
Python version:  Python 3.8.10
Target OS:  Ubuntu 20.04

### Question

What is the equivalent to `Rubeus.exe asktgt /certificate`? It looks like getTGT.py does not have a certificate option.

**Comment by jagotu** [comment]
It doesn't. If you need a python implementation of PKINIT there's https://github.com/dirkjanm/PKINITtools

**Comment by CaledoniaProject** [comment]
Thanks, that worked fine for me.
