### ISSUE TITLE
Actually connecting to an `examples/smbserver.py` server

### ISSUE THREAD

**Issue by Scripter17** [SecureAuthCorp/impacket#1326]
impacket version 0.10.0, Windows 10

I've been banging my head against this wall for hours now and I cannot find a single person getting stuck here

I run [`smbserver.py TEST C:/ -port 2555 -smb2support`](https://github.com/SecureAuthCorp/impacket/blob/master/examples/smbserver.py), I put `\\localhost:2555` into windows explorer, I get an error about how it can't find the server

Sharing folders via the builtin windows server works just fine but *something* about how this is implemented refuses to work

![image](https://user-images.githubusercontent.com/25886989/169801542-600e5c52-a9eb-410f-a704-1722b2864848.png)

**Comment by erikgeiser** [comment]
As far as I know, the port in UNC paths is separated with `@` instead of `:`. Maybe give `\\localhost:2555` a try.

**Comment by Scripter17** [comment]
Weirdly I an connect to the server from my phone (with `-ip 0.0.0.0`) so I know it works, but windows still won't open it

I've tried `\\localhost:2555`, `\\localhost@2555`, `\\127.0.0.1:2555`, `\\127.0.0.1@2555`, `\\[my laptop's name]:2555`, `\\[my laptop's name]@2555`

[The docs I've found](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths) seem silent on port formatting, but from using an FTP server I know that `localhost:port` works. Maybe you're thinking about the syntax for logging in via a URL?

**Comment by Scripter17** [comment]
Windows just keeps getting better and better, doesn't it?
