### ISSUE TITLE
error [-] type object 'CCache' has no attribute 'parseFile'

### ISSUE THREAD

**Issue by Erva-Naz** [SecureAuthCorp/impacket#1328]
I'm running this command in kali linux and getting this error

./GetUserSPNs.py -dc-ip ################## -request

[-] type object 'CCache' has no attribute 'parseFile'

**Comment by rmaksimov** [comment]
Looks like you have an outdated version of impacket. The code has been refactored, for details see #1276

**Comment by martingalloar** [comment]
As @rmaksimov commented, looks you're using an updated version of the script with an outdated installed library.

Closing, please reopen if you still have issues after updating the library!

**Comment by haicenhacks** [comment]
I am having the same issue with a fresh pull of the repo. Which library do I need to update?
