### ISSUE TITLE
Limiting max read/write buff size

### ISSUE THREAD

**Issue by RidaShamasneh** [SecureAuthCorp/impacket#1338]
I wonder why the max read/write buffer size is limited below?
I believe an SMB server should be responsible for this?

```
self._Connection['MaxTransactSize']   = min(0x100000,negResp['MaxTransactSize'])
self._Connection['MaxReadSize']       = min(0x100000,negResp['MaxReadSize'])
self._Connection['MaxWriteSize']      = min(0x100000,negResp['MaxWriteSize'])
```

**Comment by 0xdeaddood** [comment]
Hi @RidaShamasneh! 

I assume you're talking about [these lines](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/smb3.py#L567-L569) in the [MS-SMB2] Protocol Implementation. 

The `MaxReadSize` and `MaxWriteSize` values are set based on the `SMB NEGOTIATE Response` of the server. However, there are some old Windows versions that have a maximum size value restriction. In Windows 7/8 and Windows Server 2008 R2/2012 this value is 1048576 (for more info you can check the [MS Documentation](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/a64e55aa-1152-48e4-8206-edd96444e7f7#:~:text=8388608-,%3C254%3E%20Section%203.3.5.3.1%3A%20If%20the%20underlying%20transport%20is%20NETBIOS%20over%20TCP,8388608,-%3C256%3E%20Section%203.3.5.3.1)). 

So, to keep backward compatibility, we need to check that the value obtained from the server response is not greater than the max size restriction (this validation was added [here](https://github.com/SecureAuthCorp/impacket/issues/46#issuecomment-93414781)).

Closing. Reopen if you have further questions.

Thanks

**Comment by RidaShamasneh** [comment]
@0xdeaddood thanks a lot for you quick response!
