### ISSUE TITLE
impacket smbserver.py closing down connection

### ISSUE THREAD

**Issue by w0lfcat** [SecureAuthCorp/impacket#1340]
First of all, thanks for this cool project. I'm having a small problem when trying to setup smb server on kali linux.
The client is windows 10.

**Kali - 172.16.1.10**

```
$ sudo python3 /usr/share/doc/python3-impacket/examples/smbserver.py share .
Impacket v0.9.24 - Copyright 2021 SecureAuth Corporation

[*] Config file parsed
[*] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
[*] Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
[*] Config file parsed
[*] Config file parsed
[*] Config file parsed
[*] Incoming connection (172.16.1.50,51275)
[*] Closing down connection (172.16.1.50,51275)
[*] Remaining connections []
[*] Incoming connection (172.16.1.50,51277)
[*] Closing down connection (172.16.1.50,51277)
[*] Remaining connections []
```

**Windows 10 - 172.16.1.50**

```
C:\>net view \\172.16.1.10\
System error 53 has occurred.

The network path was not found.


C:\>net view \\172.16.1.10\share
System error 53 has occurred.

The network path was not found.
```

I just want to access Kali from Windows 10. Let me know if you need more info to troubleshoot this issue. Thanks

**Comment by 0xdeaddood** [comment]
Hi @w0lfcat!

It looks you don't have SMBv1 enabled on your Windows machine, try using the SMBv2 flag:

`smbserver.py share . -smb2support`

Please let me know if this solves the problem.

Thanks

**Comment by 0xdeaddood** [comment]
No answer, closing. Please re-open if needed.

**Comment by hildar007** [comment]
Hi @0xdeaddood  I encountered the similar problem. And adding **-smb2support** does not support.
Client: windows server 2019

**Comment by 1oftheguthakrs** [comment]
I have the same issue with -smb2suport enabled. 
When I connect smbserver from another Windows machine it works fine. I also connect successfully from a Linux machine. Unfortunately I don't know why one of my Windows machine didn't work. 
On the machine that got disconnected, It complains about the name of the shared folder is not correct, but I know the name is correct because using the same name works from my other machines(Windows and Linux)

**Comment by 1oftheguthakrs** [comment]
I found the solution. You need to set AllowInsecureGuestAuth reg key to 1.
https://www.youtube.com/watch?v=vyatMj1Z2NQ

**Comment by tajiknomi** [comment]
You should set **AllowInsecureGuestAuth** and unset the  **RequireSecuritySignature** i.e. 

#### Change AllowInsecureGuestAuth to 1
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters" -Name "AllowInsecureGuestAuth" -Value 1 -Type DWord

#### Change RequireSecuritySignature to 0
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "RequireSecuritySignature" -Value 0 -Type DWord

#### Verify the changes
Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters" -Name "AllowInsecureGuestAuth"
Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "RequireSecuritySignature"
