### ISSUE TITLE
cannot import name 'KeyListSecrets' from 'impacket

### ISSUE THREAD

**Issue by DerXanRam** [SecureAuthCorp/impacket#1342]
when i run this command

![vv](https://user-images.githubusercontent.com/101794261/173211233-7e52066c-f556-4d8a-8dd7-e2a92cb51723.png)

it returns error
`ImportError: cannot import name 'KeyListSecrets' from 'impacket.examples.secretsdump' (/usr/lib/python3/dist-packages/impacket/examples/secretsdump.py)`

please help

**Comment by 0xdeaddood** [comment]
Hi @DerXanRam, 

It looks you're using a new version of `secretsdump.py` with an outdated installed library. Please update the Impacket library. 

Closing. Reopen if you need further help.
