### ISSUE TITLE
mssqclient.py not working 6/12/2022

### ISSUE THREAD

**Issue by faust916** [SecureAuthCorp/impacket#1346]
### Configuration  
impacket version:  Impacket v0.10.1.dev1+20220606.123812.ac35841f
Python version:  3.8.6
Target OS:  Hackthebox.com "Archetype" tutorial, Windows
Windows Server 2019 Standard 17763

135/tcp  open  msrpc        Microsoft Windows RPC
139/tcp  open  netbios-ssn  Microsoft Windows netbios-ssn
445/tcp  open  microsoft-ds Windows Server 2019 Standard 17763 microsoft-ds
1433/tcp open  ms-sql-s     Microsoft SQL Server 2017 

Service Info: OSs: Windows, Windows Server 2008 R2 - 2012; CPE: cpe:/o:microsoft:windows

### Debug Output With Command String  

command:
─$ sudo mssqlclient.py -p 1433 ARCHETYPE/sql_svc:'M3g4c0rp123'@{10.129.129.84} -windows-auth  1 ⚙
Impacket v0.10.1.dev1+20220606.123812.ac35841f - Copyright 2022 SecureAuth Corporation

or
command:
─$ sudo mssqlclient.py -p 1433 Administrator@DC01 -windows-auth 

or
command:
─$ sudo python3 mssqlclient.py -p 1433 ARCHETYPE/sql_svc:'M3g4c0rp123'@{10.129.129.84} -windows-auth

or 
command:
─$ sudo python3 mssqlclient.py -p 1433 ARCHETYPE/sql_svc:@{10.129.129.84} -windows-auth
Password: M3g4c0rp123

All get the same response:

Traceback (most recent call last):
  File "/usr/local/bin/mssqlclient.py", line 4, in <module>
    __import__('pkg_resources').run_script('impacket==0.10.1.dev1+20220606.123812.ac35841f', 'mssqlclient.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/impacket-0.10.1.dev1+20220606.123812.ac35841f-py3.8.egg/EGG-INFO/scripts/mssqlclient.py", line 169, in <module>
    ms_sql.connect()
  File "/usr/local/lib/python3.8/dist-packages/impacket-0.10.1.dev1+20220606.123812.ac35841f-py3.8.egg/impacket/tds.py", line 531, in connect
    af, socktype, proto, canonname, sa = socket.getaddrinfo(self.server, self.port, 0, socket.SOCK_STREAM)[0]
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

### Additional context  
All attempts were made from a terminal in the "Impacket" directory, so PATH should not be an issue.

I was following a walkthrough from hackthebox.com called "Archetype":  blob:https://app.hackthebox.com/2fbea503-5943-4f84-94f5-6f1b41adb677

**Comment by 0xdeaddood** [comment]
Hi @faust916!

You have to define the target IP address without {}. Closing...
