### ISSUE TITLE
error with GetUserSPN.py

### ISSUE THREAD

**Issue by jessemaxxa** [SecureAuthCorp/impacket#1352]
### Configuration  
impacket version:  latest 
Python version:  3.10.4
Target OS:  kali

This is the command I am using to get the error i was also running this inside a venv

GetUserSPNs.py -request -dc-ip dc1.scrm.local  scrm.local/ksimpson -k -no-pass -dc-ip 10.10.11.168

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 This is the error
[-] exceptions must derive from BaseException

**Comment by 0xdeaddood** [comment]
Hi @jessemaxxa!

Could you please try to run the command with the -debug option and provide more information?

**Comment by 0xdeaddood** [comment]
Hi @ldcvanderpoel!

This error probably means that NTLM authentication is disabled in that environment. Please check this PR #1363. Using the `-dc-host` parameter to  define the FQDN or NetBIOS name of the KDC should works.

**Comment by 0xdeaddood** [comment]
No answer, closing. Please re-open if needed.
