### ISSUE TITLE
No module named impacket

### ISSUE THREAD

**Issue by OGGary** [SecureAuthCorp/impacket#1366]
└──╼ $sudo python3 smbserver.py 
Traceback (most recent call last):
  File "/impacket/impacket/smbserver.py", line 49, in <module>
    from impacket import smb, nmb, ntlm, uuid
ModuleNotFoundError: No module named 'impacket'

└──╼ $python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import impacket

**Comment by OGGary** [comment]
it works in interactive, but not in script?

**Comment by 0xdeaddood** [comment]
Hi @OGGary!

It seems there is something wrong with your installation. Please check the setup section: https://github.com/SecureAuthCorp/impacket#setup

**Comment by anadrianmanrique** [comment]
@OGGary it looks like the python interpreter it's able to find impacket library in the context of the regular user but not in the context of root. Maybe PYTHONPATH env variable should be adjusted for root as well.
