### ISSUE TITLE
type object 'CCache' has no attribute 'parseFile' - Getst.py

### ISSUE THREAD

**Issue by shadowctrl** [SecureAuthCorp/impacket#1410]
got error type object 'CCache' has no attribute 'parseFile' while executing getst.py 

command used : 

python getst.py support.htb/shadowctrl:123456 -dc-ip 10.10.11.174 -impersonate Administrator -spn www/dc.support.htb

**Comment by rmaksimov** [comment]
Looks like you have an outdated version of impacket. The code has been refactored, for details see #1276. For information on how to fix this, see #1328
