### ISSUE TITLE
crush when uploading files using SMB

### ISSUE THREAD

**Issue by Bella-Jaguar** [SecureAuthCorp/impacket#159]
hi

sometimes, when uploding files using SMB1, the SMB server sends back an empty LockingAndX packet, during the writing.

Empty lockingandx packets should be answered, but thats it. There is really nothing else to do with them, I'm not sure why there are being sent. The thing is, thats now, impacket doesn't expect to get them, and when it happens (usually when uploading really big files) it gets out of synchronization and crushes.

Bella

**Comment by asolino** [comment]
Hey @Bella-Jaguar 

Thanks for the report. I'm trying to reproduce it but I still can't. How big the file must be? What target OS are you trying uploading to?

If you have the error thrown, it's be great to know which one it is.

**Comment by Bella-Jaguar** [comment]
It happened to me when trying to upload a ~200MB~ file to a windows 7. Keep in mind that its not very common. I noticed it it during tests, after a few dozens times it worked.

**Comment by asolino** [comment]
Thanks @Bella-Jaguar 

Do you remember what error was thrown?

**Comment by asolino** [comment]
No answer, closing.
