### ISSUE TITLE
Anonymous connections 

### ISSUE THREAD

**Issue by hegusung** [SecureAuthCorp/impacket#214]
Hi,
In a previous issue I was told to make anonymous connections with impacket using '' for both user and password. However it didn't worked.

During an audit I was able to list users with an anonymous connection with winexe but I got an LOGIN_FAILURE with impacket.
Aparently impacket sends a NegTokenInit structure even with an anonymous login, whereas winexe don't.

**Comment by asolino** [comment]
hey @hegusung thanks for the report.

Do you know what was the target OS tested?
Do you have some pcap samples I can check?  That'd be helpful to identify where the problem might be faster.

thanks

**Comment by hegusung** [comment]
I managed to recreate the desired anonymous connection, I zipped the pcap file : 

[smb_anonymous.zip](https://github.com/CoreSecurity/impacket/files/506313/smb_anonymous.zip)

this connection is made using : 
smbclient -U ""%"" -L <IP>

I discovered this feature seems to be removed from the latest version of smbclient, but it works with the one from pth-toolkit : 
https://github.com/byt3bl33d3r/pth-toolkit

**Comment by asolino** [comment]
Hey @hegusung, any way you can verify it again after applying https://github.com/CoreSecurity/impacket/commit/c1e5842c2105490a5c9f763a700cd4b8e87274ec ? 

I just wanna be sure that change doesn't solve the problem. It might not be related to NegTokenInit issues. Thanks.

**Comment by hegusung** [comment]
No, it didn't solve the problem

**Comment by hegusung** [comment]
Any news on this issue ?

**Comment by martinuy** [comment]
@hegusung , 

Are you suggesting that Windows users can be dumped with an anonymous login?

Can you please provide us with the following information?

- PCAP capture of the users dumping
- Target OS (including version) where users where dumped (using an anonymous login I assume)
- Target OS where Impacket is running
- Target OS where the tool used to anonymously dump the users was running

**Comment by 0xdeaddood** [comment]
No answer, closing.

**Comment by 0xdeaddood** [comment]
No answer, closing.
