### ISSUE TITLE
OpenTable is not filled completely for SMB2 at least.

### ISSUE THREAD

**Issue by contactr2m** [SecureAuthCorp/impacket#242]
https://msdn.microsoft.com/en-us/library/cc246587.aspx

pprint(c._connection._Session['OpenTable'])
{'/\x1a\x00\x00\x00\x00\x00\x00/\x1a\x00\x00\x00\x00\x00\x00': {'Connection': 0,
                                                                'CreateDisposition': '',
                                                                'CreateGuid': '',
                                                                'CreateOption': '',
                                                                'DesiredAccess': '',
                                                                'Durable': False,
                                                                'FileAttributes': '',
                                                                'FileID': <impacket.smb3structs.SMB2_FILEID instance at 0x106397cf8>,
                                                                'FileName': '\\\\loan4-gns\\test3',
                                                                'IsPersistent': False,
                                                                'LastDisconnectTime': 0,
                                                                'OperationBuckets': [],
                                                                'Oplocklevel': SMB2_OPLOCK_LEVEL_NONE,
                                                                'ResilientHandle': False,
                                                                'ResilientTimeout': 0,
                                                                'ShareMode': 0,
                                                                'TreeConnect': 57096},

Below entries are not updated.

Open.Connection: A reference to the SMB2 transport connection on which this open was established.

Open.OperationBuckets: An array of 64 entries used to maintain information about outstanding lock and unlock operations performed on resilient Opens. Each entry MUST be assigned an index from the range of 1 to 64. Each entry is a structure with the following fields:

1.  SequenceNumber: A 4-bit integer modulo 16.
2. Free: A Boolean value of FALSE indicates that there is an outstanding lock or unlock request using this index value and SequenceNumber combination.

I saw this: 
smb3.py 71:    'Connection'         : 0, # Not Used 
Not sure whats the reason.

**Comment by asolino** [comment]
Please specify the use case for this functionality and re open if necessary. Indeed, we're not following the standard in its purist way :)
