### ISSUE TITLE
ConstraintsIntersection error when trying to use wmiexec.py with -k -no-pass?

### ISSUE THREAD

**Issue by msftsecurityteam** [SecureAuthCorp/impacket#266]
Hi all, after generating a golden ticket, I go to try and use the wmiexec.py example with the -k and -no-pass options, but I am getting a strange exception:

ConstraintsIntersection(ConstraintsIntersection(), ConstraintsUnion(SingleValueConstraint(11), SingleValueConstraint(13))) failed at: ValueConstraintError('ConstraintsUnion(SingleValueConstraint(11), SingleValueConstraint(13)) failed at: ValueConstraintError(\'all of (SingleValueConstraint(11), SingleValueConstraint(13)) failed for "15"\',)',) at Integer

Did I generate my ticket incorrectly or something?

**Comment by asolino** [comment]
Hey @msftsecurityteam 

Thanks for the report. A few questions:
1. How did you generate the golden ticket? Using `ticketer.py`?
2. What version of `pyasn1` are you using? There's some reported incompatibilities with the last version. You can easily check it by running 
```
jack:examples user$ python
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyasn1
>>> pyasn1.__version__
'0.2.2'
>>> 
```

**Comment by msftsecurityteam** [comment]
Hi asolino,

1. Yes, ticketer.py
2. pyasn1 version 0.2.3

**Comment by asolino** [comment]
Hey:
1. Please send me the command line you are using.
2. Thanks. I just checked it under my configuration and `pyasn1-0.2.3` seems to be working for this use case
3. Are you setting the `KRB5CCNAME` variable pointing to the saved golden ticket?
4. Please run `wmiexec.py` with `-debug` option and paste it here.

**Comment by msftsecurityteam** [comment]
1. ./examples/wmiexec.py -debug -k -no-pass CORP/TICKET_USER@HOST
3. Yes, I am setting the environment variable.
4. 
[+] Using Kerberos Cache: TICKET_USER.ccache
[+] SPN CIFS/HOST@CORP not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/CORP@CORP
[-] ConstraintsIntersection(ConstraintsIntersection(), ConstraintsUnion(SingleValueConstraint(11), SingleValueConstraint(13))) failed at: ValueConstraintError('ConstraintsUnion(SingleValueConstraint(11), SingleValueConstraint(13)) failed at: ValueConstraintError(\'all of (SingleValueConstraint(11), SingleValueConstraint(13)) failed for "15"\',)',) at Integer

**Comment by msftsecurityteam** [comment]
Just to clarify what I wrote above: CORP is the domain, TICKET_USER is the DA account I generated the ticket for, and HOST is just a host on the domain

**Comment by asolino** [comment]
Thanks. Just to confirm, what Impacket version are you using?

On Apr 21, 2017 15:02, "msftsecurityteam" <notifications@github.com> wrote:

Just to clarify what I wrote above: CORP is the domain, TICKET_USER is the
DA account I generated the ticket for, and HOST is just a host on the domain

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/CoreSecurity/impacket/issues/266#issuecomment-296261781>,
or mute the thread

**Comment by msftsecurityteam** [comment]
I am using the very latest git commit

**Comment by asolino** [comment]
Thanks. 

Ok.. a few more tests:
1. Let's rule out normal Kerberos auth. Can you wmiexec.py to the target w/o using the golden ticket, and using `-k` switch? (Don't forget to flush the ticket's cache, otherwise the library will use it).
2. Uncomment [these two](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiexec.py#L96) lines and these [other two](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiexec.py#L401) lines and run the script again this way:
```
./examples/wmiexec.py -debug -k HOST
```
Paste the output please.
I'm assuming wireshark capture is not allowed right?

Thanks for your help.

**Comment by msftsecurityteam** [comment]
Wireshark I wouldn't be able to do unfortunately... but I have an update: I feel kind of stupid? But I went to run klist and I didn't have any Kerberos stuff installed on my machine.  I installed some packages and now instead of having this same error, I am getting "SessionError: KRB_AP_ERR_BAD_INTEGRITY(Integrity check on decrypted field failed)"

**Comment by msftsecurityteam** [comment]
Would you still like the full output? My original error seems to have been fixed...

**Comment by asolino** [comment]
Ok. Don't feel stupid shit happens ;)

Let's be sure you're following all these steps:

1. `ticketer.py`: Don't forget, when specifying the domain name, *always* use FQDN (e.g. CORP.NET). Let's say you run `ticketer.py` this way:
```
./ticketer.py -nthash bf11f776b7cc1a2ba9acd8ccc918a805 -domain freefly.net -domain-sid S-1-5-21-3954862456-2137106910-2876453497 baduser
```
This will generate a file called `baduser.ccache`
2. Set the `KRB5CCNAME` variable pointing to the golden ticket:
```
export KRB5CCNAME=./baduser.ccache
```
If you run `klist -v ` you should have something like this
```
Credentials cache: FILE:./baduser.ccache
        Principal: baduser@FREEFLY.NET
    Cache version: 4
  KDC time offset: -1 second

Server: krbtgt/FREEFLY.NET@FREEFLY.NET
Client: baduser@FREEFLY.NET
Ticket etype: arcfour-hmac-md5, kvno 2
Ticket length: 923
Auth time:  Apr 21 17:31:57 2017
End time:   Apr 19 17:31:57 2027
Renew till: Apr 19 17:31:57 2027
Ticket flags: pre-authent, initial, renewable, proxiable, forwardable
Addresses: addressless
```
3. Run `wmiexec.py` against the target:
```
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[+] Using Kerberos Cache: ./baduser.ccache
[+] Domain retrieved from CCache: FREEFLY.NET
[+] SPN CIFS/FREEFLY-DC@FREEFLY.NET not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/FREEFLY.NET@FREEFLY.NET
[+] Using TGT from cache
[+] Username retrieved from CCache: baduser
[+] Trying to connect to KDC at FREEFLY.NET
[*] SMBv2.1 dialect used
[+] Domain retrieved from CCache: FREEFLY.NET
[+] Using Kerberos Cache: ./baduser.ccache
[+] SPN HOST/FREEFLY-DC@FREEFLY.NET not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/FREEFLY.NET@FREEFLY.NET
[+] Using TGT from cache
[+] Username retrieved from CCache: baduser
[+] Trying to connect to KDC at FREEFLY.NET
[+] Target system is freefly-dc and isFDQN is True
[+] StringBinding: \\\\FREEFLY-DC[\\PIPE\\atsvc]
[+] StringBinding: FREEFLY-DC[49154]
[+] StringBinding chosen: ncacn_ip_tcp:FREEFLY-DC[49154]
[+] Domain retrieved from CCache: FREEFLY.NET
[+] Using Kerberos Cache: ./baduser.ccache
[+] SPN HOST/FREEFLY-DC@FREEFLY.NET not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/FREEFLY.NET@FREEFLY.NET
[+] Using TGT from cache
[+] Username retrieved from CCache: baduser
[+] Trying to connect to KDC at FREEFLY.NET
[+] Domain retrieved from CCache: FREEFLY.NET
[+] Using Kerberos Cache: ./baduser.ccache
[+] SPN HOST/FREEFLY-DC@FREEFLY.NET not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/FREEFLY.NET@FREEFLY.NET
[+] Using TGT from cache
[+] Username retrieved from CCache: baduser
[+] Trying to connect to KDC at FREEFLY.NET
[+] Domain retrieved from CCache: FREEFLY.NET
[+] Using Kerberos Cache: ./baduser.ccache
[+] SPN HOST/FREEFLY-DC@FREEFLY.NET not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/FREEFLY.NET@FREEFLY.NET
[+] Using TGT from cache
[+] Username retrieved from CCache: baduser
[+] Trying to connect to KDC at FREEFLY.NET
[!] Launching semi-interactive shell - Careful what you execute
[!] Press help for extra shell commands
C:\>whoami
freefly.net\baduser

C:\>
```

Is there anything different you did?
What is the target OS version? (I'm testing against a Windows 2008 R2).

**Comment by asolino** [comment]
> Would you still like the full output? My original error seems to have been fixed...

If you're getting `KRB_AP_ERR_BAD_INTEGRITY` I don't know what exactly might be wrong. Did you follow all the steps I wrote before? Did you use `aesKey` or `ntHash` for `ticketer.py`, what is the target OS Server Version you're trying to connect to?

**Comment by msftsecurityteam** [comment]
Pretty much did everything exact what you did above, except change baduser to a real DA account. I am getting this integrity check trying to wmiexec to a 2008 SP1 box.  I used nthash, not AES. Maybe my krbtgt nthash is wrong?

**Comment by asolino** [comment]
Use `secretsdump.py` to check your krbtgt hash. Try using `-aesKey` instead also.

When testing the ticket, try a simpler script (`wmiexec.py` is pretty complex). `smbclient.py` is  a good option:
```
./smbclient.py -k -debug HOST
``` 
if it works then:
```
use c$
ls
```

**Comment by romanblachman** [comment]
Actually, I'm experiencing the same problem as mentioned in the beginning of the thread. The ccache ticket was created legitimately by using kinit with a keytab file. The keytab file has all the possibly supported encryption types:aes256-cts-hmac-sha1-96, aes128-cts-hmac-sha1-96, des-cbc-md5, arcfour-hmac, des3-cbc-sha1).
When looking at the ccache file using klist, I get the following:

`Ticket cache: FILE:/tmp/krb5cc_0
Default principal: user@DOMAIN.COM

Valid starting       Expires              Service principal
04/23/2017 22:29:12  04/24/2017 08:29:12  krbtgt/DOMAIN.COM@DOMAIN.COM
	renew until 04/24/2017 22:29:11, Etype (skey, tkt): aes256-cts-hmac-sha1-96, aes256-cts-hmac-sha1-96`

When trying to run wmiquery.py using this ccache file, I'm getting the following error:
`KRB5CCNAME=/tmp/krb5cc_0 python /usr/local/bin/wmiquery.py -no-pass -k dc01.domain.com -debug
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

[+] Using Kerberos Cache: /tmp/krb5cc_0
[-] ConstraintsIntersection(ConstraintsIntersection(), ConstraintsUnion(SingleValueConstraint(10), SingleValueConstraint(12))) failed at: ValueConstraintError('ConstraintsUnion(SingleValueConstraint(10), SingleValueConstraint(12)) failed at: ValueConstraintError(\'all of (SingleValueConstraint(10), SingleValueConstraint(12)) failed for "15"\',)',) at Integer`

I'm uploading pcap file of the scenario, while it looks like no communication is really happening, just socket establishment, and nothing else is being exchanged via the protocol.
[wmiquery_capture.pcap.zip](https://github.com/CoreSecurity/impacket/files/950096/wmiquery_capture.pcap.zip)

**Comment by asolino** [comment]
There must be something going on when readin a ccache file generated by
kinit. Any chance of getting that ccache file?

Running wmiexec with the traceback lines uncommented would be great too

Thanks Roman

**Comment by romanblachman** [comment]
Yes, I've assumed that this is caused by the ccache input file, but I cannot figure out what is different with it.

I've tried uncommenting the traceback lines in the wmiquery.py file, but didn't get any new prints other than I've pasted.

See the attached ccache file (not original, masked names).

[ccache.zip](https://github.com/CoreSecurity/impacket/files/950105/ccache.zip)

**Comment by asolino** [comment]
Thanks for the files!

Regarding wmiexec there are two sets of tracebacks to uncomment.. just in
case.

**Comment by romanblachman** [comment]
I'm using wmiquery.py and not wmiexec.py. I've tried uncommenting both sections in wmiquery.py, but it still didn't show me any additional prints other the ones I've shared on this thread.

Happy to help to make impacket better! Let me know if you want me try something out or add additional prints anywhere.

Thank you,
Roman.

**Comment by msftsecurityteam** [comment]
Hey @asolino, just wanted to give a quick update-

So my golden ticket works now, for some reason your secretsdump.py gave me a different (and correct) krbtgt hash, versus using other tools out there ;-).  As far as the original problem with ConstraintsIntersection issues, I am not 100% sure what I did to fix it, other than I was using DOMAIN versus DOMAIN.COMPANY.COM.  I was having DNS errors when trying to talk to the DC when I was doing this.... once I changed this up it worked, but that could have just been a coincidence. Cheers

**Comment by asolino** [comment]
Hey @msftsecurityteam 

Great to know the problem was on the krbtgt hash. 
I'm gonna leave this issue open until we figure out the ConstraintsIntersection problem.

thanks again!

**Comment by romanblachman** [comment]
@asolino do you need anything from me for the constraints issue? This reproduces for me easily, so I think that something in the generated ticket (by krb5 standard kinit) isn't supported by the ccache parser.

**Comment by asolino** [comment]
Hey @romanblachman 

Yes.. I will need your help. I grabbed your ccache and I cannot reproduce it down here. I'm using macOS for most of my testing so maybe this is related to Linux. What OS are you running it under?
Looks like indeed the problem is in the ccache parsing, so we should try to understand where it is generating an exception. 

Could you please try running [this](https://github.com/CoreSecurity/impacket/blob/master/impacket/krb5/ccache.py) file?
it's the ccache parser implementation and it does have a __main__ section that loads the ccache file pointed by KRB5CCNAME. Can you set that variable and Python run that file to see if it outputs your cache ticket correctly?

thanks!

**Comment by romanblachman** [comment]
Hello @asolino, I'm running Ubuntu 14.04.

This is the output of the ccache.py parser, I've masked the username and domain names, to match the ccache file I've sent you.

```
admin@admin:~$ sudo python /usr/local/lib/python2.7/dist-packages/impacket/krb5/ccache.py
Primary Principal: domainuser1@DOMAIN1234.COM
Credentials:
[0]
	Client: domainuser1@DOMAIN1234.COM
	Server: krbtgt/DOMAIN1234.COM@DOMAIN1234.COM
	Key: (0x17)db92ef334f0e94a529c57390526029d1
	Times:
		Auth : 2017-04-24T16:09:22
		Start: 2017-04-24T16:09:22
		End  : 2017-04-25T02:09:22
		Renew: 2017-04-25T16:09:21
	SubKey: 0
	Flags: 0x50e00000
	Addresses: 0
	Auth Data: 0
	Ticket: 618204203082041ca003020105a1101b0e4e4f524752554d4643552e4f5247a2233021a003020102a11a30181b066b72627467741b0e4e4f524752554d4643552e4f5247a38203dc308203d8a003020112a103020103a28203ca048203c60be5ccbba7e267e4f787f447c43d3f74a3d5b907b748825791b25a6b53ba8812c09c1abded391bf90b1132dfcc213c50222cff248ad084bb343b18159fb4a94e412a60ce40b3688f091a73fff34039cb4a94715e9026e79918e828e665877f0f3b87ee55834fda281e3a597d4e29df5fefd30c64996cc1fa3f1dfe7b03e110f12b8a60054d945c033bc74307f2881605d8b80610e38e26b7ef8738c86a6656b4bea5dd7ab9693e1c91c62d28df3481bec17bec4ab4d475f2a7dc7dad6a0636a917dd2a5ff97fa5365f417e73107221aaa82dcc41cd71f43fe282a59ec07a59a4562ed003bd0d940822ff2785937fd6d3bf90d0f5f51b6ff49a79cdf4fdd5a728ef982f3c7b1eabe1965a9b7c0ca5966f08d7f32bd6b8935178b0f97c2914b432fa39ba389fea03466b85f9fa36b39c13ead8487e2883b0997656f1c6e92eff7880cf49b5ad09b36c0143270d58fbe4d47528b797d89e1e99056b0ee6e27a2f5f16e6a24ce82afa1c4dd34a58ad49b88ea9fad02f076ff8f5d49ea0ac99ab54c9516ff760830c9b2d977b4561f2f28d0bb341c47db493107160f6839f4bc63a0bf28263f74699a55860719184b54db3b0c7b1c5eeff175e7508060605664df04e1868af848f479cf5b90ed95b7bd9b337ca8d517139ed4e76eb11aba0612610c79346bb984e8b6299778f2d8cce9e69bd279f4feec032f0abb8201abbe92e6a1723d1b3c46b35fe14028fcdeba3aea50f19af359d6c95b6b0a65d05af10f05d808673d250f46eb951aa35b46379e04b1268c5d37d9e92f896237efd999cad590e4cb03c5a2af924fee88f61d4a5c7011b46c295427d92cb0e03edfa1e9af7fec0116c8aaded74a51d87e06889b666f9866d7831324d1a093dd966b0b5895a080fcabfc7410fc7e8006d7f63211fc456cf2323df85ae3b1845cee9088c4364158c1f739ce5a20191e202b25226d89fbbea5de0e7998c1a41d7d81eb8640bcdd50a37fa115f5ce74c9b6d06f7e2ad75be73f079fbd7e5f5561ca7f2189e9baae6b70d393b7862373ae02d49c346a8df73c98e8983a48dce9341f09b531e4c05e1f866f4280f0301858e8672f901e6b981f5d2c89367be8699929e74889eb42e08baba2fbebc062b1136aef039f8390fe80e315bc243ac6735a0843c33abffadf4e76ec7484b2b5461da5c600114f7b0e50d3a18639665b252fea52851147c63a63524dc30128b60ecdc1acc65c2b44cb4b7b8d127f980e38b1adf593af8797bfe543ef20602f37f856b1ce3c5bf8f40e5b9eba09612df5f8a77102b5c3925c328e4d0da572004bf43ef8b7f83d4432f1f27daab8c2067ddeaef060dc55ffca1cdad934968f18f45
	Second Ticket:
[1]
	Client: domainuser1@DOMAIN1234.COM
	Server: krb5_ccache_conf_data/pa_type/krbtgt/DOMAIN1234.COM@DOMAIN1234.COM@X-CACHECONF:
	Key: (0x0)
	Times:
		Auth : 1970-01-01T00:00:00
		Start: 1970-01-01T00:00:00
		End  : 1970-01-01T00:00:00
		Renew: 1970-01-01T00:00:00
	SubKey: 0
	Flags: 0x0
	Addresses: 0
	Auth Data: 0
	Ticket: 32
	Second Ticket:
```

Thanks,
Roman

**Comment by asolino** [comment]
Thanks for the data @romanblachman.

I see a weird ticket there but can't conclude that's the problem. Let's try to go to a simpler script and see if problem is still there. If you execute `smbclient.py -k -debug TARGETHOST` are you getting the same problem? If so, please uncomment the tracebacks in that file to see if we're lucky this time.

thanks!

**Comment by romanblachman** [comment]
Hey @asolino,
I didn't change anything, and suddenly it works as normal, using both smbclient.py and wmiquery.py scripts.
Do you have any explanation to this?

**Comment by asolino** [comment]
@romanblachman I don't have an explanation at all except there's something inside the ticket that is triggering this issue (assuming you did use a different ticket cache in your last test).

**Comment by romanblachman** [comment]
@asolino yes, I re-did kinit to make sure that the ticket is valid, and now everything is working.

**Comment by asolino** [comment]
> @asolino yes, I re-did kinit to make sure that the ticket is valid, and now everything is working.

Good.. Can you unzip the ccache.zip file you attached, set  `KRB5CCNAME` to that file and see if you can trigger it again? Looks like this happens before contacting the target server so it might work.

**Comment by romanblachman** [comment]
I just checked. Downloaded the ccache from this thread, and tried to use it for wmiquery.py, and it doesn't show the error anymore, but rather says KRB_AP_ERR_TKT_EXPIRED(Ticket expired).

Two options:
1) The ccache file I've uploaded doesn't match the one that was causing the problems???
2) It is not related to the ccache file???

**Comment by asolino** [comment]
There's only one way to verify that :).. If you control the target Domain Controller (crossing fingers it's a test DC) you can rewind the clock and do the same with your client machine.
If testing again doesn't trigger the issue then the ccache has nothing to do with this.. it's something else.

**Comment by romanblachman** [comment]
Unfortunately, it is not a test DC, so I will provide details when I have them, if this ever happens ago. Sounds like a plan?

**Comment by asolino** [comment]
No problem @romanblachman I understand.

Thanks a lot for your help!.. Yes.. I'll leave this issue open until we figure things out. If it happens to you again please send the ccache file and (if possible) a pcap.

thanks again!

**Comment by dirkjanm** [comment]
FWIW, the error from the first post was the exact one I got previously, which promoted the fix in 9bb51a3
Maybe they were not having the very latest commit when running into this?

**Comment by asolino** [comment]
I thought about that too @dirkjanm that's why I asked the version being used. Guess we will need to pay attention if this happens again. I'll leave this open until we have more information.

thanks for checking.

**Comment by asolino** [comment]
Closing now. Reopen if somebody experiences this issue again
