### ISSUE TITLE
Authentication type not recognized 

### ISSUE THREAD

**Issue by kxjhcs** [SecureAuthCorp/impacket#268]
when i use smbexec.py connect a win10 os,return "Authentication type not recognized ",why? tks

**Comment by asolino** [comment]
hey @kxjhcs 

Please provide the command line you are specifying to `smbexec.py`. A pcap capture would be highly needed as well.

thanks

**Comment by kxjhcs** [comment]
@asolino 
the cmd is：smbexec.py administrator:123456@192.168.101.147

[smbexec_test_192.168.101.147.zip](https://github.com/CoreSecurity/impacket/files/986467/smbexec_test_192.168.101.147.zip)

thanks

**Comment by asolino** [comment]
thanks for the pcap.. I've never seen that error. The interest part is the OpenSCMManager works and returns a valid handle (that is latter used when creating the service).
Did you test other impacket examples? psexec.py? wmiexec.py? What is the target OS? Anything special configuration wise?

thanks

**Comment by asolino** [comment]
No answer, closing
