### ISSUE TITLE
Windows installation errors

### ISSUE THREAD

**Issue by basketas** [SecureAuthCorp/impacket#279]
OK, just wanna add some hints here for those who had trouble installing latest impacket libraries on win10 with python 2.7x

You must install pycrypto with easy_install, and not pip.. It won't work otherwise!
easy_install pycrypto

You must also install VCForPython27.msi before running the upper command:
https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by asolino** [comment]
Thanks for the data @basketas . Now that we switched to pycryptodomex things should be easier.
