### ISSUE TITLE
smbrelayx.py failed to authanticate target

### ISSUE THREAD

**Issue by talb21** [SecureAuthCorp/impacket#299]
python smbrelayx.py -h <target> -e ./<VeilPayload>.exe

getting the folowing erroe while browsing via SMB to the target:

[-] Authenticating against <target> as <hostname>\<username> FAILED

can someone advise?

thanks!

**Comment by WayZzz** [comment]
I encountered the same problem...

**Comment by talb21** [comment]
it happens now with the newest impakcet version

**Comment by asolino** [comment]
The fact `ntlmrelayx` is trying to relay credentials doesn't mean it should always succeed. There are many factors involved in the relaying process that could fail, that have nothing to do with a bug in the script. You are not providing any context that could help us understand what could possibly go wrong, so we can try to replicate the problem. 

Closing.

**Comment by talb21** [comment]
Hi, actually im using smbrelayx.py.
I would love to help on reproducing, can you please let me know what's needed?

**Comment by asolino** [comment]
Things that help reproduce an issue like this:

1. Impacket version used.
2. Command line execution used.
3. Client and Server OS versions.
4. How are you triggering the victim's connection?
5. Is this a lab environment? Is the user you're trying to relay valid at the target machine?
6. Also, try `ntlmrelayx.py`, there are differences in the implementation.

That is just to start.

**Comment by ilyesmsk** [comment]
I have the same issue it says authentificating help i don't know why
