### ISSUE TITLE
WMI, a large number of logon events

### ISSUE THREAD

**Issue by brickbtv** [SecureAuthCorp/impacket#312]
At the moment, i'm trying to get EventLog messages via impacket wmiquery.py script. 
Every query produce on remote machine ~6 Events (in "System"-journal) about Logon and Special Logon. 

So, for me it's like a snowball: retrieving events produce events. 

Is there any way to hold connection for querying, or, probably, reduce their number?

**Comment by asolino** [comment]
Hey @brickbtv 

Hmm.. if you stay inside `wmiquery.py` the original DCOM connection will stay connected. Have you tried executing more than one query that way? (not through the command line)

**Comment by brickbtv** [comment]
Sorry for a long answer, @asolino 

Yes, i have tried to execute many queries with one DCOM connection, but it still generates 6 event per query. 
I found an ToDo comment here: https://github.com/CoreSecurity/impacket/blob/8729e1a6d8d96d4bb48313e6107ce51b0e1aaf02/impacket/dcerpc/v5/dcomrt.py#L21-L23
So, it's probably just the way that queries are implemented, and it's not a bug.

I will try to work around dcomrt request function.

**Comment by asolino** [comment]
Hey @brickbtv 

That comment is marked as done.. It might be worth checking it again tho.. 

You should definitely try doing the same queries from a Windows machine (using Powershell) and check the events that are generated. That would be the ultimate answer.

**Comment by brickbtv** [comment]
Hey @asolino 

I made a small patch via reflection, like:
```python
INTERFACE.request = patchedRequest

def patchedRequest(self, req, iid=None, uuid=None):
    # ... request function code ...
    # a small patch:
    if not hasattr(self, 'connected'):
        self.connect(iid)
        self.connected = True
    # ... other request function code ...
```

And it works well with many-many queries, without reconnection. 😏 

But there are "pingServer" with 120 seconds delay, and he's reconnecting every 2 minutes (2 logon messages in 'System' journal). 
Right now i'm trying to determine the place i can change code the same way.

I took another Windows PC and it has the same behavior, so, probably, it's not a WMI configuration problem. 
Powershell implementation (WinRM) is good alternative, but it returns an Object-like events without "Message" field and have some problems with locale and few other details.
