### ISSUE TITLE
psexec.py: additional options to support batch mode

### ISSUE THREAD

**Issue by vstefanoxx** [SecureAuthCorp/impacket#327]
Hi,

it could be useful to allow batch mode use of psexec.py.
I suggest to add options like:
-stdout `<file>`
-stderr `<file>`
to write standard output and standard error of remote commands to files.

It could be also useful to support piping adding a "-silent" option to suppress all log messages and output only the remote messages.

In attachment is the diff file against psexec.py in Impacket v0.9.15 to implement the suggested features.
[psexec.py.zip](https://github.com/CoreSecurity/impacket/files/1322424/psexec.py.zip)

**Comment by vstefanoxx** [comment]
Another problem of parsing the output of remote commands is that most of the times it is prefixed by a backslash: I couldn't find where it comes from, I only see that the output of remote command start from the last column of previous line.

I solved the problem removing the backslash frmo the output:
psexec.py ... | perl -pe 's/\010//g'

Someone have an idea of where that backslash come from?

**Comment by asolino** [comment]
Hey @vstefanoxx 

Thanks for your patch... Any change to submit this as a PR?

With regards to output redirection, did you try just the regular shell redirection? It should work as well:
```
./psexec.py Administrator@freefly-dc "cmd.exe /c dir x:\\" > /tmp/stdout 2> /tmp/stderr
```

**Comment by vstefanoxx** [comment]
The command you suggested still give me in /tmp/stdout the log messages of psexec.py, the ones starting with [*]:
<pre>
[*] Trying protocol 445/SMB...
[*] Requesting shares on 192.168.123.4.....
...
</pre>

Sure i can grep them out, but not in a "safe" way (maybe remote command return lines starting with [*] too, and also are blank lines between log messages, etc.).

I'm not an expert of github, when I have it ready I'll submit a PR :)

**Comment by asolino** [comment]
That is correct @vstefanoxx.. but if the output redirection works, we might just need to add the `-silent` command line parameter (or `-debugLevel`). I just want to add only the necessary command line parameters.

**Comment by asolino** [comment]
No PR received + If there's more demand for such feature this can be reconsidered.
