### ISSUE TITLE
psexec.py: [-] Error performing the uninstallation, cleaning up

### ISSUE THREAD

**Issue by vstefanoxx** [SecureAuthCorp/impacket#328]
Hi,

using psexec.py I get most of the times the error message:
`[-] Error performing the uninstallation, cleaning up`

and it leaves around the temporary exe file in remote host.
I used it with only one remote host, and only very few times uninstallation was completed positively.

If inside the function "uninstall" of file:
/usr/lib/python2.7/dist-packages/impacket
I add a pause of 2 seconds between the removal of service and the removal of file, all goes well.
1 seconds it's not enough, still having problems.

The windows host is not a slow PC, it's quite fast.

Is it possible to solve the problem in more elegant way?

**Comment by asolino** [comment]
Hey @vstefanoxx 

Interesting behavior. Never faced it before.. Any details about the target machine? (OS? distance hops?)
There should definitely be a better way than adding a delay.. can you wireshark the traffic and check what's going on at the end of the connection when trying to remove the file? Maybe we can catch that error and keep trying a few more times before giving up.

**Comment by asolino** [comment]
And.. just in case.. have you tried `wmiexec.py`? It doesn't upload any file. Might be a better solution for you.

**Comment by tlathm** [comment]
Also make sure that the service exe file isn't getting quarantined by some virus scan on the host. That was happening to me until I added an exclusion in the virus scan for it, and caused all sorts of odd failures.

**Comment by vstefanoxx** [comment]
Thank you for your answer.

Target machine is a Windows 7 Professional PC, while source machine is a Virtualbox VM with Debian running in the same PC: VM is in bridged mode, never had problems related with networking.
There is no antivirus, exe file get correctly executed, only the cleaning up step goes wrong.

Here is the part of wireshark log related with a successful deletion of file (with 2 seconds break betweem removal of service and deletion of file):
<pre>
3452	3.867007000	192.168.123.101	192.168.123.4	SMB2	186	Tree Connect Request Tree: \\192.168.123.4\ADMIN$
3453	3.867165000	192.168.123.101	192.168.123.4	TCP	66	38512→445 [ACK] Seq=69301 Ack=7548 Win=62464 Len=0 TSval=35736584 TSecr=45940587
3454	3.868171000	192.168.123.101	192.168.123.4	SMB2	214	Create Request File: qhKnpyZW.exe
3455	3.868822000	192.168.123.101	192.168.123.4	SMB2	183	Read Request Len:1024 Off:0
3456	3.868895000	192.168.123.101	192.168.123.4	SMB2	183	Read Request Len:1024 Off:0
3457	3.870008000	192.168.123.101	192.168.123.4	SMB2	158	Close Request
3458	3.870953000	192.168.123.101	192.168.123.4	SMB2	183	Read Request Len:1024 Off:0
3459	3.871744000	192.168.123.101	192.168.123.4	SMB2	183	Read Request Len:1024 Off:0
3460	3.872508000	192.168.123.101	192.168.123.4	SMB2	138	Tree Disconnect Request
3461	3.873340000	192.168.123.101	192.168.123.4	SMB2	183	Read Request Len:1024 Off:0
</pre>

Here is wireshark log for psexec.py without break and generating error:
<pre>
30662	129.197017000	192.168.123.101	192.168.123.4	SMB2	186	Tree Connect Request Tree: \\192.168.123.4\ADMIN$
30663	129.197868000	192.168.123.101	192.168.123.4	SMB2	214	Create Request File: SFOocYku.exe
30664	129.198497000	192.168.123.101	192.168.123.4	SMB2	183	Read Request Len:1024 Off:0
30665	129.199165000	192.168.123.101	192.168.123.4	SMB2	183	Read Request Len:1024 Off:0
30666	129.199751000	192.168.123.101	192.168.123.4	SMB2	183	Read Request Len:1024 Off:0
30667	129.200322000	192.168.123.101	192.168.123.4	SMB2	183	Read Request Len:1024 Off:0
30668	129.200694000	192.168.123.101	192.168.123.4	TCP	66	38578→445 [ACK] Seq=70410 Ack=8522 Win=62464 Len=0 TSval=35839524 TSecr=45981763
30669	129.201126000	192.168.123.101	192.168.123.4	SMB2	138	Tree Disconnect Request
30670	129.201700000	192.168.123.101	192.168.123.4	SMB2	183	Read Request Len:1024 Off:0
30671	129.202270000	192.168.123.101	192.168.123.4	SMB2	183	Read Request Len:1024 Off:0
30672	129.203151000	192.168.123.101	192.168.123.4	SMB2	226	Write Request Len:44 Off:0
</pre>

"Create Request File: <nomefile>.exe" has option "delete on close", and the difference I can see is that in the first log appear a "Close Request", in the second log it's missing: that's why probably the file doesn't get deleted
Another difference is that in the 2nd log appear a "Write Request" that is missing in the first log.

That was my first attempt in using psexec.py, maybe it's just an unlucky combination; I tried to use it in different networks and hosts and all went well.

**Comment by asolino** [comment]
Did it keep happening on other machines @vstefanoxx ?

**Comment by asolino** [comment]
No answer, closing
