### ISSUE TITLE
Is it possible to check for whether impacket can get us file meta-data like size/creator/ ACLs etc?

### ISSUE THREAD

**Issue by munirajtomar** [SecureAuthCorp/impacket#386]
Hi Team,
I would like to know if Impacket would help usto fetch File ACL's (like file permissions) and other file metadata like size of the file , created by whom , etc??
Any help would be appreaciated. Thanks in advance

**Comment by asolino** [comment]
Hey @munirajtomar 

Yes, it can be used for that, but you would need to code the specific script if none of the examples solve your request.
