### ISSUE TITLE
wmiquery reports rpc_s_access_denied 

### ISSUE THREAD

**Issue by hackdefendr** [SecureAuthCorp/impacket#390]
Even with -debug enabled on the command line, I only see this:

> rpc_s_access_denied

How do I troubleshoot this?

I know my wmi query works, because I used the same query with wmic.

**Comment by asolino** [comment]
I don't have enough info to understand the problem. If you can send us two PCAP files with the traffic of `wmiquery` and `wmic` that would help identifying what's going on.

**Comment by asolino** [comment]
No answer, closing.
