### ISSUE TITLE
poor performance of wmi query

### ISSUE THREAD

**Issue by sckoehler** [SecureAuthCorp/impacket#410]
I have been attempting to fetch logon events using wmiquery.py.  I noticed that performance is rather poor. In fetching 4000 records, impacket makes 300 million function calls, of which 80 million are calls to calculatePad.  Here's the top of some profile output:

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
6197/1258   46.679    0.008   97.053    0.077 ndr.py:808(unpack)
 28091772   24.258    0.000   35.347    0.000 ndr.py:195(calculatePad)
3216929/1918811   18.756    0.000   35.233    0.000 structure.py:429(calcUnpackSize)
  9004231   17.507    0.000   18.561    0.000 structure.py:525(findAddressFieldFor)
 65118839   17.296    0.000   17.296    0.000 {method 'split' of 'str' objects}
865206/676054   12.321    0.000  109.918    0.000 structure.py:135(fromString)
3229265/1326683   10.661    0.000   59.080    0.000 structure.py:268(unpack)
3229361/1918907    9.328    0.000   31.973    0.000 structure.py:358(calcPackSize)
3032468/1027762    9.148    0.000   20.432    0.000 structure.py:176(pack)
80434224/71818556    8.800    0.000   28.444    0.000 {len}

I dug into this a little, and found that after an unpack of type PMInterfacePointer, there is an unpack of type "c" with an array size of about 6800.  This causes the loop in unpack to call calculatePad 6800 times. This seems wasteful.  Isn't there a way to unpack an array of 6800 characters in one step, without having to do this loop?

**Comment by asolino** [comment]
Hey @sckoehler 

Can you point out to the code you're referring? Have you tried to change the code and see what happens?

**Comment by sckoehler** [comment]
Alberto,

I have been adding print statements to try to understand the problem, but I
have not yet tried coding a solution. The loop in question is in the unpack
function near ndr.py:808.  Here's the loop:

            while numItems and soFarItems < len(data):
                pad = self.calculatePad(self.item, soFarItems+soFar)
                if pad > 0:
                    soFarItems +=pad
                if dataClassOrCode is None:
                    nsofar = soFarItems + calcsize(item)
                    answer.append(unpack(item, data[soFarItems:nsofar])[0])
                else:
                    itemn = dataClassOrCode(isNDR64=self._isNDR64)
                    size = itemn.fromString(data[soFarItems:],
soFar+soFarItems)
                    answer.append(itemn)
                    nsofar += size + pad
                numItems -= 1
                soFarItems = nsofar

For each logon record returned, this loop runs about 6800 times, advancing
one character at each iteration.  The repeated call to calculatePad is one
of the expensive parts of this loop.  The call to fromString also takes a
lot of time.


Steve Koehler

**Comment by asolino** [comment]
Won't fix at the moment. Pull requests welcomed for those that want to work on performance enhancements.
