### ISSUE TITLE
Print wmiexec's output as it arrives from the network

### ISSUE THREAD

**Issue by reinaldo-gomes** [SecureAuthCorp/impacket#418]
It would be really helpful to me if wmiexec's output was simillar to atexec: output is printed in blocks, as it arrives from the target, while wmiexec waits for the whole file to be downloaded, before printing it.

The reason is that I usually download large files (tens of MB) over a VERY slow link, and I need to know how much of the file I have downloaded so far, or even if something went wrong with the transfer.

Can anyone do it or at least point in the right direction?

ps: Unfortunately, atexec is not an option in these operations, due to bizarre permission issues with the application (HP Data Protector Manager's command line), which do not occur when using wmiexec.

**Comment by reinaldo-gomes** [comment]
After fiddling around with this issue for quite a bit, I've managed to make my problematic commands run by completely removing the "UserID" node from atexec.py's XML... but only for as long as the given user (used in atexec's auth) is currently logged on to the windows server.

This makes me wonder: is it really necessary in some cases?

Still got to figure out how to either successfully run my command through atexec when not logged in to the windows server, or getting wmiexec's output to be flushed out as soon as it's available...

**Comment by asolino** [comment]
Please create separate issues with repro steps so I can better analyze what's going on. Closing this one.
