### ISSUE TITLE
mimikatz.py Does Not Work. 

### ISSUE THREAD

**Issue by Tylous** [SecureAuthCorp/impacket#428]
I keep getting this error when ever I try to run mimikatz.py:

`./mimikatz.py <redacted> -debug`
`Impacket v0.9.17-dev - Copyright 2002-2018 Core Security Technologies`
` `
`Password:`
`[+] Your pycrypto doesn't support AES.MODE_CCM. Currently only pycrypto experimental supports this mode.`
`Download it from https://www.dlitz.net/software/pycrypto`
`[-] DCERPC Runtime Error: code: 0x16c9a0d6 - ept_s_not_registered`

The pycrypto is installed and the user I am testing with has admin rights.

`pip install pycrypto
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages`

I've even tested with the experimental version of pycrypto but with no luck.

**Comment by asolino** [comment]
Hey @Tylous 

Did you run `rpc::server` at the target (inside mimikatz)?

[Here](https://twitter.com/agsolino/status/843542109642743809?lang=en) you have an example.

**Comment by dirkjanm** [comment]
I was confused with this as well. If you're not aware of the history of this example, you'd assume that the example would first run mimikatz.exe at the target, and then interact with it. The current example only works when you already have mimikatz running on the other side. Maybe it would be good to clear this up a bit in the example itself? Or to add an option to spawn it automatically with psexec/wmiexec?

**Comment by Tylous** [comment]
Hey @asolino so to be clear you need to already have existing access to the remote system as well as the mimikatz files on said system?

**Comment by Lexus89** [comment]
Would be really nice if the script would upload all files and do it automatically

**Comment by asolino** [comment]
PRs are welcome to add that functionality. For now closing.
