### ISSUE TITLE
rdp_check.py SSL Error

### ISSUE THREAD

**Issue by Tylous** [SecureAuthCorp/impacket#429]
I keep on getting the following error, I was wondering  if anyone else has ran into this issue and how to resolve it?
`./rdp_check.py <redacted>`
`Impacket v0.9.17-dev - Copyright 2002-2018 Core Security Technologies`
` `
`Password:`
`Traceback (most recent call last):`
 ` File "./rdp_check.py", line 577, in <module>`
  `  check_rdp(address, username, password, domain, options.hashes)`
  `File "./rdp_check.py", line 410, in check_rdp`
  `  ctx.set_cipher_list('RC4')`
  `File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 832, in set_cipher_list`
   ` _lib.SSL_CTX_set_cipher_list(self._context, cipher_list) == 1`
 ` File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 61, in openssl_assert`
  `  exception_from_error_queue(error)`
  `File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue`
   ` raise exception_type(errors)`
`OpenSSL.SSL.Error: [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')`

**Comment by asolino** [comment]
Hey @Tylous 

Thanks for the report. Yes I saw that error before, and that probably means your target servers do not support `RC4` as the cipher used for SSL.

Can you test replacing [this line](https://github.com/CoreSecurity/impacket/blob/master/examples/rdp_check.py#L410) inside the `rdp_check.py` script with [this other line](https://github.com/CoreSecurity/impacket/blob/master/impacket/tds.py#L911) an let me know if it works on your side?

thanks.

**Comment by Tylous** [comment]
I will give that a shot tonight and see if that works.

**Comment by Tylous** [comment]
I tried changing that line but no luck. I am  currently using pyOpenSSL (16.2.0).

**Comment by hatlord** [comment]
Same issue here. Targets have RC4 enabled.

**Comment by asolino** [comment]
Hey guys, can you `git pull` and recheck? You will need to have `pyOpenSSL>=0.16.2` installed from now on.

**Comment by hatlord** [comment]
Thanks Asolino, sadly, I get errors. The following error is against a Windows 2008 R2 DC in my lab. The RDP setup is default and all the basic ciphers are there. I can RDP to it with the MS client. PyOpenSSL is v18.0.

```
./rdp_check.py LAB/administrator:Qwerty1@10.10.10.11
Impacket v0.9.18-dev - Copyright 2002-2018 Core Security Technologies

Traceback (most recent call last):
  File "./rdp_check.py", line 577, in <module>
    check_rdp(address, username, password, domain, options.hashes)
  File "./rdp_check.py", line 413, in check_rdp
    tls.do_handshake()
  File "/Users/rich/Library/Python/2.7/lib/python/site-packages/OpenSSL/SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/rich/Library/Python/2.7/lib/python/site-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "/Users/rich/Library/Python/2.7/lib/python/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_hello', 'wrong ssl version')]
```

This output is from a 2003 box, again, default settings. Confirmed I can RDP to it with the MS client on Mac.

```
./rdp_check.py WORKGROUP/administrator:Password123@10.10.10.12
Impacket v0.9.18-dev - Copyright 2002-2018 Core Security Technologies


RDP_NEG_FAILURE
DST-REF: {0}
SRC-REF: {13330}
CLASS-OPTION: {0}
Type: {3}
Flags: {0}
Length: {8}
failureCode: {2}
[-] Server doesn't support PROTOCOL_HYBRID, hence we can't use CredSSP to check credentials
```

**Comment by yixiangwenhai** [comment]
do you have to solve this problem now? When I test on Windows 7 or 2008 r2 found the same problem
