### ISSUE TITLE
Request vncexec.py

### ISSUE THREAD

**Issue by Lexus89** [SecureAuthCorp/impacket#458]
A script using the impacket library was made to create vnc connections. It would be nice to see this script in the impacket examples and to further improve the script for example by adding an execution method of the ps1 using the psexec style as currently only wmi is supported.

https://github.com/klsecservices/Invoke-Vnc

**Comment by asolino** [comment]
Looks like an interesting addition. We're open for PRs if somebody is willing to give it a try. Closing for now.
