### ISSUE TITLE
Feature Request: Identify local admin access when listing socks relays

### ISSUE THREAD

**Issue by 0xhexmex** [SecureAuthCorp/impacket#468]
I've been playing around with the `-socks` option in `v0.9.18-dev` and ended up with a nice list of about 20+ open socks relays for various domain users against multiple hosts.

One thing that would be awesome (if it's possible) would be to mark which of the open relays are for admin-level sessions. As it is now, I work my way down the list trying secretsdump.py against each connection hoping to find a local admin. 

Maybe a way to implement that check would be to check for access to the ADMIN$ or C$ share upon successful SMB authentication? If that's successful, just a simple asterisk next to the admin-level socks connections could do the trick.

Thanks!

**Comment by asolino** [comment]
Solved in https://github.com/SecureAuthCorp/impacket/pull/548
