### ISSUE TITLE
Add some automated testing?

### ISSUE THREAD

**Issue by cclauss** [SecureAuthCorp/impacket#482]
Is it time to add some automated testing like Travis CI, Circle CI, Appveyor, etc.? https://github.com/marketplace/category/continuous-integration  Linking these to the existing Tox tests is fairly straightforward.

**Comment by asolino** [comment]
I would love to add some automated testing functionality @cclauss. Now, does any of those CI providers support having a DC configured to launch the tests against?

**Comment by cclauss** [comment]
DC?

**Comment by asolino** [comment]
Domain Controller. We would need to have a Windows Server configured as domain controller in order to launch all the SMB/RPC tests against.

**Comment by cclauss** [comment]
You got a Docker Image for the DC?  They will all let you launch a Docker Image to test against.

**Comment by asolino** [comment]
I don't. I have multiple VMs with different Windows Server versions (e.g. 2008R2, 2012, etc) configured as domain controllers that I test impacket against.

**Comment by cclauss** [comment]
Could we add Travis CI, Circle CI, or Appveyor just to start doing some static analysis like #494 and maybe even run the __tox__ tests?  Once the test runner is working, we can add more tests to it.
