### ISSUE TITLE
GetUserSPNs.py -  'module' object has no attribute 'Present'

### ISSUE THREAD

**Issue by angusonmacgyver** [SecureAuthCorp/impacket#484]
/usr/share/doc/python-impacket/examples/GetUserSPNs.py -dc-ip 10.10.10.100 -request ACTIVE.local/USER
Impacket v0.9.18-dev - Copyright 2002-2018 Core Security Technologies

Password:
'module' object has no attribute 'Present'

After I input password I get this error. Any ideas why is that ?

**Comment by angusonmacgyver** [comment]
However if I run the same command from extracted zip it works without any issues.

**Comment by asolino** [comment]
Reopen if you're still experiencing this issue
