### ISSUE TITLE
while running on windows machine E:\python cmd>python dcs.py Traceback (most recent call last):   File "dcs.py", line 39, in <module>     from impacket.examples import logger ImportError: No module named impacket.examples

### ISSUE THREAD

**Issue by rajvardhan7744** [SecureAuthCorp/impacket#488]
here , dcs.py its smbexec.py 

E:\python cmd>python dcs.py
Traceback (most recent call last):
  File "dcs.py", line 39, in <module>
    from impacket.examples import logger
ImportError: No module named impacket.examples

**Comment by asolino** [comment]
I can't understand this issue. Closing.
Next time please put the necessary steps for me to reproduce the issue. Otherwise I cannot help.
