### ISSUE TITLE
something wrong?

### ISSUE THREAD

**Issue by gaodaqiang1** [SecureAuthCorp/impacket#489]
proxychains python mssqlclient.py sa:123456@192.168.126.202
ProxyChains-3.1 (http://proxychains.sf.net)
Impacket v0.9.18-dev - Copyright 2002-2018 Core Security Technologies

|D-chain|-<>-144.48.xxx.xxx:8080-<><>-192.168.126.202:1433-<><>-OK
[*] Encryption required, switching to TLS

it stopped here

**Comment by asolino** [comment]
Can't say much with that output.
