### ISSUE TITLE
ImportError: No module named ldap

### ISSUE THREAD

**Issue by nrrpinto** [SecureAuthCorp/impacket#501]
I am trying to execute the following command:
> python /usr/share/doc/python-impacket/examples/GetUserSPNs.py -request -dc-ip 10.10.XX.XXX <domain>/<user> -outputfile kerberoast.txt

And I get the following error:

> Traceback (most recent call last):
>   File "/usr/share/doc/python-impacket/examples/GetUserSPNs.py", line 48, in <module>
>     from impacket.ldap import ldap, ldapasn1
> ImportError: No module named ldap

I have installed all the libraries but i still got the same error. Can someone help me? Thanks in advance.

**Comment by asolino** [comment]
Hey @nrrpinto 

You probably have an older impacket version already installed and is being loaded before the new one. Please check [this](https://github.com/SecureAuthCorp/impacket/issues/212) and close this issue if that solves your problem. If not, send me the version you are running (output of the first line of the script being executed)

**Comment by nrrpinto** [comment]
Hi @asolino,

Thanks so much for the tip. Yes, it did solve my problem.
