### ISSUE TITLE
secretsdump.py - Error while calling getNextRow() (previously utf16 codec error)

### ISSUE THREAD

**Issue by Aurakal** [SecureAuthCorp/impacket#503]
Hi,

I'm having an issue with secretsdump.py on a ntds.dit file coming from a Windows Server 2016. When I run secretsdump.py on it:

`secretsdump.py -ntds ntds.dit -system SYSTEM LOCAL`

It returns the following:

```
Impacket v0.9.17 - Copyright 2002-2018 Core Security Technologies

[*] Target system bootKey: 0xc03fcc27eb232e8cf9aedfe9dccb2af8
[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Searching for pekList, be patient
[-] Error while calling getNextRow(), trying the next one
```

Previously, I was on the v.0.9.16-dev branch, and I had an utf16 codec error.

```
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[*] Target system bootKey: 0xc03fcc27eb232e8cf9aedfe9dccb2af8
[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Searching for pekList, be patient
[-] 'utf16' codec can't decode bytes in position 0-1: illegal encoding
[*] Cleaning up...
```
Is it possible that Impacket isn't updated to support the extraction of ntds.dit files from a Windows Server 2016 yet? I can provide all the logs, and debugging data needed (minus the actual ntds.dit and SYSTEM files, obviously).

Thank you.

**Comment by asolino** [comment]
Are you getting that error for every Row? Are you getting any user data back?
I have tested the script against 2016 (a while back tho) and it was working. 
I'd suggest trying the DRSUAPI method.

**Comment by Aurakal** [comment]
What happens is that after getting the first getNextRow() error, nothing happens. It looks stuck. Then when I press "Ctrl + C", it keeps on printing the same getNextRow() error message, as if it was trying to move on. I can only kill the process using "Ctrl + Z". And I'm not getting any user data back, no.

Ideally, I would like to crack the passwords "offline" (local), but I can give the DRSUAPI method a try and see how it goes.

**Comment by asolino** [comment]
Just tested again a W2k16 and it worked, although it is not fully updated. I don't think you can provide the DIT and reg hives for testing I assume.

the DRSUAPI method will allow you to do offline cracking, the only difference is that you dump the DIT contents live. However, it is much more accurate and reliable since it mimics a DC replication process. Use the `-outputfile` argument to save all the data.

**Comment by Aurakal** [comment]
I would but I can't sadly, since these are used in a Prod environment. Also, I have 2 ntds.dit files, both from 2 different Windows Server 2016 DCs and the results are the same.

On a side note, it seems that esedbexport (libesedb) and esentutl.py (Impacket) also have a hard time with my Windows Server 2016 hives, as they also fail to extract them. The only tool that has worked so far, is DSInternals.

**Comment by Aurakal** [comment]
Just to let you know that I'll be trying the DRSUAPI method this week. Also, I'll update my Impacket version to the GitHub one (dev branch) and see if that "fixes" the issue.

**Comment by asolino** [comment]
> On a side note, it seems that esedbexport (libesedb) and esentutl.py (Impacket) also have a hard time with my Windows Server 2016 hives, as they also fail to extract them. The only tool that has worked so far, is DSInternals.

It makes sense that `esentutl.py` fails since it is using the same underlying library. What is the error thrown?

I will update my 2016 server and give it another try. 

Let me know if the DRSUAPI method worked for you.

**Comment by Aurakal** [comment]
Alright so I tested the DRSUAPI method, using a Domain Admin account, and it works. However, I cannot use that method, as:

1) I don't want to add a Domain Admin account only for password cracking purposes
2) Since I'm working on automating our password cracking process (Python script), I don't want to leave the password somewhere where it would be "easily" acccessible (for a Domain Admin account too).

As for esentutl.py, I'm running it right now to see what the error is.

Didn't think of updating to the GitHub dev branch too, will do it after.

**Comment by Aurakal** [comment]
I ran esentutl.py against a ntds.dit coming from a Windows Server 2008 DC, and then did a grep for the string "ATTk590689" and it returned something.

Would you be able to provide me an exempt of your esentutl.py extract of your Windows Server 2016 ntds.dit (assuming there's no production data in it)? I would like to compare the area where that string is, and see if I can find where it should be in my extract.

**Comment by asolino** [comment]
Sure thing. Tell me what you need me to run.

**Comment by asolino** [comment]
Btw.. running `./esentutl.py w16/ntds.dit export -table datatable | grep -E "ATTk590689"` returns data for me. 
Looking at the links you sent: 
_Notice esedbexport is running on this same ntds file (from some days) and there is an "ATTk590689"(Pek-List) attribute in database file (database.4 file)_

Can you try that?.. If that's the case, there's gotta be a bug in `ese.py` that we will need to nail down

**Comment by Aurakal** [comment]
Might be a very crude method, but if you can run these commands:

`cat ntds-extracted-file | grep -nre ATTk590689`

So I can see around which line that value is and:

`cat ntds-extracted-file | grep -B 100 -A 100 ATTk590689`

So I can see what kind of data is wrapped around that line.

Regarding esedbexport, it doesn't work. If I try to extract a Windows Server 2016 ntds.dit using it, I get this error:

```
esedbexport 20170121

Opening file.
Unable to open: ../DOMAIN/ntds.dit.
libesedb_catalog_definition_read: unsupported last fixed size data type: 12.
libesedb_catalog_read: unable to read catalog definition.
libesedb_file_open_read: unable to read catalog.
libesedb_file_open_file_io_handle: unable to read from file handle.
libesedb_file_open: unable to open file: ../DOMAIN/ntds.dit.
export_handle_open: unable to open input file.
```
Which is apparently a known issue:

https://github.com/libyal/libesedb/issues/34

PS: Sorry if my troubleshooting steps are weird, I'm not a programmer at all, so doing my debugging steps are closer to traditional tech support than code debugging.

**Comment by asolino** [comment]
> cat ntds-extracted-file | grep -nre ATTk590689

`(standard input):70152:ATTk590689                    : '0300000001000000fe86f0cb211b1d4fcb9711242008a928a81c861c26bdd74cd8892956391975ed2128940211b39af726d54c456ef97a5d3e4cf5a1f171899c67f66b767792f51b44f8e5c210caac2c66e601e4da79185700000000000000000000000000000000'`

> cat ntds-extracted-file | grep -B 100 -A 100 ATTk590689

```
ATTk589827                    : '69000000'
ATTc131094                    : 655660
ATTk589972                    : '939069f25af220429deb03df4cc4a9c5'
ATTc131093                    : 65536
ATTm590048                    : u'D:(A;;RPWPCRCCDCLCLORCWOWDSDDTSW;;;DA)(A;;RPWPCRCCDCLCLORCWOWDSDDTSW;;;ED)(A;;RPWPCRCCDCLCLORCWOWDSDDTSW;;;SY)(A;;CC;;;AU)(A;;RPLCLORC;;;WD)(A;;RPWPCRCCDCLCLORCWOWDSDDTSW;;;CO)'
ATTi589994                    : 0
ATTq131192                    : 2026
ATTl131075                    : 13097348602
ATTm589825                    : u'Dns-Zone-Scope-Container'
ATTb590607                    : 2037
ATTj131442                    : 1
ATTm3                         : u'Dns-Zone-Scope-Container'
ATTj131073                    : 4
ATTq131091                    : 2026
ATTl131074                    : 13097348602
ATTp131353                    : '0700000000000000'
ATTk589826                    : 'df0360836ae4654291d50d3a26e1f3c5'
ATTc590019                    : 655445
ATTb590606                    : 1511
ATTj590199                    : 16
*** 1770
DNT_col                       : 2039
PDNT_col                      : 2066
OBJ_col                       : 1
RDNtyp_col                    : 3
cnt_col                       : 2
ab_cnt_col                    : 0
time_col                      : 13097348602
NCDNT_col                     : 2066
IsVisibleInAB                 : 42
recycle_time_col              : 3038287259199220266
Ancestors_col                 : '02000000f9070000fa070000fb07000012080000f7070000'
ATTc590021                    : 1376281
ATTm131532                    : u'dnsZoneScope'
ATTm131298                    : u'A zonescope of a zone is another copy of the zone contained in the zone with different set of resource records.'
ATTl591181                    : 0
ATTc131098                    : 3
ATTi590342                    : 1
ATTi131241                    : 1
ATTc590020                    : '041a0509008d020900'
ATTm131266                    : u'Dns-Zone-Scope'
ATTb49                        : 2039
ATTc0                         : '040d00030000000100'
ATTk589827                    : '68000000'
ATTc131094                    : 655661
ATTk589972                    : '618a6f693f2dce40a4b3e275dfcc49c5'
ATTc131093                    : 65536
ATTm590048                    : u'D:(A;;RPWPCRCCDCLCLORCWOWDSDDTSW;;;DA)(A;;RPWPCRCCDCLCLORCWOWDSDDTSW;;;ED)(A;;RPWPCRCCDCLCLORCWOWDSDDTSW;;;SY)(A;;CC;;;AU)(A;;RPLCLORC;;;WD)(A;;RPWPCRCCDCLCLORCWOWDSDDTSW;;;CO)'
ATTi589994                    : 0
ATTq131192                    : 2028
ATTl131075                    : 13097348602
ATTm589825                    : u'Dns-Zone-Scope'
ATTb590607                    : 2039
ATTj131442                    : 1
ATTm3                         : u'Dns-Zone-Scope'
ATTj131073                    : 4
ATTq131091                    : 2028
ATTl131074                    : 13097348602
ATTp131353                    : '0700000000000000'
ATTk589826                    : '7d50ef00426dcb4fbb3c50c4c4c4be5e'
ATTc590019                    : 655660
ATTb590606                    : 1511
ATTj590199                    : 16
*** 1771
DNT_col                       : 2041
PDNT_col                      : 2
OBJ_col                       : 0
RDNtyp_col                    : 1376281
cnt_col                       : 1
ab_cnt_col                    : 0
time_col                      : 13178055067
Ancestors_col                 : '02000000f9070000'
ATTm589825                    : u'NET'
*** 1772
DNT_col                       : 2042
PDNT_col                      : 2041
OBJ_col                       : 1
RDNtyp_col                    : 1376281
cnt_col                       : 26
ab_cnt_col                    : 0
time_col                      : 13147229332
NCDNT_col                     : 2
IsVisibleInAB                 : 42
recycle_time_col              : 3038287259199220266
Ancestors_col                 : '02000000f9070000fa070000'
ATTq589850                    : 131841789876710919
ATTm590715                    : u'[LDAP://CN={31B2F340-016D-11D2-945F-00C04FB984F9},CN=Policies,CN=System,DC=FREEFLY16,DC=NET;0]'
ATTj591283                    : 7
ATTj591848                    : 0
ATTl591181                    : 0
ATTr589970                    : '0104000000000005150000005df4b9d4074fe8b48205181f'
ATTi590692                    : 1
ATTb590192                    : 4120
ATTq589863                    : 9223372036854775808L
ATTj591235                    : 10
ATTk590026                    : '0001'
ATTq589898                    : 18446707785709551616L
ATTb49                        : 2042
ATTq589884                    : 18446744055709551616L
ATTc0                         : '06000a000e0043000a0042000a0000000100'
ATTk590689                    : '0300000001000000fe86f0cb211b1d4fcb9711242008a928a81c861c26bdd74cd8892956391975ed2128940211b39af726d54c456ef97a5d3e4cf5a1f171899c67f66b767792f51b44f8e5c210caac2c66e601e4da79185700000000000000000000000000000000'
ATTk589827                    : '000b0000'
ATTj589912                    : 1000
ATTh591183                    : '04001c000c080000140000001eb93889e40c45df9f0c64d23bbb62370d08000014000000683a24e2e8164bd3af86ac3c2cf3f981'
ATTk589828                    : '0200000000000000020000000000000082fea1969479724ea973f1d6c6d8a34c1a60000000000000deff7811030000002a8f3fea8feb1b4d8abb7ef9e981b9fbeb5f000000000000d7aad50f03000000'
ATTk131146                    : '0100000028000000000000000000000000000000000000002a8f3fea8feb1b4d8abb7ef9e981b9fb'
ATTq131192                    : 49162
ATTl131075                    : 13184178987
ATTj589979                    : 1
ATTm589825                    : u'FREEFLY16'
ATTj591612                    : 1
ATTj589917                    : 1
ATTj590181                    : 0
ATTj131073                    : 5
ATTj589978                    : 1
ATTq589905                    : 0
ATTh590442                    : '16002e0046005e0076008e00a600be00d600ee0006010108000014000000a9d1ca15768811d1aded00c04fd8d5cd0208000014000000aa312825768811d1aded00c04fd8d5cd0308000014000000a361b2ffffd211d1aa4b00c04fd7d83a0408000014000000ab1d30f3768811d1aded00c04fd8d5cd0508000014000000ab8153b7768811d1aded00c04fd8d5cd06080000140000002fbac1870ade11d297c400c04fd8d5cd070800001400000018e2ea80684f11d2b9aa00c04f79f805080800001400000022b70c67d56e4efb91e9300fca3dc1aa090800001400000009460c08ae1e4a4ea0f64aee7daa1e5a0a08000014000000f4be92a4c777485e878e9421d53087db0b080000140000006227f0af1fc2410d8e3bb10615bb5b0f'
ATTq131091                    : 4099
ATTl131074                    : 13147229332
ATTp131353                    : '9800000000000000'
ATTq589885                    : 18446744055709551616L
ATTb131079                    : '06000a000e00fb070000531000005b100000'
ATTk589826                    : '61f135cc3932d447b04e21257256e6c6'
ATTm1376281                   : u'FREEFLY16'
ATTq589992                    : 1
ATTb590193                    : 2048
ATTi592168                    : 1
ATTj589897                    : 0
ATTb590606                    : 1586
ATTj591613                    : 1000
ATTj591614                    : 10
ATTj589903                    : 7
ATTj589919                    : 24
ATTq589902                    : 18446743209709551616L
ATTj590199                    : -1946157056
*** 1773
DNT_col                       : 2043
PDNT_col                      : 2042
OBJ_col                       : 1
RDNtyp_col                    : 3
cnt_col                       : 18
ab_cnt_col                    : 0
time_col                      : 13147229332
NCDNT_col                     : 2042
IsVisibleInAB                 : 42
recycle_time_col              : 3038287259199220266
Ancestors_col                 : '02000000f9070000fa070000fb070000'
ATTj591848                    : 0
ATTl591181                    : 0
ATTi131241                    : 1
ATTb49                        : 2043
ATTc0                         : '040c000a0000000100'
ATTk589827                    : '01000000000000000a00000000000000000000000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb05100000000000000510000000000000030000000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb05100000000000000510000000000000010002000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb05100000000000000510000000000000020002000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb051000000000000005100000000000004a00020002000000c7add50f0300000082fea1969479724ea973f1d6c6d8a34cfc5f000000000000fc5f000000000000a90002000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb05100000000000000510000000000000190102000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb05100000000000000510000000000000010009000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb051000000000000005100000000000006a0209000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb051000000000000005100000000000000e0309000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb05100000000000000510000000000000'
ATTk589828                    : '0200000000000000020000000000000082fea1969479724ea973f1d6c6d8a34c1a60000000000000deff7811030000002a8f3fea8feb1b4d8abb7ef9e981b9fbeb5f000000000000d7aad50f03000000'
ATTk131146                    : '0100000028000000000000000000000000000000000000002a8f3fea8feb1b4d8abb7ef9e981b9fb'
ATTq131192                    : 24572
ATTl131075                    : 13150563783
ATTm589825                    : u'Configuration'
ATTm3                         : u'Configuration'
ATTj131073                    : 13
ATTh590442                    : '06001e0036000f0800001400000018e2ea80684f11d2b9aa00c04f79f8051008000014000000ab8153b7768811d1aded00c04fd8d5cd11080000140000006227f0af1fc2410d8e3bb10615bb5b0f'
ATTq131091                    : 4101
ATTl131074                    : 13147229332
ATTp131353                    : '0500000000000000'
ATTb131079                    : 2066
ATTk589826                    : 'bf8308078c59c54daad821a50519e0c6'
ATTb590606                    : 1549
*** 1774
DNT_col                       : 2044
PDNT_col                      : 2043
OBJ_col                       : 1
RDNtyp_col                    : 3
cnt_col                       : 4
ab_cnt_col                    : 0
time_col                      : 13147229332
NCDNT_col                     : 2043
IsVisibleInAB                 : 42
recycle_time_col              : 3038287259199220266
Ancestors_col                 : '02000000f9070000fa070000fb070000fc070000'
ATTl591181                    : 0
ATTi131241                    : 1
ATTb49                        : 2044
ATTc0                         : '046b000a0000000100'
ATTk589827                    : '01000000000000000900000000000000000000000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb0b100000000000000b10000000000000030000000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb0b100000000000000b10000000000000010002000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb0b100000000000000b10000000000000020002000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb0b100000000000000b10000000000000a90002000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb0b100000000000000b10000000000000190102000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb0b100000000000000b10000000000000010009000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb0b100000000000000b10000000000000770109000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb0b100000000000000b100000000000000e0309000100000094cca20f030000002a8f3fea8feb1b4d8abb7ef9e981b9fb0b100000000000000b10000000000000'
ATTq131192                    : 4107
ATTl131075                    : 13147229332
ATTm589825                    : u'Sites'
ATTm3                         : u'Sites'
ATTj131073                    : 4
ATTq131091                    : 4107
ATTl131074                    : 13147229332
ATTp131353                    : '0a00000000000000'
ATTk589826                    : 'ff72eddbc035d6438d923491f13602d6'
ATTb590606                    : 1900
ATTj590199                    : -2113929216
*** 1775
DNT_col                       : 2045
PDNT_col                      : 2044
OBJ_col                       : 1
RDNtyp_col                    : 3
cnt_col                       : 4
```

**Comment by Aurakal** [comment]
For both ntds.dit (one from Windows Server 2008, and one from Windows Server 2016), this is what I get:

```
Impacket v0.9.18-dev - Copyright 2018 SecureAuth Corporation

[+] Mounting DB...
[+] Trying to fetch page -1 (0x0)
[+] Database Version:0x620, Revision:0x11
[+] Page Size: 8192
```

**Comment by Aurakal** [comment]
Might have found something. I'm currently reviewing the output of esentutl.py on the Windows Server 2016 hive, and I found this:

```
ATTm589852                    : u'DomainDnsZones.SUBDOMAIN.DOMAIN.com'
ATTb590606                    : 4935
ATTj590199                    : 5
[-] Error while calling getNextRow(), trying the next one
*** 5686
DNT_col                       : 8358
PDNT_col                      : 8357
OBJ_col                       : 1
RDNtyp_col                    : 1376281
cnt_col                       : 46
ab_cnt_col                    : 0
time_col                      : 1
NCDNT_col                     : 8357
IsVisibleInAB                 : 42
recycle_time_col              : 3038287259199220266
Ancestors_col                 : '02000000f9070000fa070000a5200000a6200000'
ATTm13                        : u'Microsoft DNS Directory'
```
And it jumps from *** 5684 to *** 5686, skipping *** 5685, where I suspect the pek is, because in the output from the Windows Server 2008 ntds.dit, the ATTk590689 line is in the *** section right after the Microsoft DNS Directory one.

Getting closer.

**Comment by asolino** [comment]
Just committed https://github.com/SecureAuthCorp/impacket/commit/a570dbce64e3c6203b944d40eb7830d83b631a5c that will provide stacktrace output when `getNextRow()` is failing. Don't forget to run it with `-debug`. Could be useful.

**Comment by Aurakal** [comment]
Alright, here it is:

```
ATTm589852                    : u'DomainDnsZones.groupe.jeancoutu.com'
ATTb590606                    : 4935
ATTj590199                    : 5
[+] Exception:
Traceback (most recent call last):
  File "/usr/local/bin/esentutl.py", line 42, in exportTable
    record = ese.getNextRow(cursor)
  File "/usr/local/lib/python2.7/dist-packages/impacket/ese.py", line 808, in getNextRow
    return self.__tagToRecord(cursor, tag['EntryData'])
  File "/usr/local/lib/python2.7/dist-packages/impacket/ese.py", line 952, in __tagToRecord
    record[column] = record[column].decode(stringDecoder)
  File "/usr/lib/python2.7/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf16' codec can't decode bytes in position 0-1: illegal encoding
[-] Error while calling getNextRow(), trying the next one
[+] Trying to fetch page 9449 (0x49d4000)
[+] Multivalue detected in column ATTk131163, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTk131155, returning raw results
[+] Multivalue detected in column ATTh590442, returning raw results
*** 5686
DNT_col                       : 8358
PDNT_col                      : 8357
OBJ_col                       : 1
RDNtyp_col                    : 1376281
cnt_col                       : 46
ab_cnt_col                    : 0
time_col                      : 1
NCDNT_col                     : 8357
IsVisibleInAB                 : 42
recycle_time_col              : 3038287259199220266
Ancestors_col                 : '02000000f9070000fa070000a5200000a6200000'
ATTm13                        : u'Microsoft DNS Directory'
```

So an issue with encoding? That error is the one I had previously back when I was using v0.9.16-dev.

**Comment by asolino** [comment]
I'd say it is more an issue with wrong parsing (that ends up with a decoding issue).

Please `git pull` again and re-run. I added extra debug info on that section.

**Comment by Aurakal** [comment]
I can't seem to find the extra logging information anywhere... should it be in the output file?

**Comment by asolino** [comment]
It should be logged in the same way as the errors you sent me. 
I basically added [this line](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/ese.py#L955) when the decode fails. It should read `Record[column]` following by the raw data that was tried to be decoded.

Try searching for that string. Are you sure you did a `git pull` and are using the updated version?

Are you still getting the errors (with stacktrace) you showed before?

**Comment by asolino** [comment]
Don't worry @Aurakal .. we're all learning all the time ;)

Doing it by hand works as well (as long as you do it in the same place). Just be sure you're changing the file that is actually used by the library. If you downloaded impacket, then unzipped it and finally ran `pip install` the working copy will be installed in the system. So if you change anything in your local unzipped directory, be sure to run `pip install .` again ( you might need to uninstall the library first). Just in case you didn't do it that way.

**Comment by asolino** [comment]
Great @Aurakal 

That is not a utf-16le char.. so there's an issue there (maybe DB corrupted). In any case, we might be able to skip it and hope for the best. But before that, let's check what column is that. Please replace the line I added before for:
```
LOG.debug('Record[%r]: %r' % (column, record[column]))
```
And then inspect with `ditsnap` what is the value for the attribute is.  If they match, that's an easy fix.

**Comment by asolino** [comment]
Thanks for the data @Aurakal 

> Can ese.py by adjusted so that if I encounter a utf-16le encoding error, it just moves on to the next attribute in the current row instead of going to the next one?

Yes it can.. Although if we're talking about a LongBinary type, the program should have reached that section (it's only meant to decode if the attribute is JET_coltypText or JET_coltypLongText), but that could be another issue. Let's do this, Please replace the previous line with these three:
```
LOG.debug('Record[%r][%d]: %r' % (column, columnRecord['ColumnType'], record[column]))
record[column] = record[column].decode(stringDecoder, "replace")
pass
```  
I'm adding in the `LOG.debug` the columnType, to verify what's there, and then I'm decoding the data but replacing the badchars. Let's give it a try and send me the output.

thanks

**Comment by Aurakal** [comment]
Alright, here it is.
```
*** 5685
DNT_col                       : 8356
PDNT_col                      : 7352
[...]
[+] Record['ATTm590715'][12]: '\x18\xdd\x01\x00'
[+] Multivalue detected in column ATTk131163, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTk131155, returning raw results
[+] Multivalue detected in column ATTh591183, returning raw results
[+] Multivalue detected in column ATTh590442, returning raw results
*** 5686
DNT_col                       : 8357
PDNT_col                      : 2042
[...]
ATTk590689                    : '[REDACTED]'
```
It was able to continue parsing the file, and I can see my pek attribute (ATTk590689) now! :) So it works! I'll try it with Impdump and see if it works properly.

**Comment by asolino** [comment]
> It was able to continue parsing the file, and I can see my pek attribute (ATTk590689) now! :) So it works! I'll try it with Impdump and see if it works properly

Ok.. so there's an inconsistency there but maybe it is not fatal. 
You can actually run `secretsdump.py` since it uses `ese.py` to parse the DIT file.
Let me know how it goes

**Comment by Aurakal** [comment]
Ran secretsdump.py on the ntds.dit file and it was able to extract the hashes! I'll try ImpDump once I get back to work on Monday, but at this point, if it doesn't work, I'll open a new issue for that project, since ese.py can now process the .dit file and retrieve the pek attribute.

Another thing I'll try on Monday as well, just to be sure, is to run secretsdump.py against the whole .dit file (I killed it after a couple of extracts, just wanted to see if it worked now or not) and see if it goes through it properly (doesn't jump in a never-ending loop or else).

Thank you for all your assistance with this asolino! 👍

**Comment by asolino** [comment]
This is great news @Aurakal 

Please let me know if the hashes extracted are working, that is crucial for me to decide whether or not to include this fix in the public version. 
Using pass-the-hash techniques or comparing it with the DRSUAPI method could be a good idea.

**Comment by Aurakal** [comment]
So I just ran my password cracking script (which uses esentutl.py to extract the data from the ntds.dit files, and then uses impdump.py to go through it) and it looks like it worked. I'm doing this for 3 domains, and for one of them, it looks like impdump.py crashed when it tried to dump the hashes. I'll look into it, but I doubt that this is related to the extraction process of esentutl.py. I'll see if I can adjust my script to use secretsdump.py instead, since it looks faster anyway. 

Here's the error from impdump.py, if you're curious:
```
Traceback (most recent call last):
  File "/root/Crack/ImpDump/impdump.py", line 241, in <module>
    decUserHashes(sys.argv[1], sys.argv[2])
  File "/root/Crack/ImpDump/impdump.py", line 190, in decUserHashes
    print decUserHash(bootkey, rawPekKey, name, rawRID, "", rawNTLMhash)
  File "/root/Crack/ImpDump/impdump.py", line 53, in decUserHash
    ntlm = ds_decrypt_single_hash(rid, encNTLM)
  File "/root/Crack/ImpDump/framework/win32/dshashdump.py", line 58, in ds_decrypt_single_hash
    hash = d1.decrypt(enc_hash[:8]) + d2.decrypt(enc_hash[8:])
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 8 in length
```
Other than that, I guess this can be considered a case closed :)

**Comment by asolino** [comment]
Great news @Aurakal. Thanks a lot for your help nailing this down. Closing now.
