### ISSUE TITLE
SMB Server Upload and Download is really slow

### ISSUE THREAD

**Issue by HoseinTB** [SecureAuthCorp/impacket#515]
I run SMB Server on Ubuntu server 16.04
Upload and download speeds are less than 7MB/s 
is there any solution or workaround for this problem ?

**Comment by asolino** [comment]
Have you tried running it with `-smb2support` switch? Be sure the client is using SMB2 protocol.

In any case, upload/download performance is not a big priority at the moment. I'm sure there are way to better improve it.

**Comment by asolino** [comment]
No answer.. closing
