### ISSUE TITLE
can't install in python2.7 with pip 8.1.2 centos7 with version error on 0.9.17

### ISSUE THREAD

**Issue by WoolenWang** [SecureAuthCorp/impacket#523]
Downloading http://mirrors.sangfor.org/pypi/web/+f/68d/47b101392e68e/impacket-0.9.17.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 25.4MB/s 
    Complete output from command python setup.py egg_info:
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    error in impacket setup command: Invalid environment marker: python_version<"2.7"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Fh4dgR/impacket/

use pip to install this pkg will get this error

**Comment by cclauss** [comment]
Or __pip install --upgrade pip__ (you might to run via __sudo__)
