### ISSUE TITLE
Undefined name: __spec__ in examples/ntlmrelayx

### ISSUE THREAD

**Issue by cclauss** [SecureAuthCorp/impacket#529]
Why does flake8 flag '`__spec__`' as an undefined name?
https://travis-ci.com/SecureAuthCorp/impacket/jobs/160606437#L528

Interestingly, this happens on the Python 2 tests but _not_ on the Python 3 tests.

Oh... https://docs.python.org/3/reference/import.html#module-spec added in Python 3.4.

**Comment by asolino** [comment]
As commented by @dirkjanm [here](https://github.com/SecureAuthCorp/impacket/blob/python36/impacket/examples/ntlmrelayx/attacks/__init__.py#L50)
>   This seems to be None in some case (py3 only)
>   \_\_spec\_\_ is py3 only though, but I haven't seen this being None on py2
>   so it should cover all cases.

Maybe we should explicitly check we're running Python3 and skip it in Python2 so flake doesn't catch it.. I don't know.

**Comment by cclauss** [comment]
Fixed in #530
