### ISSUE TITLE
struct.pack(B | 0.0 | None) DeprecationWarning: ('integer argument expected, got float')

### ISSUE THREAD

**Issue by contactr2m** [SecureAuthCorp/impacket#546]
Debug level output of negotiate session.
-
I upgraded the impacket library and getting this since then.
I saw recent commit to [structure.py c15d447084]
(https://github.com/SecureAuthCorp/impacket/commit/c15d447084f665762d3857e088fc6e095463d488#diff-ce6a66d1936fa241ef5528069290daba)
-
controller_initialize connecting to server...
structure:packField:MainProcess:MainThread[102]: packField( Signature | "�SMB )
   pack( "�SMB | None | Signature)
structure:packField:MainProcess:MainThread[113]: 	answer '\xffSMB'
structure:packField:MainProcess:MainThread[102]: packField( Command | B=0 )
   pack( B=0 | 114 | Command)
   pack( B | 114 | None)
structure:packField:MainProcess:MainThread[113]: 	answer 'r'
structure:packField:MainProcess:MainThread[102]: packField( ErrorClass | B=0 )
   pack( B=0 | None | ErrorClass)
   pack( B | None | None)
   pack( B | 0 | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\x00'
structure:packField:MainProcess:MainThread[102]: packField( _reserved | B=0 )
   pack( B=0 | None | _reserved)
   pack( B | None | None)
   pack( B | 0 | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\x00'
structure:packField:MainProcess:MainThread[102]: packField( ErrorCode | <H=0 )
   pack( <H=0 | None | ErrorCode)
   pack( <H | None | None)
   pack( <H | 0 | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\x00\x00'
structure:packField:MainProcess:MainThread[102]: packField( Flags1 | B=0 )
   pack( B=0 | 24 | Flags1)
   pack( B | 24 | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\x18'
structure:packField:MainProcess:MainThread[102]: packField( Flags2 | <H=0 )
   pack( <H=0 | 51201 | Flags2)
   pack( <H | 51201 | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\x01\xc8'
structure:packField:MainProcess:MainThread[102]: packField( PIDHigh | <H=0 )
   pack( <H=0 | None | PIDHigh)
   pack( <H | None | None)
   pack( <H | 0 | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\x00\x00'
structure:packField:MainProcess:MainThread[102]: packField( SecurityFeatures | 8s="" )
   pack( 8s="" | None | SecurityFeatures)
   pack( 8s | None | None)
   pack( 8s | '' | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\x00\x00\x00\x00\x00\x00\x00\x00'
structure:packField:MainProcess:MainThread[102]: packField( Reserved | <H=0 )
   pack( <H=0 | None | Reserved)
   pack( <H | None | None)
   pack( <H | 0 | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\x00\x00'
structure:packField:MainProcess:MainThread[102]: packField( Tid | <H=0xffff )
   pack( <H=0xffff | None | Tid)
   pack( <H | None | None)
   pack( <H | 65535 | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\xff\xff'
structure:packField:MainProcess:MainThread[102]: packField( Pid | <H=0 )
   pack( <H=0 | None | Pid)
   pack( <H | None | None)
   pack( <H | 0 | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\x00\x00'
structure:packField:MainProcess:MainThread[102]: packField( Uid | <H=0 )
   pack( <H=0 | None | Uid)
   pack( <H | None | None)
   pack( <H | 0 | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\x00\x00'
structure:packField:MainProcess:MainThread[102]: packField( Mid | <H=0 )
   pack( <H=0 | None | Mid)
   pack( <H | None | None)
   pack( <H | 0 | None)
structure:packField:MainProcess:MainThread[113]: 	answer '\x00\x00'
structure:packField:MainProcess:MainThread[102]: packField( Data | *: )
   pack( *: | [<impacket.smb.SMBCommand instance at 0x7f140e0f8f38>] | Data)
   pack( : | <impacket.smb.SMBCommand instance at 0x7f140e0f8f38> | None)
structure:packField:MainProcess:MainThread[102]: packField( WordCount | B=len(Parameters)/2 )
   pack( B=len(Parameters)/2 | None | WordCount)
   pack( B | None | None)
   pack( B | 0.0 | None)
```python
  Traceback (most recent call last):
      connection = SMBConnection(remoteHost='10.1.9.175', remoteName='10.1.9.175')
    File "/usr/tools/lib/python2.7/site-packages/impacket/smbconnection.py", line 74, in __init__
      self.negotiateSession(preferredDialect)
    File "/usr/tools/lib/python2.7/site-packages/impacket/smbconnection.py", line 111, in negotiateSession
      self._timeout, True, flags1=flags1, flags2=flags2, data=negoData)
    File "/usr/tools/lib/python2.7/site-packages/impacket/smbconnection.py", line 168, in negotiateSessionWildcard
      self._nmbSession.send_packet(str(smbp))
    File "/usr/tools/lib/python2.7/site-packages/impacket/structure.py", line 172, in __str__
      return self.getData()
    File "/usr/tools/lib/python2.7/site-packages/impacket/structure.py", line 123, in getData
      data += self.packField(field[0], field[1])
    File "/usr/tools/lib/python2.7/site-packages/impacket/structure.py", line 108, in packField
      ans = self.pack(format, self.fields[fieldName], field = fieldName)
    File "/usr/tools/lib/python2.7/site-packages/impacket/structure.py", line 229, in pack
      answer += self.pack(two[1], each)
    File "/usr/tools/lib/python2.7/site-packages/impacket/structure.py", line 266, in pack
      return data.getData()
    File "/usr/tools/lib/python2.7/site-packages/impacket/structure.py", line 123, in getData
      data += self.packField(field[0], field[1])
    File "/usr/tools/lib/python2.7/site-packages/impacket/structure.py", line 110, in packField
      ans = self.pack(format, None, field = fieldName)
    File "/usr/tools/lib/python2.7/site-packages/impacket/structure.py", line 203, in pack
      return self.pack(two[0], eval(two[1], {}, fields))
    File "/usr/tools/lib/python2.7/site-packages/impacket/structure.py", line 273, in pack
      return pack(format, data)
  DeprecationWarning: ('integer argument expected, got float', "When packing field 'WordCount | B=len(Parameters)/2' in impacket.smb.SMBCommand", "When packing field 'Data | *: | [<impacket.smb.SMBCommand instance at 0x7f140e0f8f38>]' in impacket.smb.NewSMBPacket")
```

$ python --version
Python 2.7.12

Monkey patching structure.py to check type and convert it works but i thought struct.pack does converts and all.  isnt it ?

**Comment by asolino** [comment]
Thanks @contactr2m 

Can you please checkout the `python36` branch instead and test again?

**Comment by contactr2m** [comment]
> Thanks @contactr2m
> 
> Can you please checkout the `python36` branch instead and test again?
Thanks 
 https://github.com/SecureAuthCorp/impacket/commit/a5f0b62927ddb6462d3d4121dce742051324781a#diff-ce6a66d1936fa241ef5528069290daba did fix it. 
Closing the ticket
