### ISSUE TITLE
ntlmrelayx: smbclient says protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE

### ISSUE THREAD

**Issue by CaledoniaProject** [SecureAuthCorp/impacket#554]
CORP/admin is a DA account and I've successfully retrieved the hash,

```
ntlmrelayx> socks
Protocol  Target          Username    AdminStatus  Port
--------  --------------  ----------  -----------  ----
SMB       172.16.177.131  CORP/ADMIN  TRUE         445
```

In proxychains.conf I have

```
[ProxyList]
socks4 127.0.0.1 1080
```

And smbclient does not work [as described in this article](https://www.secureauth.com/blog/playing-relayed-credentials):

```
# ./proxychains4 -f test.conf smbclient //172.16.177.131/c$ -U CORP/ADMIN
[proxychains] config file found: test.conf
[proxychains] preloading ./libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
WARNING: The "syslog" option is deprecated
Enter CORP/ADMIN's password:
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  172.16.177.131:445  ...  OK
protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE
```

Direct connection with smbclient + credential works, so it's a socks proxy issue.

How should I debug this?

**Comment by asolino** [comment]
Hey @CaledoniaProject thanks for the report..

Something tells me this could be something related to different SMB Versions proxied vs the specific SMB version `smbclient` is trying to negotiate. If I remember well `smbclient` will use by default `SMBv1` and won't negotiate other versions. Or it could happen that `smbclient` is configured with `min_protocol` that doesn't match what was relayed. Or, indeed there's a bug in the SOCKS bits we will need to find out.

Can you please first use our own [smbclient.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/smbclient.py) and check if it works?

You gotta call it slightly different:
```
proxychains -f test.conf python smbclient.py CORP/ADMIN@172.16.177.131
```
put whatever password you want and then inside the prompt:
```
use c$
ls
````

let me know how it goes.

**Comment by CaledoniaProject** [comment]
Thanks for pointing out.

1. smbclient.py works fine. 
2. smbclient works if I don't remove the `-smb2support` switch
