### ISSUE TITLE
Psexec.py hangs and breaks wmiexec.py if remcom file is caught by target

### ISSUE THREAD

**Issue by lonewolf210** [SecureAuthCorp/impacket#559]
Psexec.py hangs if the remcom file being dropped to disk is caught by antivirus. This forces the user to ctrl+c to end the file to escape. If wmiexec.py is then attempted against the target it returns an access denied error for permissions. This will persist until the target has been restarted.

I tried to do some debugging but didn't have a ton of success. From what I can tell the problem seems to be that the smb connection can't be cleanly closed. Although reading through the RemCom github there was mention of the service polluting the  registry if not cleanly exited and it appears that this was never addressed in that project.

**Comment by asolino** [comment]
Can't understand the relationship between `psexec.py` / `wmiexec.py` and an AV. Can't do much w/o context.
