### ISSUE TITLE
Feature Request: ntlmrelayx accepts a list of source/destination pairs for targets

### ISSUE THREAD

**Issue by NotMedic** [SecureAuthCorp/impacket#561]
Would it be possible to add in a source/destination pair for ntlmrelayx? The idea would be that you pre-define a list of targets similar to the current tf option, however, the target will be different based on the source that authenticates against ntlmrelayx. 

an example file:
source1, target1
source1, target2
source2, target2
source3, target3
source4, target3

When ntlmrelayx receives an authentication request from source1, it will relay to target1. when it receives an authentication request for source2, it relays to target2 and so forth. If multiple destinations exist per target, it'll continue to round-robin in its current fashion between targets.

**Comment by asolino** [comment]
Hey @NotMedic 

What's the use case for this? Shouldn't it be based on the user you want to relay rather than the source machine?

**Comment by asolino** [comment]
> I chatted with dirk-jan about this as well. The use-case is that the source machine account is the account being relayed. Your idea about relaying per user account is also valid, as you could define it a machine account as a user account

Indeed. The current target specification already supports [this](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/utils/targetsutils.py#L19), but no implementation on the relay part to actual support it.

> I'm not sure you have the username early enough in the process to make a decision for the destination though.

In a twisted way yes, you can :).. It's just a lack of time to implement it ...

**Comment by dirkjanm** [comment]
> In a twisted way yes, you can :).. It's just a lack of time to implement it ...

Can you? I was always under the impression that since the username is only sent in the type3 message it is too late to decide where to relay it at that point

**Comment by asolino** [comment]
Closed as fixed in https://github.com/SecureAuthCorp/impacket/pull/767
