### ISSUE TITLE
nrlmrelayx SyntaxError

### ISSUE THREAD

**Issue by surgicalmittens** [SecureAuthCorp/impacket#563]
When I run:

`python ntlmrelayx.py -t ldap://DOMAINCONTROLLER --escalate-user USER 
`

I get the following error.

```
File “ntlmrelayx.py”, line 73
   print outputFormat.format(*header)
                    ^
SyntaxError: invalid syntax (edited) 

```
I've had this error with both the most current version from git and the 0.9.18 release. Any assistance would be appreciated.

**Comment by asolino** [comment]
Hey @surgicalmittens 

Looks like you're running `ntlmrelayx.py` using Python 3. Try running it with Python 2.x or `git pull` the [python36](https://github.com/SecureAuthCorp/impacket/tree/python36) branch (still under testing.)

**Comment by surgicalmittens** [comment]
Thanks @asolino,

Ran `git clone https://github.com/SecureAuthCorp/impacket.git -b python36`

That fixed it for me.
