### ISSUE TITLE
--add-computer causing error

### ISSUE THREAD

**Issue by redtop** [SecureAuthCorp/impacket#580]
Hi,
Trying to replicate dirkjanm's post https://dirkjanm.io/worst-of-both-worlds-ntlm-relaying-and-kerberos-delegation/
Updated version of impacket from git:

Saw this error first:
```
root@ka01  /opt/impacket/examples   master  ./ntlmrelayx.py -t ldaps://dc01.lab.local --add-computer                                               
Impacket v0.9.18-dev - Copyright 2018 SecureAuth Corporation

[*] Protocol Client SMB loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Running in relay mode to single host
Traceback (most recent call last):
  File "./ntlmrelayx.py", line 338, in <module>
    c = start_servers(options, threads)
  File "./ntlmrelayx.py", line 144, in start_servers
    c.setLDAPOptions(options.no_dump, options.no_da, options.no_acl, options.no_validate_privs, options.escalate_user, options.add_computer, options.delegate_access)
TypeError: setLDAPOptions() takes exactly 5 arguments (8 given)
```

Tried giving the 5 'no' arguments, same error:

```
root@ka01  /opt/impacket/examples   master  ./ntlmrelayx.py -t ldaps://dc01.lab.local --add-computer --no-dump --no-da --no-acl --no-validate-privs
Impacket v0.9.18-dev - Copyright 2018 SecureAuth Corporation

[*] Protocol Client SMB loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Running in relay mode to single host
Traceback (most recent call last):
  File "./ntlmrelayx.py", line 338, in <module>
    c = start_servers(options, threads)
  File "./ntlmrelayx.py", line 144, in start_servers
    c.setLDAPOptions(options.no_dump, options.no_da, options.no_acl, options.no_validate_privs, options.escalate_user, options.add_computer, options.delegate_access)
TypeError: setLDAPOptions() takes exactly 5 arguments (8 given)
```
PS thanks for all the impacket goodness over the years ;-)

**Comment by dtrizna** [comment]
I've seen the same error.
Reinstall of impacket helped.

_python setup.py install
python -m pip install -r requirements.txt_

**Comment by redtop** [comment]
Thanks for the response, working now. Happy Hacking!

**Comment by weuroi578** [comment]
I am seeing the same error despite reinstalling impacket. I do not see the error when I run the original version, only seeing this in Dirkjan's version of ntlmrelayx.

Thank you for this amazing tool!

**Comment by weuroi578** [comment]
> Hi,
> Trying to replicate dirkjanm's post https://dirkjanm.io/worst-of-both-worlds-ntlm-relaying-and-kerberos-delegation/
> Updated version of impacket from git:
> 
> Saw this error first:
> 
> ```
> root@ka01  /opt/impacket/examples   master  ./ntlmrelayx.py -t ldaps://dc01.lab.local --add-computer                                               
> Impacket v0.9.18-dev - Copyright 2018 SecureAuth Corporation
> 
> [*] Protocol Client SMB loaded..
> [*] Protocol Client SMTP loaded..
> [*] Protocol Client MSSQL loaded..
> [*] Protocol Client HTTPS loaded..
> [*] Protocol Client HTTP loaded..
> [*] Protocol Client IMAPS loaded..
> [*] Protocol Client IMAP loaded..
> [*] Protocol Client LDAPS loaded..
> [*] Protocol Client LDAP loaded..
> [*] Running in relay mode to single host
> Traceback (most recent call last):
>   File "./ntlmrelayx.py", line 338, in <module>
>     c = start_servers(options, threads)
>   File "./ntlmrelayx.py", line 144, in start_servers
>     c.setLDAPOptions(options.no_dump, options.no_da, options.no_acl, options.no_validate_privs, options.escalate_user, options.add_computer, options.delegate_access)
> TypeError: setLDAPOptions() takes exactly 5 arguments (8 given)
> ```
> 
> Tried giving the 5 'no' arguments, same error:
> 
> ```
> root@ka01  /opt/impacket/examples   master  ./ntlmrelayx.py -t ldaps://dc01.lab.local --add-computer --no-dump --no-da --no-acl --no-validate-privs
> Impacket v0.9.18-dev - Copyright 2018 SecureAuth Corporation
> 
> [*] Protocol Client SMB loaded..
> [*] Protocol Client SMTP loaded..
> [*] Protocol Client MSSQL loaded..
> [*] Protocol Client HTTPS loaded..
> [*] Protocol Client HTTP loaded..
> [*] Protocol Client IMAPS loaded..
> [*] Protocol Client IMAP loaded..
> [*] Protocol Client LDAPS loaded..
> [*] Protocol Client LDAP loaded..
> [*] Running in relay mode to single host
> Traceback (most recent call last):
>   File "./ntlmrelayx.py", line 338, in <module>
>     c = start_servers(options, threads)
>   File "./ntlmrelayx.py", line 144, in start_servers
>     c.setLDAPOptions(options.no_dump, options.no_da, options.no_acl, options.no_validate_privs, options.escalate_user, options.add_computer, options.delegate_access)
> TypeError: setLDAPOptions() takes exactly 5 arguments (8 given)
> ```
> 
> PS thanks for all the impacket goodness over the years ;-)

Please reopen this.

**Comment by asolino** [comment]
hey there

I'm seeing you using impacket 0.9.18-dev when you should be in 0.9.19-dev
in order to run this new functionality.

**Comment by squid22** [comment]
a simple git pull fixed it for me...
