### ISSUE TITLE
pip install dependency warning

### ISSUE THREAD

**Issue by SR4ven** [SecureAuthCorp/impacket#582]
When installing with `pip install impacket` the following warning comes up:
```
ldapdomaindump 0.9.1 has requirement ldap3==2.5.1, but you'll have ldap3 2.5.2 which is incompatible.
```
The installation succeeds but imports for ldap3 or ldapdomaindump fail.
This roots down to the dependencie checking of pip. See https://github.com/pypa/pip/issues/988

A temporary fix could be setting the required ldap3 version of this packet to 2.5.1

**Comment by dirkjanm** [comment]
Can confirm, ldap3 2.5.1 is currently forced in ldapdomaindump because of some critical bugs in 2.5.2 that it depends on, forcing it on 2.5.1 for impacket too should fix it in the meanwhile.

**Comment by asolino** [comment]
Thanks for the analysis folks.. merging https://github.com/SecureAuthCorp/impacket/pull/583
