### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by evilwing** [SecureAuthCorp/impacket#588]
ntlmrelayx.py -t ldaps://pentestlab-Dc.pentestlab.com -wh 192.168.123.54 --delegate-access   
[*] Protocol Client SMB loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
Exception in thread Thread-2:
...
...
File "build/bdist.macosx-10.7-x86_64/egg/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 328, in run
    self.server = self.HTTPServer((self.config.interfaceIp, httpport), self.HTTPHandler, self.config)
  File "build/bdist.macosx-10.7-x86_64/egg/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 42, in __init__
    SocketServer.TCPServer.__init__(self,server_address, RequestHandlerClass)
 return getattr(self._sock,name)(*args)
error: [Errno 48] Address already in use

**Comment by asolino** [comment]
Looks like you have another process listening in port 80 (or whatever `httpport` value is set for)
