### ISSUE TITLE
SMBConnection.isSigningRequired() may be ambiguous for SMB2/3

### ISSUE THREAD

**Issue by hantwister** [SecureAuthCorp/impacket#593]
The `SMB3` class returns `_Session["SigningRequired"]` when prompted if the remote side requires signing, but a developer may be expecting it to return `_Connection["RequireSigning"]`, especially if a session has not been properly established (e.g., if an exception is thrown near the end of `SMB3.login`).

An example of this ambiguity causing issues can be seen [here](https://github.com/byt3bl33d3r/CrackMapExec/pull/300).

If there is a meaningful distinction between a _session_ requiring signing and a _connection_ requiring signing, perhaps there could be two different accessor methods?

If there is not a meaningful distinction, perhaps the existing accessor could be made to check `_Connection["RequireSigning"]`?

**Comment by asolino** [comment]
Fixed in https://github.com/SecureAuthCorp/impacket/commit/ff6450fc88c879d1e2b580a99ec6ff6b7a8ea62b
