### ISSUE TITLE
mssqlclient.py: SSL routines, ssl_cipher_list_to_bytes, no ciphers available

### ISSUE THREAD

**Issue by nick2root** [SecureAuthCorp/impacket#595]
everytime i run this mssqlclient.py to connect MS SQL Server 2017. same error occurs. 

password true or wrong, same error occurs.

![image](https://user-images.githubusercontent.com/25618690/55332095-58ec7180-549d-11e9-93c6-ce58e50cfea0.png)

**Comment by asolino** [comment]
Hey @nick2root 

Please try with a newer impacket version to check if the problem persists. (current stable is `0.9.18`).

**Comment by nick2root** [comment]
thanks bro, in 0.9.18. there is no problem like this.
