### ISSUE TITLE
python3 compile-time issues of 0.9.19

### ISSUE THREAD

**Issue by xambroz** [SecureAuthCorp/impacket#600]
Hello,
there are a lot of python3 compile-time syntax issues with compiling the current release 0.9.19 such as: 
byte-compiling /home/rebus/rpmbuild/BUILDROOT/python-impacket-0.9.19-1.fc29.x86_64/usr/lib/python3.7/site-packages/impacket/dns.py to dns.cpython-37.pyc
  File "/usr/lib/python3.7/site-packages/impacket/dns.py", line 618
    print d
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(d)?

byte-compiling /home/rebus/rpmbuild/BUILDROOT/python-impacket-0.9.19-1.fc29.x86_64/usr/lib/python3.7/site-packages/impacket/examples/smbclient.py to smbclient.cpython-37.pyc
  File "/usr/lib/python3.7/site-packages/impacket/examples/smbclient.py", line 72
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling /home/rebus/rpmbuild/BUILDROOT/python-impacket-0.9.19-1.fc29.x86_64/usr/lib/python3.7/site-packages/impacket/examples/os_ident.py to os_ident.cpython-37.pyc
  File "/usr/lib/python3.7/site-packages/impacket/examples/os_ident.py", line 31
    return `self.value`
           ^
SyntaxError: invalid syntax

byte-compiling /home/rebus/rpmbuild/BUILDROOT/python-impacket-0.9.19-1.fc29.x86_64/usr/lib/python3.7/site-packages/impacket/dcerpc/v5/transport.py to transport.cpython-37.pyc
  File "/usr/lib/python3.7/site-packages/impacket/dcerpc/v5/transport.py", line 141
    raise RuntimeError, 'virtual function'
                      ^
SyntaxError: invalid syntax

byte-compiling /home/rebus/rpmbuild/BUILDROOT/python-impacket-0.9.19-1.fc29.x86_64/usr/lib/python3.7/site-packages/impacket/dcerpc/v5/epm.py to epm.cpython-37.pyc
  File "/usr/lib/python3.7/site-packages/impacket/dcerpc/v5/epm.py", line 1338
    if tmp_address <> '':
                    ^
SyntaxError: invalid syntax

byte-compiling /home/rebus/rpmbuild/BUILDROOT/python-impacket-0.9.19-1.fc29.x86_64/usr/lib/python3.7/site-packages/impacket/dcerpc/v5/mimilib.py to mimilib.cpython-37.pyc
  File "/usr/lib/python3.7/site-packages/impacket/dcerpc/v5/mimilib.py", line 183
    self.P = 0xFFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7EDEE386BFB5A899FA5AE9F24117C4B1FE649286651ECE65381FFFFFFFFFFFFFFFFL

                                                            ^
SyntaxError: invalid syntax

byte-compiling /home/rebus/rpmbuild/BUILDROOT/python-impacket-0.9.19-1.fc29.x86_64/usr/lib/python3.7/site-packages/impacket/dot11.py to dot11.cpython-37.pyc
  File "/usr/lib/python3.7/site-packages/impacket/dot11.py", line 470
    crcle=crc32(bytes)&0xffffffffL

Full transcript from Fedora python3 package build attached:
[python3_errors.txt](https://github.com/SecureAuthCorp/impacket/files/3044086/python3_errors.txt)

MichalAmbroz

**Comment by asolino** [comment]
Hey @xambroz 

impacket `0.9.19` does *not* support Python3. Check its [setup.py](https://github.com/SecureAuthCorp/impacket/blob/impacket_0_9_19/setup.py) definition.

Python 3.6.x support has been [merged](https://github.com/SecureAuthCorp/impacket/pull/596) into master a few days ago, and is not tagged to a version yet.
