### ISSUE TITLE
Can't find a valid stringBinding to connect

### ISSUE THREAD

**Issue by avrusanov** [SecureAuthCorp/impacket#602]
Hello!

We have issue with windows server connect. 

# wmiquery.py -debug user:password@data-w2016-iis10.srv.rcntec.com 
Impacket v0.9.19 - Copyright 2019 SecureAuth Corporation

[+] Target system is data-w2016-iis10.srv.rcntec.com and isFDQN is True
[+] StringBinding: \\\\DATA-W2016IIS10[\\PIPE\\atsvc]
[+] StringBinding: DATA-W2016IIS10[49666]
[+] StringBinding: 10.215.0.205[49666]
[+] StringBinding: \\\\DATA-W2016IIS10[\\pipe\\SessEnvPublicRpc]
[+] StringBinding chosen: None

Root of issue is inequality NetBIOS name of server (DATA-W2016IIS10) and first part of domain name (DATA-W2016-IIS10).

https://github.com/SecureAuthCorp/impacket/blob/429f97a894d35473d478cbacff5919739ae409b4/impacket/dcerpc/v5/dcomrt.py#L1256

Please fix it.

**Comment by asolino** [comment]
Hmmm...

I'm not sure what the right fix should be @avrusanov. Let me think if I can extract the NetBIOS name from the underlying SMB Connection, but I'm not sure that'd break other use cases.

Did you make WMI to work from Windows using that DNS name?

In the meantime, add DATA-W2016IIS10 to your host file and that would make it work.

Now.. where did you get this banner from?
```
Impacket v0.9.19 - Copyright 2002-2019 Core Security Technologies
```
That doesn't belong to [`0.9.19`](https://github.com/SecureAuthCorp/impacket/blob/impacket_0_9_19/impacket/version.py)

**Comment by avrusanov** [comment]
But if i use ip - all is ok

wmiquery.py -debug user:password@10.215.0.205

Impacket v0.9.19 - Copyright 2019 SecureAuth Corporation

[+] Target system is  10.215.0.205 and isFDQN is False
[+] StringBinding: \\\\DATA-W2016IIS10[\\PIPE\\atsvc]
[+] StringBinding: DATA-W2016IIS10[49666]
[+] StringBinding:  10.215.0.205[49666]
[+] StringBinding chosen: ncacn_ip_tcp: 10.215.0.205[49666]
[!] Press help for extra shell commands

Don't worry about banner - i have copied text not exactly 

issue reproduced when NetBios name is not equal first part of FQDN

**Comment by avrusanov** [comment]
Thank you for help! I think we need to change FQDN name to NetBIOS name
