### ISSUE TITLE
ValueError: _type_ 'v' not supported

### ISSUE THREAD

**Issue by no1deer** [SecureAuthCorp/impacket#604]
When running ntlmrelayx.py or mimikatz from the example directory i am receiving the following error:        

Python 2,7
➜  impacket git:(master) ✗ python examples/ntlmrelayx.py                                                                  
Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation                                                              
                                                                                                                          
[*] Protocol Client LDAP loaded..                                                                                         
[*] Protocol Client LDAPS loaded..                                                                                        
[*] Protocol Client SMB loaded..                                                                                          
[*] Protocol Client HTTPS loaded..                                                                                        
[*] Protocol Client HTTP loaded..                                                                                         
[*] Protocol Client IMAPS loaded..                                                                                        
[*] Protocol Client IMAP loaded..                                                                                         
[*] Protocol Client MSSQL loaded..                                                                                        
[*] Protocol Client SMTP loaded..                                                                                         
Traceback (most recent call last):                                                                                        
  File "examples/ntlmrelayx.py", line 294, in <module>                                                                    
    from impacket.examples.ntlmrelayx.attacks import PROTOCOL_ATTACKS                                                     
  File "/usr/local/lib/python2.7/dist-packages/impacket/examples/ntlmrelayx/attacks/__init__.py", line 57, in <module>    
    __import__(package + '.' + os.path.splitext(file)[0])                                                                 
  File "/usr/local/lib/python2.7/dist-packages/impacket/examples/ntlmrelayx/attacks/smbattack.py", line 24, in <module>   
    from impacket.examples.smbclient import MiniImpacketShell                                                             
  File "/usr/local/lib/python2.7/dist-packages/impacket/examples/smbclient.py", line 35, in <module>                      
    import pyreadline as readline                                                                                         
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/__init__.py", line 12, in <module>                              
    from . import logger, clipboard, lineeditor, modes, console                                                           
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/clipboard/__init__.py", line 13, in <module>                    
    from .win32_clipboard import GetClipboardText, SetClipboardText                                                       
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/clipboard/win32_clipboard.py", line 37, in <module>             
    import ctypes.wintypes as wintypes                                                                                    
  File "/usr/lib/python2.7/ctypes/wintypes.py", line 19, in <module>                                                      
    class VARIANT_BOOL(_SimpleCData):                                                                                     

Python 3.5
➜  impacket git:(master) ✗ python3.5 examples/ntlmrelayx.py         
Traceback (most recent call last):                                  
  File "examples/ntlmrelayx.py", line 47, in <module>               
    from impacket import version                                    
ImportError: No module named 'impacket'                             

➜  impacket git:(master) ✗ dpkg -l python-impacket                                                                                                 
Desired=Unknown/Install/Remove/Purge/Hold                                                                                                          
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend                                                                     
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)                                                                                         
||/ Name                            Version              Architecture         Description                                                          
+++-===============================-====================-====================-==================================================================== 
ii  python-impacket                 0.9.15-1             all                  Python module to easily build and dissect network protocols          

➜  impacket git:(master) ✗ lsb_release -a          
No LSB modules are available.                      
Distributor ID: Debian                             
Description:    Debian GNU/Linux 9.8 (stretch)     
Release:        9.8                                
Codename:       stretch

**Comment by asolino** [comment]
Please follow the [installation instructions](https://github.com/SecureAuthCorp/impacket#installing) and be sure to remove any previously installed impacket version.
