### ISSUE TITLE
HTTP --> LDAP

### ISSUE THREAD

**Issue by coldalfred** [SecureAuthCorp/impacket#608]
running ntlmrelayx.py i get this error trying to escale to DA from PrivExchange vulnerability

" Relaying to LDAP will not work! (This usually happens when relaying from SMB to LDAP) "

I don't know why, if is a HTTP to LDAP and not a SMB to LDAP.

i just follow the examples from here :
https://dirkjanm.io/abusing-exchange-one-api-call-away-from-domain-admin/

![ntlmrelay-exchange 1](https://user-images.githubusercontent.com/2179757/55919771-c8104700-5bbc-11e9-9de4-8362379b6bbf.png)

**Comment by asolino** [comment]
Probable the target is enforcing Signing. In any case, check the latest version (0.9.20-dev) and try again.
