### ISSUE TITLE
Secretsdump.py line 126 except Exception, e: error 

### ISSUE THREAD

**Issue by L07tB0y** [SecureAuthCorp/impacket#610]
line 126
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by asolino** [comment]
Please specify the exact line,  impacket version you're using and Python version. 

I can't find what you're pointing in our master branch.

**Comment by L07tB0y** [comment]
The latest version of the secretsdump.py
https://github.com/SecureAuthCorp/impacket/blob/master/examples/secretsdump.py

When I try to execute the script I get a syntax error on line 126 which just says else: so not entirely sure why it gives me the error as there are plenty of else: statements before this line and it accepts those. 

I am using python 3.7.0 on windows 10.

**Comment by asolino** [comment]
Hey @L07tB0y 

`Impacket 0.9.19` does *not* support Python 3.x

If you want to use Python 3.x you will need to clone / download de master branch (`0.9.20-dev`).
