### ISSUE TITLE
installed the latest version of impacket 0.9.19 getting syntax error on secretsdump.py

### ISSUE THREAD

**Issue by L07tB0y** [SecureAuthCorp/impacket#611]
getting the following error. Running Python 3.7.0 on windows 10 1809 impacket version 0.9.19

Downloaded the latest 

E:\impacket\examples>secretsdump.py
  File "E:\impacket\examples\secretsdump.py", line 126
    except Exception, e:
                    ^
SyntaxError: invalid syntax

E:\impacket\examples>PYTHON secretsdump.py
  File "secretsdump.py", line 126
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by asolino** [comment]
`Impacket 0.9.19` does *not* support Python 3.x. Please download/clone the master branch (dev version).

**Comment by L07tB0y** [comment]
i don't see a dev branch under master. Master seems to be the latest one.

**Comment by asolino** [comment]
Master *is* the dev branch (check [here](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/version.py) )

Impacket `0.9.19` is not master.. it is [tagged](https://github.com/SecureAuthCorp/impacket/tree/impacket_0_9_19) in the past
