### ISSUE TITLE
impacket dev version - Python 3.7 - Win 10 - secretsdump.py syntax error 

### ISSUE THREAD

**Issue by L07tB0y** [SecureAuthCorp/impacket#612]
E:\impacket\examples>secretsdump.py
Traceback (most recent call last):
  File "E:\impacket\examples\secretsdump.py", line 56, in <module>
    from impacket.smbconnection import SMBConnection
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\impacket\smbconnection.py", line 266
    except (smb.SessionError, smb3.SessionError), e:
                                                ^
SyntaxError: invalid syntax

**Comment by cnotin** [comment]
The version available in pip is currently 0.9.19 which is not Python3 compatible. You should install it from source or wait until the pip package is upgraded
See https://github.com/SecureAuthCorp/impacket/issues/61#issuecomment-481769266

**Comment by asolino** [comment]
Thanks for the clarification @cnotin, closing this issue.

@L07tB0y let us know if you can install master, if not we will help you.
