### ISSUE TITLE
Go to Python3.7

### ISSUE THREAD

**Issue by eamanu** [SecureAuthCorp/impacket#620]
Hello, 

I am working on the package of impacket on Debian. Impacket was package to be build on Python2. Now, I am working to package on python3. I couldn't work on it for Debian10 (:-(), so for now will be work on testing.

But now Debian 10 come with Python3.7 . So, my question is: exist some plan to port impacket to Python3.7? do you need help with that?

**Comment by asolino** [comment]
Thanks for your help @eamanu .

You can checkout our [dev](https://github.com/SecureAuthCorp/impacket) branch that already supports Python3. I mostly tested it with Python3.6 tho.
