### ISSUE TITLE
"Searching for pekList, be patient",and then nothing happen

### ISSUE THREAD

**Issue by Lz1y** [SecureAuthCorp/impacket#625]
Copy ntds.dit from windows server 2019 via vss-copy.

![image](https://user-images.githubusercontent.com/23468993/57843690-4f2a8d80-7801-11e9-9e5c-b6b8a6c40ec2.png)
![image](https://user-images.githubusercontent.com/23468993/57843700-5782c880-7801-11e9-9e89-f93b030a1a8e.png)

Using dcsync(?):
![image](https://user-images.githubusercontent.com/23468993/57844201-2a82e580-7802-11e9-9a65-cf16a57b0e81.png)

Debug info:
root@kali:~/Downloads/Ad-Pentest/impacket/examples# secretsdump.py -system SYSTEM -ntds ntds  -history -just-dc-ntlm  LOCAL -debug 
Impacket v0.9.19-dev - Copyright 2019 SecureAuth Corporation

[+] Retrieving class info for JD
[+] Unknown type 0x7
[+] Retrieving class info for Skew1
[+] Unknown type 0xa
[+] Retrieving class info for GBG
[+] Unknown type 0x2
[+] Retrieving class info for Data
[+] Unknown type 0x2
[*] Target system bootKey: 0x26a5ab97d02818127fa4762aa422b973
[+] Checking NoLMHash Policy
[+] LMHashes are NOT being stored
[+] Mounting DB...
[+] Trying to fetch page -1 (0x0)
[+] Database Version:0x620, Revision:0x14
[+] Page Size: 8192
[+] Total Pages in file: 1534
[+] Trying to fetch page 4 (0xa000)
[+] Trying to fetch page 13 (0x1c000)
[+] Trying to fetch page 14 (0x1e000)
[+] Trying to fetch page 19 (0x28000)
[+] Trying to fetch page 20 (0x2a000)
[+] Trying to fetch page 21 (0x2c000)
[+] Trying to fetch page 22 (0x2e000)
[+] Trying to fetch page 23 (0x30000)
[+] Trying to fetch page 126 (0xfe000)
[+] Trying to fetch page 151 (0x130000)
[+] Trying to fetch page 152 (0x132000)
[+] Trying to fetch page 153 (0x134000)
[+] Trying to fetch page 154 (0x136000)
[+] Trying to fetch page 157 (0x13c000)
[+] Trying to fetch page 159 (0x140000)
[+] Trying to fetch page 160 (0x142000)
[+] Trying to fetch page 158 (0x13e000)
[+] Trying to fetch page 155 (0x138000)
[+] Trying to fetch page 156 (0x13a000)
[+] Trying to fetch page 31 (0x40000)
[+] Trying to fetch page 36 (0x4a000)
[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Searching for pekList, be patient
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc590020, returning raw results
[... ]
[*] Reading and decrypting hashes from ntds 
[+] Finished processing and printing user's hashes, now printing supplemental information
[*] Cleaning up... 
root@kali:~/Downloads/Ad-Pentest/impacket/examples#

**Comment by asolino** [comment]
Hey @Lz1y 

Haven't tested `secretsdump.py` against 2019 servers. Did you experience that in other OS versions?

**Comment by Lz1y** [comment]
@asolino It seems like no problem in other versions.

**Comment by asolino** [comment]
Are you still experiencing the same problem against a 2019 server @Lz1y ?

**Comment by 0xdeaddood** [comment]
No answer, closing.
