### ISSUE TITLE
ntlmrelayx  no data

### ISSUE THREAD

**Issue by jvlavl** [SecureAuthCorp/impacket#629]
Good day,

I have a question about the tool ntlmrelayx.

I'm running it at the office that I working for to do a network investigation.
I created a list of stations that are vulnerable with CrackmapExec.

I fire-up ntlmrelayx with the following command python ntlmrelayx.py -tf list.txt -smb2support -c "ipconfig" 

As I look at samples on youtube I see hashes arriving in ntlmrelayx  but I don't retrieve any information in here. when I run Responder in the same way I do receive hashes from the network. 

When I combine the two ntlmrelayx is authenticating against the targets.
What i'm I missing to get the same info in ntlmrelayx or must I always combine the two?

Is there a config file that i'm missing? 

Please adviseGood day,

I have a question about the tool ntlmrelayx.

I'm running it at the office that I working for to do a network investigation.
I created a list of stations that are vulnerable with CrackmapExec.

I fire-up ntlmrelayx with the following command python ntlmrelayx.py -tf list.txt -smb2support -c "ipconfig" 

As I look at samples on youtube I see hashes arriving in ntlmrelayx  but I don't retrieve any information in here. when I run Responder in the same way I do receive hashes from the network. 

When I combine the two ntlmrelayx is authenticating against the targets.
What i'm I missing to get the same info in ntlmrelayx or must I always combine the two?

Is there a config file that i'm missing? 

Please advise

**Comment by dirkjanm** [comment]
You will always need to run them together as responder.py makes sure the hosts connect to you. ntlmrelayx only relays that connection to other systems. ntlmrelayx does not spoof anything by itself
