### ISSUE TITLE
Error unpacking data with SAM and SECURITY hive provided

### ISSUE THREAD

**Issue by fearthebeard2019** [SecureAuthCorp/impacket#639]
OS: Kali 
secretsdump.py -sam SAM -system SYSTEM LOCAL
Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation

[-] ("Unpacked data doesn't match constant value ''\x00\x00\x04\x00'' should be ''regf''",

Security:
head SECURITY
regf���0�D��� PemRoot\System32\Config\SECURITY}�l#hbin

Sam:
head SAM
�__SysObjectsRelmonState&�@��

**Comment by asolino** [comment]
Can't reproduce this unless you send me the hives. Re-open if you send them.

**Comment by fearthebeard2019** [comment]
@asolino .... thanks for the response, went back and processed new copies of the hives. Seems that the first transfer was corrupt. Sorry for any issues the bug post might have caused

**Comment by ALI502539** [comment]
Hi, I am having the same error I have exported the sam and system files from regedit and also from cmd using both save and export commands then I brought the sam.reg and system.reg file to Kali desktop and used the following command:
impacket-secretsdump -sam sam.reg -system system.reg 
And then he gives me the same error can someone please help??
