### ISSUE TITLE
NetBIOS does not handle highly concurrent usages due to limitation in select() and filedescriptor number

### ISSUE THREAD

**Issue by cnotin** [SecureAuthCorp/impacket#649]
The NetBIOS classes, `NetBIOS` and `NetBIOSTCPSession` use `select()` to read from their socket:
https://github.com/SecureAuthCorp/impacket/blob/2f2db662bae0919251b959d76ef42269dd522def/impacket/nmb.py#L540
https://github.com/SecureAuthCorp/impacket/blob/2f2db662bae0919251b959d76ef42269dd522def/impacket/nmb.py#L946
https://github.com/SecureAuthCorp/impacket/blob/2f2db662bae0919251b959d76ef42269dd522def/impacket/nmb.py#L978

We can find similar code in the original pysmb project:
https://github.com/miketeo/pysmb/blob/18271728f62ff9cac9372fa4c7e78fcdc249258e/python3/smb/SMBConnection.py#L596

The issue is that `select()` does not accept a file descriptor number above a certain limit (often 1024 on Linux). See also:
https://stackoverflow.com/questions/14250751/how-to-increase-filedescriptors-range-in-python-select

Therefore, in a highly concurrent situation (e.g. +1k client SMB threads) we start to get errors such as:
`filedescriptor out of range in select()`

The solution would be to use `poll()` but it is not compatible with Windows.
Should we implement something that prefers `poll()` when available but that can fall-back to `select()`?

**Comment by cnotin** [comment]
`select()` is used in `polling_read()` and `non_polling_read()` which are used interchangeably depending on the boolean `select_poll` constructor parameter:
https://github.com/SecureAuthCorp/impacket/blob/2f2db662bae0919251b959d76ef42269dd522def/impacket/nmb.py#L887-L891
https://github.com/SecureAuthCorp/impacket/blob/2f2db662bae0919251b959d76ef42269dd522def/impacket/nmb.py#L873-L874

I don't seem to find any case where a value different than the default `select_poll=False` is used.
There's maybe an occasion to simplify the code here.
We could also use a blocking mode socket with `settimeout()`

**Comment by asolino** [comment]
Nice catch @cnotin 

I'd like the idea of going for `poll` first and then fall back to `select` if needed. Do you mind giving it a shot and send a PR? We will need to test it thoroughly since this method must be in the top three of most used by the library ;).

The `polling_read()` / `non_polling_read()`is something used by our @HelpSystems friends so I'd rather not change it (AFAIR that `select_poll` is manually set by them).

**Comment by cnotin** [comment]
Thanks for your feedback!
I can suggest something, in the medium term... :)

**Comment by asolino** [comment]
Thank you @cnotin and sorry for the delay.

No worries, It'd be a great addition since the SOCKS relay could consume sockets way fast as well.

**Comment by cnotin** [comment]
Here is how to reproduce the issue.
Start an SMB server with impacket's script:
`python examples/smbserver.py test . > /dev/null`

Run the following client script to open many connections in parallel:
```python
from threading import Thread
from impacket.smbconnection import SMBConnection
from time import sleep

THREADS = 2000
cpt = 0


def worker():
    global cpt
    cpt += 1
    if cpt % 100 == 0:
        print(f"Thread {cpt}")

    try:
        smbconn = SMBConnection("127.0.0.1", "127.0.0.1")
    except ValueError as e:
        print(e.args[0])

    # sleep to keep the thread alive and file descriptor open
    while True:
        sleep(1)


print("Starting threads")
for _ in range(0, THREADS):
    t = Thread(target=worker)
    t.daemon = True
    t.start()
print("Press ENTER to quit...")
input()
print("Okay, bye!")
```

After around 1k thread, you should get errors like:
> filedescriptor out of range in select()

**Comment by cnotin** [comment]
@asolino do you have thoughts against using `socket.settimeout()`?

Here is a quick try with it. It seems to work fine in normal cases (aka no `select()` issue, even after more than 2k threads), but I haven't tested yet triggering the timeout:

- nmb.py

```python
    def non_polling_read(self, read_length, timeout):
        data = b''
        if timeout is None:
            timeout = 3600

        start_time = time.time()
        bytes_left = read_length

        while bytes_left > 0:
            received = b''
            self._sock.settimeout(timeout)
            try:
                received = self._sock.recv(bytes_left)
            except socket.error as e:
                err = e.args[0]
                if err == errno.EAGAIN or err == errno.EWOULDBLOCK:
                    raise NetBIOSTimeout
            except Exception as ex:
                raise NetBIOSError('Error occurs while reading from remote', ERRCLASS_OS, ex[0])

            if (time.time() - start_time) > timeout:
                raise NetBIOSTimeout

            if len(received) == 0:
                raise NetBIOSError('Error while reading from remote', ERRCLASS_OS, None)

            data = data + received
            bytes_left = read_length - len(data)

        return bytes(data)
```

**Comment by cnotin** [comment]
Otherwise we could use the [selectors](https://docs.python.org/3/library/selectors.html) module which automatically selects the best available function:
https://github.com/python/cpython/blob/f8dc3e85ab01e1b0345738670dcb3993da7ec436/Lib/selectors.py#L580-L582

Only disadvantage:
> New in version 3.4.
