### ISSUE TITLE
Unable to download files with WMIEXEC.py from Dropbox

### ISSUE THREAD

**Issue by benichmt1** [SecureAuthCorp/impacket#650]
Trying to copy a file from a local Windows Dropbox Folder provides the following error:

`STATUS_IO_REPARSE_TAG_NOT_HANDLED(The layered file system driver for this I/O tag did not handle it when needed.)`

To reproduce:
Impacket v0.9.17

```
get file.pdf
```

**Comment by asolino** [comment]
Hey @benichmt1 

Try using our [latest release](https://github.com/SecureAuthCorp/impacket/releases/tag/impacket_0_9_19)
