### ISSUE TITLE
caniusepython3 shows this project as one that needs to transition to Python3

### ISSUE THREAD

**Issue by ShayNehmad** [SecureAuthCorp/impacket#654]
caniusepython3 shows this project as one that needs to transition to Python3 but issue https://github.com/SecureAuthCorp/impacket/issues/61 is closed, saying that this DOES work on Python 3. 

I'm planning to migrate my project (Infection Monkey) soon, and I want to know if this project officially supports Python 3 - what am I missing?

**Comment by asolino** [comment]
Hey @ShayNehmad 

This project supports Python 3.x, although no stable version has yet been released with such support. Currently only `0.9.20-dev` supports Python 3.x . So far there hasn't been many issues reported so I will probably tag a stable version soon. In the meantime you can use the dev branch (i.e. `master`).

**Comment by ShayNehmad** [comment]
Great, thanks for the answer!
Hopefully you'll release the stable version soon ⌚🎉
