### ISSUE TITLE
ntlmrelayx SOCKS module

### ISSUE THREAD

**Issue by testbughub** [SecureAuthCorp/impacket#657]
Hi!

This may be a newbie question, but when I try to use:
python ntlmrelayx.py -rf targets.txt -smb2support
I get this error:
Traceback (most recent call last):
  File "ntlmrelayx.py", line 48, in <module>
    from impacket.examples.ntlmrelayx.servers.socksserver import SOCKS
ImportError: No module named socksserver

I've done a quick google search, but no luck there.
Any help is much appreciated!

**Comment by asolino** [comment]
Hey @testbughub 

Looks like you're running an old impacket version. You should uninstall the current version and install the [newest one](https://github.com/SecureAuthCorp/impacket/releases/tag/impacket_0_9_19) (or `master` branch).

If problem persists, reopen this ticket but include the *full* command line execution and output.

**Comment by testbughub** [comment]
Hi @asolino and thanks for replying.

I was just dumb. I didn't use python3.

**Comment by asolino** [comment]
Good to know it got solved @testbughub .. Closing
