### ISSUE TITLE
Python3 release

### ISSUE THREAD

**Issue by arossert** [SecureAuthCorp/impacket#663]
I noticed that the latest 0.9.19 version is not yet working with Pyhton3 but the master branch is.
Python2 is about to be deprecated when are you planning to make another release to support Python3 without installing the master branch?

**Comment by asolino** [comment]
Hey @arossert 

We will be publishing a `0.9.20` way before Python2 is deprecated. I just want more testing to be done with the master branch.

**Comment by rhertzog** [comment]
@asolino Do you have any ETA for the 0.9.20 release? I'm wondering if we should do a snapshot from master or if we can expect the release soon... in Kali Linux we have many other packages depending on impacket and porting them to Python 3 requires to have impacket ready first. So a release would be very much welcome if it's ready.

We're tracking this here: https://gitlab.com/kalilinux/packages/impacket/issues/1

**Comment by asolino** [comment]
Hey @rhertzog. ETA for 0.9.20 is within the next few weeks, most probably before month ends.

**Comment by xambroz** [comment]
Seems that impacket is for now kicked from Fedora 31 release for not having python 3 support.
https://bugzilla.redhat.com/show_bug.cgi?id=1738110

**Comment by asolino** [comment]
I just released [0.9.20](https://github.com/SecureAuthCorp/impacket/releases/tag/impacket_0_9_20) with Python 3.x (tested in 3.6) support. Closing.

**Comment by xambroz** [comment]
Cool - thank you
