### ISSUE TITLE
rpc_s_access_denied, very common issue with impacket scripts !

### ISSUE THREAD

**Issue by Spl0itx** [SecureAuthCorp/impacket#664]
I know there are many topics related to the same issue, I read every single post but there are no solutions fit with my problem. 

I have the same problem with wmiexec, smbexec, atexec, dcomexec,

I am testing this on my local Windows 10 pro x64

$ python /usr/share/doc/python-impacket/examples/wmiexec.py user2@192.168.31.131 "whoami"
Impacket v0.9.19 - Copyright 2019 SecureAuth Corporation

Password:
[*] SMBv3.0 dialect used
[-] rpc_s_access_denied

user2 is in administrators group

PORT     STATE SERVICE
135/tcp  open  msrpc
139/tcp  open  netbios-ssn
445/tcp  open  microsoft-ds
1539/tcp open  intellistor-lm

even with some other scripts in Impacket like services.py

user@ubuntu:~/Desktop$ python /usr/share/doc/python-impacket/examples/services.py user2@192.168.31.131 list
Impacket v0.9.19 - Copyright 2019 SecureAuth Corporation

Password:
[-] DCERPC Runtime Error: code: 0x5 - rpc_s_access_denied

Thank you all in advanced

**Comment by asolino** [comment]
Thanks for the extra clarification @awsmhacks. Closing this one since there was no answer.

**Comment by Natz-ft** [comment]
what if my Account is domain joined，I also met this situation with a normal domain user.

**Comment by nareshmail** [comment]
Your user is not have permission , so make this request with admin user. or make reg entry

**Comment by fanyibo2009** [comment]
remote UAC problem. you can try administrator user.
