### ISSUE TITLE
HTTP to SMB Relay

### ISSUE THREAD

**Issue by bypass1** [SecureAuthCorp/impacket#672]
What does this means: 'NoneType' object has no attribute 'sendAuth'?

[*] HTTPD: Received connection from 10.x.x.x, attacking target smb://10.x.x.x
[*] HTTPD: Client requested path: /
[+] Exception:
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 72, in handle_one_request
    http.server.SimpleHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 209, in do_POST
    return self.do_GET()
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 272, in do_GET
    if not self.do_ntlm_auth(token,authenticateMessage):
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 368, in do_ntlm_auth
    clientResponse, errorCode = self.client.sendAuth(token)
AttributeError: 'NoneType' object has no attribute 'sendAuth'
[-] Exception in HTTP request handler: 'NoneType' object has no attribute 'sendAuth'

**Comment by asolino** [comment]
Looks like a bug. 
Please state impacket version used and repro steps.

**Comment by bypass1** [comment]
The Version is: 
Impacket v0.9.20-dev
Python 2.7.16
pip 18.1

Package                            Version       
---------------------------------- --------------
adns-python                        1.2.1         
alembic                            1.0.0.dev0    
argcomplete                        1.8.1         
asn1crypto                         0.24.0        
atomicwrites                       1.1.5         
attrs                              18.2.0        
autobahn                           17.10.1       
Automat                            0.6.0         
Babel                              2.6.0         
backports-abc                      0.5           
backports.functools-lru-cache      1.5           
backports.shutil-get-terminal-size 1.0.0         
BBQSQL                             1.0           
bcrypt                             3.1.6         
beautifulsoup4                     4.7.1         
blinker                            1.4           
bottle                             0.12.15       
capstone                           3.0.5         
cbor                               1.0.0         
certifi                            2018.8.24     
Chameleon                          2.24          
chardet                            3.0.4         
Cheetah3                           3.1.0         
chirp                              daily-20190104
Click                              7.0           
click-plugins                      1.0.4         
colorama                           0.3.7         
configobj                          5.0.6         
configparser                       3.5.0b2       
constantly                         15.1.0        
cryptography                       2.6.1         
cssselect                          1.0.3         
cycler                             0.10.0        
Cython                             0.29.2        
decorator                          4.3.0         
deprecation                        2.0.6         
dhcpig                             0.0.0         
dicttoxml                          1.7.4         
distorm3                           3.4.1         
Django                             1.11.20       
dnslib                             0.9.7         
dnspython                          1.16.0        
docutils                           0.14          
easygui                            0.96          
EasyProcess                        0.2.5         
EditorConfig                       0.12.1        
Elixir                             0.7.1         
entrypoints                        0.3           
enum34                             1.1.6         
et-xmlfile                         1.0.1         
filedepot                          0.5.2         
filteralchemy                      0.1.0         
Flask                              1.0.2         
Flask-BabelEx                      0.9.3         
Flask-Classful                     0.14.1        
Flask-Login                        0.4.1         
Flask-Mail                         0.9.1         
Flask-Principal                    0.4.0         
Flask-Restless                     0.17.0        
Flask-Security                     3.0.0         
Flask-Session                      0.3.1         
Flask-SQLAlchemy                   2.1           
Flask-WTF                          0.14.2        
FormEncode                         1.3.0         
funcsigs                           1.0.2         
fuse-python                        0.3.1         
future                             0.16.0        
futures                            3.2.0         
fuzzywuzzy                         0.17.0        
GDAL                               2.4.0         
GeoIP                              1.3.2         
gevent                             1.3.7         
gpg                                1.12.0        
greenlet                           0.4.15        
Hackersh                           0.2.0         
halberd                            0.2.4         
html5lib                           1.0.1         
httplib2                           0.11.3        
hupper                             1.5           
hyperlink                          17.3.1        
idna                               2.6           
impacket                           0.9.20.dev0   
incremental                        16.10.1       
ipaddress                          1.0.17        
IPy                                0.83          
ipython                            5.8.0         
ipython-genutils                   0.2.0         
itsdangerous                       0.24          
jdcal                              1.0           
Jinja2                             2.10          
jsbeautifier                       1.6.4         
jsonpickle                         0.9.5         
jsonrpclib                         0.1.7         
keepnote                           0.7.8         
keyring                            17.1.1        
keyrings.alt                       3.1.1         
killerbee                          1.0           
kiwisolver                         1.0.1         
ldap3                              2.5.1         
ldapdomaindump                     0.9.1         
lxkeymap                           0.1           
lxml                               4.3.2         
lz4                                1.1.0         
M2Crypto                           0.31.0        
Mako                               1.0.7         
MarkupSafe                         1.1.0         
marshmallow                        3.0.0b3       
marshmallow-sqlalchemy             0.14.1        
mate-menu                          18.4.3        
matplotlib                         2.2.3         
mechanize                          0.2.5         
mercurial                          4.8.2         
metaconfig                         0.1.4a1       
mimerender                         0.6.0         
mock                               2.0.0         
mockito                            0.5.2         
more-itertools                     4.2.0         
msgpack                            0.5.6         
mysqlclient                        1.3.10        
netaddr                            0.7.19        
networkx                           2.2           
NfSpy                              1.0           
nose                               1.3.7         
nplusone                           1.0.0         
numpy                              1.16.2        
olefile                            0.46          
openpyxl                           2.4.9         
packaging                          19.0          
paramiko                           2.4.2         
passlib                            1.7.1         
Paste                              3.0.6         
PasteDeploy                        2.0.1         
PasteScript                        2.0.2         
pathlib2                           2.3.3         
pbkdf2                             1.3           
pbr                                4.2.0         
pcapy                              0.10.8        
peepdf                             0.4.2         
pefile                             2018.8.8      
pexpect                            4.6.0         
pickleshare                        0.7.5         
Pillow                             5.4.1         
pip                                18.1          
plaster                            1.0           
plaster-pastedeploy                0.5           
pluggy                             0.8.0         
prettytable                        0.7.2         
prompt-toolkit                     1.0.15        
psycopg2                           2.7.7         
py                                 1.7.0         
py-ubjson                          0.12.0        
pyasn1                             0.4.2         
pyasn1-modules                     0.2.1         
pycairo                            1.16.2        
pycrypto                           2.6.1         
pycryptodomex                      3.6.1         
pycurl                             7.43.0.2      
pydns                              2.3.6         
pydot                              1.4.1         
pyenchant                          2.0.0         
Pygments                           2.3.1         
PyGObject                          3.30.4        
pygraphviz                         1.5           
pyinotify                          0.9.6         
pylibemu                           0.3.3         
pymongo                            3.7.1         
pymssql                            2.1.4         
PyNaCl                             1.3.0         
PyOpenGL                           3.1.0         
pyOpenSSL                          19.0.0        
pyparsing                          2.2.0         
PyPDF2                             1.26.0        
pyquery                            1.2.9         
pyramid                            1.10.2        
PyRIC                              0.1.6         
pyrit                              0.5.1         
pyrtlsdr                           0.2.9         
pyscard                            1.9.7         
pyserial                           3.4           
PySide                             1.2.2         
PySocks                            1.6.8         
pysqlite                           2.7.0         
pytesseract                        0.2.5         
pytest                             3.10.1        
python-dateutil                    2.7.3         
python-editor                      1.0.3         
python-Levenshtein                 0.12.0        
python-magic                       0.4.16        
python-mimeparse                   0.1.4         
python-openid                      2.2.5         
python-slugify                     2.0.1         
python-snappy                      0.5.3         
python-xlib                        0.23          
pythonaes                          1.0           
Pythonect                          0.6.0         
PyTrie                             0.2           
pytz                               2019.1        
pyusb                              1.0.2         
PyV8                               1.0.dev0      
PyVirtualDisplay                   0.2.1         
pyxdg                              0.25          
PyYAML                             3.13          
pyzmq                              17.1.2        
qrcode                             6.1           
qt4reactor                         1.0           
repoze.lru                         0.7           
requests                           2.21.0        
rfcat                              1.0           
rfidiot                            1.0           
roguehostapd                       1.2.3         
roman                              2.0.0         
rsa                                4.0           
rtlsdr-scanner                     1.3.1         
scandir                            1.9.0         
scapy                              2.4.0         
scgi                               1.13          
SecretStorage                      2.3.1         
selenium                           3.14.1        
service-identity                   16.0.0        
setproctitle                       1.1.10        
setuptools                         40.8.0        
shodan                             1.11.1        
simplegeneric                      0.8.1         
simplejson                         3.16.0        
singledispatch                     3.4.0.3       
sipvicious                         0.2.8         
six                                1.12.0        
slowaes                            0.1a1         
soupsieve                          1.8           
speaklater                         1.3           
specan                             0.0.0         
SQLAlchemy                         1.2.18        
sqlalchemy-schemadisplay           1.3           
sqlparse                           0.2.4         
subprocess32                       3.5.3         
tcpwatch                           1.3.1         
Tempita                            0.5.2         
tornado                            5.1.1         
tqdm                               4.28.1        
traitlets                          4.3.2         
translationstring                  1.3           
trollius                           2.0.1         
Twisted                            18.9.0        
txaio                              2.10.0        
typing                             3.6.6         
u-msgpack-python                   2.1           
unicodecsv                         0.14.1        
Unidecode                          1.0.23        
urllib3                            1.24.1        
uTidylib                           0.5           
venusian                           1.2.0         
vinetto                            0.7b0         
visvis                             1.11.1        
volatility                         2.6           
waitress                           1.2.0b2       
wapiti3                            3.0.1         
wcwidth                            0.1.7         
webargs                            5.1.2         
webencodings                       0.5.1         
WebOb                              1.8.5         
websocket-client                   0.53.0        
WebTest                            2.0.32        
webunit                            1.3.10        
Werkzeug                           0.14.1        
wheel                              0.32.3        
Whoosh                             2.7.4         
wifiphisher                        1.4           
wifite                             2.2.5         
wsaccel                            0.6.2         
WTForms                            2.2.1         
wxPython                           3.0.2.0       
wxPython-common                    3.0.2.0       
XlsxWriter                         1.1.2         
xmlbuilder                         1.0           
yara-python                        3.9.0         
zenmap                             7.70          
zope.component                     4.3.0         
zope.deprecation                   4.4.0         
zope.event                         4.2.0         
zope.hookable                      4.0.4         
zope.interface                     4.3.2

4.19.0-parrot4-28t-amd64
Distributor ID:	Parrot
Description:	Parrot GNU/Linux 4.6
Release:	4.6
Codename:	n/a

---------------------------

this bug(?) only appears for 1 host in my network. with other hosts and the same command it works.
i though his host do not expose his hash but with running responder i can see the hash.

**Comment by bypass1** [comment]
are more information require? if so, which one?

**Comment by asolino** [comment]
can you `git pull` and retest please?

**Comment by asolino** [comment]
Closing as fixed
