### ISSUE TITLE
Feature Request - raiseChild.py RID flag

### ISSUE THREAD

**Issue by mubix** [SecureAuthCorp/impacket#678]
Being able to specify a specific RID/SID to dump automatically instead of the default 500 would be nice in situations where a user might want to pull a different account.

**Comment by 0xdeaddood** [comment]
Hey @mubix! I created a PR with this feature -> #725. It was merged some days ago. Were you able to test it?

**Comment by asolino** [comment]
Closing. Fixed in https://github.com/SecureAuthCorp/impacket/pull/725
