### ISSUE TITLE
 global name 'DES' is not defined

### ISSUE THREAD

**Issue by jagdishmohite** [SecureAuthCorp/impacket#681]
Hello,
I updated Impacket, and while using mssqlclient.py,  I get below

mssqlclient.py -p 1433 reporting@querier.htb -windows-auth
Impacket v0.9.21-dev - Copyright 2019 SecureAuth Corporation

Password:
[*] Encryption required, switching to TLS
[-] global name 'DES' is not defined

not sure what is wrong?

**Comment by jagdishmohite** [comment]
I think we should close this issue , after uninstalling and fresh install of impacket solved my issue

**Comment by 404nofound2333** [comment]
thank u.the same one in HTB

**Comment by NeKroFR** [comment]
> I think we should close this issue , after uninstalling and fresh install of impacket (pip install --ignore-installed six) solved my issue

no, because it helped me and will help others
