### ISSUE TITLE
Help with NTLMRelayx and SMB to SMB relay

### ISSUE THREAD

**Issue by kimoppalfens** [SecureAuthCorp/impacket#685]
I have a setup where I can connect to a machine running ntlmrelayx.py using HTTP and have the credentials relayed just fine.

Using the exact same machines, fails when the connection is initiated over SMB.
[*] SMBD-Thread-150: Received connection from 172.30.20.40, attacking target smb://172.30.10.139
[-] Authenticating against smb://172.30.1.139 as Domain\administrator FAILED

**Comment by asolino** [comment]
Hey @kimoppalfens 

Please `git pull` and retest. Should be fixed now.

**Comment by kimoppalfens** [comment]
Still the same for me.

**Comment by asolino** [comment]
If you run `ntlmrelayx.py` with the `--remove-mic` switch, Does it work?

**Comment by kimoppalfens** [comment]
> If you run `ntlmrelayx.py` with the `--remove-mic` switch, Does it work?

That did the trick. Should've caught that when looking at the changes. 
Thanks for the help.

**Comment by asolino** [comment]
Ok..

Still, looks like you didn't commit / use the latest change. It should work w/o the `--remove-mic` switch. Previously it only worked with the `--remove-mic` switch. That's why I asked ;)

**Comment by asolino** [comment]
Closing as fixed
