### ISSUE TITLE
Windows Server 2016 DCSync issues

### ISSUE THREAD

**Issue by ltdenard** [SecureAuthCorp/impacket#687]
On 2016, it doesn't give me anything, but this:

python secretsdump.py -just-dc-ntlm -user-status -pwd-last-set -outputfile hashes.tmp svc-test:passwordhere@192.168.100.100
Impacket v0.9.21-dev - Copyright 2019 SecureAuth Corporation

[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Cleaning up...
 
It's windows server 2016 standard with the latest patches. Anything else you want to know, I'll try to answer about my setup. Anyone else having this same issue?

**Comment by awsmhacks** [comment]
Just tried this on a server2016 and it worked. 
Can you provide the full output of adding -debug right after secretsdump.py?   
 
 `secretsdump.py -debug -just-dc-ntlm -user-status -pwd-last-set -outputfile hashes.tmp svc-test:passwordhere@192.168.100.100`  
  
also, using python 2 | 3?

**Comment by ltdenard** [comment]
So first off, this was an installation error by me, but I do appreciate the response and appreciate the work put into this python module.

Somehow, I had 0.9.16 and 0.9.20 installed at the same time which was causing issues with me testing the new version to see if I fixed the issues I was having with 0.9.16. The 0.9.16 version was really interesting when you try to do a DCsync though. You could start a DCsync and then about 30 seconds to a minute in, it would cause the domain controller to give you a one minute warning and then reboot. You could basically cause a DoS. I see it's no longer a release or never made it to a release. Is this way?

**Comment by ltdenard** [comment]
Also, I can still cause a domain controller with a large active directory database to reboot even with the 0.9.20 version about minute into a DCsync. It runs and starts printing out the hashes and the gives the following once the 1 minute warning expires and causes it to reboot. I'll try to see if I can get a debug log the next time, but since this is a production domain, I have limit my runs of this.

[-] DRSR SessionError: code: 0x20fa - ERROR_DS_DRA_INTERNAL_ERROR - The replication system encountered an internal error.
[*] Something wen't wrong with the DRSUAPI approach. Try again with -use-vss parameter
[*] Cleaning up...

**Comment by awsmhacks** [comment]
I have heard of an issue like this if the DC has less memory available then the size of the ntds.dit file. 

I know metasploit implemented a sort of 'paging' to keep memory usage low and pipes back ~20 accounts at a time, I'm not sure if thats the same as how impacket is trying.  [reference](https://blog.rapid7.com/2015/07/01/safely-dumping-domain-hashes-with-meterpreter/)
  
Would be interesting to see if post/windows/gather/credentials/domain_hashdump  in metasploit gives you the same DoS result.   

There's also been a reported disconnect occurring https://github.com/SecureAuthCorp/impacket/issues/682 but it doesnt look to be the same issue.

**Comment by asolino** [comment]
Closing.
