### ISSUE TITLE
Change computer name in --add-computer 

### ISSUE THREAD

**Issue by ghost** [SecureAuthCorp/impacket#695]
Hi there - not an issue per se, just wondered where exactly we could change the name of the newly created computer account, when using --add-computer. If this is arbitrarily chosen and can be changed to something closer to the target hosts naming convention, then it could blend in better and go unnoticed.

**Comment by awsmhacks** [comment]
I think how it works currently you would have to edit https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/attacks/ldapattack.py#L90   
and rebuild.  
  
Its a good idea for an enhancement/feature-request and probably wouldn't be too difficult to implement.

**Comment by rkovaci** [comment]
cool, thank you for your help.

**Comment by asolino** [comment]
Closing, solved in https://github.com/SecureAuthCorp/impacket/pull/696
