### ISSUE TITLE
bash: pip: command not found

### ISSUE THREAD

**Issue by Mweo-Bruce** [SecureAuthCorp/impacket#701]
I'm unable to install the source execute. Using Linux debian. Need help.
Thanks...

**Comment by Unitiser** [comment]
You should try to install pip.

**Comment by asolino** [comment]
Or try running `python setup.py install`. Open an issue if you have problems with it. Closing.

**Comment by Sensilis** [comment]
asolino thanks man I was having the same issue and your comment really helped
