### ISSUE TITLE
ValueError('`digestmod` is required.') in Pytthon3.8

### ISSUE THREAD

**Issue by Unitiser** [SecureAuthCorp/impacket#702]
According to my research, `hmac.py` was updated in python3.8 and requires the `digestmod` to be set explicitly. This issue has been addressed in `ldap3` 2.6.0.

https://github.com/cannatag/ldap3/blob/master/_changelog.txt

On my machine I forced updated that version and it seamed to fix the issue.

Edit : 
Today, I did a bit more digging. I was still getting the error from `ntlm.py`. I identified occurrences of `hmac` without explicit `digestmod` in the following files : 

```
./impacket/ntlm.py
./impacket/dcerpc/v5/nrpc.py
./impacket/examples/secretsdump.py
```

**Comment by asolino** [comment]
Hey @Unitiser 

Haven't tested  `impacket` with `3.8`. Would you mind issuing a PR to address this?

**Comment by slasyz** [comment]
Hllo @asolino 

I created a PR, could you please check it?

**Comment by Unitiser** [comment]
Awesome @slasyz, 

Thanks for doing this, I was planning on working on this issue this weekend but you beat me to it! From what I can tell, the only thing missing is the ldap3 version bump.

**Comment by slasyz** [comment]
Thank you, @Unitiser

I think that an extended testing should be performed (including updating ldap3 dependency and testing its usage) to guarantee full Python 3.8 compatibility.

**Comment by asolino** [comment]
Fixed in https://github.com/SecureAuthCorp/impacket/pull/711
