### ISSUE TITLE
secretsdump fails to get SAM hashes on Windows Server 2019

### ISSUE THREAD

**Issue by NEXUS2345** [SecureAuthCorp/impacket#710]
I'm working on updating the tool keimpx and ran into an issue when dealing with secretsdump when testing against Windows Server 2019. Here is the stack trace:
```
Traceback (most recent call last):
  File "/home/consultant/tools/scanning/keimpx-dev/keimpx/lib/secretsdump.py", line 429, in dumpSAM
    encNTHash = SAM_HASH_AES(V[userAccount['NTHashOffset']:][:userAccount['NTHashLength']])
  File "/home/consultant/tools/scanning/keimpx-dev/keimpx/lib/python2.7/site-packages/impacket/structure.py", line 84, in __init__
    self.fromString(data)
  File "/home/consultant/tools/scanning/keimpx-dev/keimpx/lib/python2.7/site-packages/impacket/structure.py", line 149, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/home/consultant/tools/scanning/keimpx-dev/keimpx/lib/python2.7/site-packages/impacket/structure.py", line 321, in unpack
    return self.unpack(two[0],data)
  File "/home/consultant/tools/scanning/keimpx-dev/keimpx/lib/python2.7/site-packages/impacket/structure.py", line 380, in unpack
    return unpack(format, data)[0]
error: ('unpack requires a string argument of length 2', "When unpacking field 'PekID | <H=0 | ''[:2]'")
```

I thought it might be something in my code, but after comparing it to your examples from which the code is based on, they are basically identical. I then decided to test your example against the same server and got this output:
```
[+] Service RemoteRegistry is already running
[+] Retrieving class info for JD
[+] Retrieving class info for Skew1
[+] Retrieving class info for GBG
[+] Retrieving class info for Data
[*] Target system bootKey: REDACTED
[+] Checking NoLMHash Policy
[+] LMHashes are NOT being stored
[+] Saving remote SAM database
[*] Dumping local SAM hashes (uid:rid:lmhash:nthash)
[+] Calculating HashedBootKey from SAM
[+] NewStyle hashes is: True
Administrator:500:REDACTED:REDACTED:::
[+] NewStyle hashes is: True
Guest:501:REDACTED:REDACTED:::
[+] NewStyle hashes is: True
DefaultAccount:503:REDACTED:REDACTED:::
[-] SAM hashes extraction failed: string index out of range
```

The issues here sound similar, but I can't be sure if they are identical or not. Both were tested on Python 2.7.17, one with Impacket 0.9.20 from pypi and the other (the latter) direct from source on this repo. The source for my updates to keimpx is located here: https://github.com/NEXUS2345/keimpx/tree/impacket-0.9.20

Any help/insight is much appreciated.

**Comment by asolino** [comment]
Thanks for the feedback @NEXUS2345. Looks like there's something going on with offline extraction and Server 2019. I haven't tested it yet so, if you want to do some research on where the problem might be that'd be of lot of help.

I'd start trying to understand where that `string index out of range` exception is happening.

**Comment by NEXUS2345** [comment]
It appears that the issue may have something to do with Windows Defender Application Guard. WDAG creates an account called WDAGUtilityAccount, which when doing my testing I found to be the account that the SAM dump was failing on. This account is disabled until WDAG is enabled, and using the command `net users` on the doman controller does not reveal the accounts existence, so this may be the cause of the issues.

**Comment by asolino** [comment]
Closed as fixed in https://github.com/SecureAuthCorp/impacket/pull/802
