### ISSUE TITLE
lookupsid.py - digestmod is required

### ISSUE THREAD

**Issue by Reelix** [SecureAuthCorp/impacket#717]
Python: 3.8.0
Impacket: v0.9.20

Syntax: python lookupsid.py 'user:pass'@{iphere}

lookupsid.py fails on line 79 - https://github.com/SecureAuthCorp/impacket/blob/master/examples/lookupsid.py#L79 - With the error
```
[*] Brute forcing SIDs at {iphere}
[*] StringBinding ncacn_np:{iphere}[\pipe\lsarpc]
[-] `digestmod` is required.
```

**Comment by awsmhacks** [comment]
I believe this was fixed in a recent PR, same issue as https://github.com/SecureAuthCorp/impacket/issues/702  
  
Could you pull down the latest, v0.9.21-dev and try again?

**Comment by asolino** [comment]
No answer, closing

**Comment by noraj** [comment]
@asolino When will v0.9.21 be released ?

**Comment by noraj** [comment]
With latest (0056b61ca52e13acf05d101518976980f1592d85) git version (master branch)

```
python examples/GetUserSPNs.py domain/user
Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation

[-] Missing required parameter 'digestmod'.
```

**Comment by asolino** [comment]
`0.9.21-dev` is `master` until a new release is tagged. Check [here](https://github.com/SecureAuthCorp/impacket/blob/master/setup.py#L13)
