### ISSUE TITLE
Feature Request - raiseChild.py target IPs

### ISSUE THREAD

**Issue by mubix** [SecureAuthCorp/impacket#726]
It would be nice to have target IPs for the child DC and forest/parent DC so that it can easily be tunneled

**Comment by mubix** [comment]
This turned out to be due to an odd situation where uppercase and lowercase mattered to a DNS server that was being resolved

**Comment by mubix** [comment]
If you happen upon this issue where you are using proxychains, you can edit the `/usr/lib/proxychains3/proxyresolv` file (just a bash script)
The file usually looks like this:
```
#!/bin/sh
# This script is called by proxychains to resolve DNS names

# DNS server used to resolve names
DNS_SERVER=${PROXYRESOLV_DNS:-4.2.2.2}


if [ $# = 0 ] ; then
        echo "  usage:"
        echo "          proxyresolv <hostname> "
        exit
fi

export LD_PRELOAD=libproxychains.so.3
dig $1 @$DNS_SERVER +tcp | awk '/A.+[0-9]+\.[0-9]+\.[0-9]/{print $5;}'
```
Just change the `dig` line and add the `TEST` line before it to look like this:
```
#!/bin/sh
# This script is called by proxychains to resolve DNS names

# DNS server used to resolve names
DNS_SERVER=${PROXYRESOLV_DNS:-4.2.2.2}


if [ $# = 0 ] ; then
        echo "  usage:"
        echo "          proxyresolv <hostname> "
        exit
fi

TEST=$(echo $1 | awk '{print tolower($1)}')

export LD_PRELOAD=libproxychains.so.3
dig $TEST @$DNS_SERVER +tcp | awk '/A.+[0-9]+\.[0-9]+\.[0-9]/{print $5;}'
```

This will lowercase all resolution and should fix the issue.

**Comment by asolino** [comment]
Thanks for the detailed explanation!
