### ISSUE TITLE
Error when Getting TGT (GetNPUsers.com)

### ISSUE THREAD

**Issue by JohnEarle** [SecureAuthCorp/impacket#733]
I Receiving the following error after Getting TGT
[*] Getting TGT for *******
[-] <ConstraintsIntersection object at 0xb7555f2c consts <ConstraintsUnion object at 0xb7555dac consts <SingleValueConstraint object at 0xb7555d6c consts 10>, <SingleValueConstraint object at 0xb7555d8c consts 12>>> failed at: ValueConstraintError('<ConstraintsUnion object at 0xb7555dac consts <SingleValueConstraint object at 0xb7555d6c consts 10>, <SingleValueConstraint object at 0xb7555d8c consts 12>> failed at: ValueConstraintError(\'all of (<SingleValueConstraint object at 0xb7555d6c consts 10>, <SingleValueConstraint object at 0xb7555d8c consts 12>) failed for "11"\',)',) at Integer

**Comment by asolino** [comment]
Can't reproduce this issue. Please re-open with full details on how to repro.
