### ISSUE TITLE
Loosen requirement on ldap3 version

### ISSUE THREAD

**Issue by exploide** [SecureAuthCorp/impacket#742]
It seems impacket inherited the requirement on the ldap3 dependency from ldapdomaindump. Hence it is pinned to `ldap3==2.5.1`.

This causes conflicts in some package managers which already contain newer versions.

Since ldap3 v2.6.1 contains fixes for the compatibility issues and the recently published ldapdomaindump v0.6.2 is fine with modern ldap3 versions again, I propose to also loosen the requirements here for impacket.

**Comment by dirkjanm** [comment]
Yes the version in impacket can also be bumped to 2.6.1 or copied from ldapdomaindump which allows both 2.5.1 and 2.6.1 or newer (but not breaking versions in between those). @agsolino is this something you could fix or would you like a PR?

**Comment by asolino** [comment]
Hey folks:

Just pushed these changes, please double check if everything's working accordingly. If so, let's close this issue.

**Comment by asolino** [comment]
Closing. Re-open if you experience any issue.
