### ISSUE TITLE
smbclient.py no support for raw commands or mass download

### ISSUE THREAD

**Issue by Greenwolf** [SecureAuthCorp/impacket#751]
### Configuration  
impacket version:  Impacket v0.9.21-dev
Python version:  2.7.16+
Target OS:  Windows 7

### Debug Output With Command String  
Recursive download with smbclient: https://superuser.com/questions/856617/how-do-i-recursively-download-a-directory-using-smbclient
```
mask ""
recurse ON
prompt OFF
cd 'path\to\remote\dir'
lcd '~/path/to/download/to/'
mget *
```
Commands are not accepted.

### Additional context  
In smbclient.py, there seems to be no obvious option to recursively download files, making it problematic to use on large numbers of files on large shares. There also appears to be no reference to it in the documentation. 

Does this option exist and is undocumented? Or has it not been implemented? The raw commands which should allow this in smbclient are listed above. I was recently on a test where both smbclient and pth-smbclient were failing, while smbclient.py was working, but it was difficult to download the data needed due to only being able to 'get' on single files, * wildcard was tried but found not to work.

**Comment by jimmio** [comment]
+1 to adding this functionality

**Comment by 0xdeaddood** [comment]
Added in #1095. Closing.
