### ISSUE TITLE
Pipe not ready, aborting

### ISSUE THREAD

**Issue by rafaelgov95** [SecureAuthCorp/impacket#753]
### Configuration  
impacket version:  v0.9.20
Python version:  3.7 and 2.7
Target OS:  Windows 10
psexec.py -debug rafael.viana@172.23.64.74
Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation

Password:
[+] StringBinding ncacn_np:172.23.64.74[\pipe\svcctl]
[*] Requesting shares on 172.23.64.74.....
[*] Found writable share ADMIN$
[*] Uploading file MPaaQMYz.exe
[*] Opening SVCManager on 172.23.64.74.....
[*] Creating service NtYm on 172.23.64.74.....
[*] Starting service NtYm.....
Traceback (most recent call last):
  File "/home/rafael/.local/bin/psexec.py", line 156, in doStuff
    fid_main = self.openPipe(s,tid,r'\RemCom_communicaton',0x12019f)
  File "/home/rafael/.local/bin/psexec.py", line 106, in openPipe
    raise Exception('Pipe not ready, aborting')
Exception: Pipe not ready, aborting
[+] Pipe not ready, aborting
[*] Opening SVCManager on 172.23.64.74.....
[*] Stopping service NtYm.....
[*] Removing service NtYm.....
[*] Removing file MPaaQMYz.exe.....
[-] Error performing the uninstallation, cleaning up

**Comment by asolino** [comment]
That's most probably an AV catching the executable file. Did you try `wmiexec.py`?

**Comment by rafaelgov95** [comment]
Password:
[*] SMBv3.0 dialect used
[+] Target system is 142.23.64.74 and isFDQN is False
[+] StringBinding: \\\\XXX-22222[\\pipe\\SessEnvPublicRpc]
[+] StringBinding: XXX-22222-156586[49666]
[+] StringBinding: 10.0.75.1[49666]
[+] StringBinding: 172.17.129.145[49666]
[+] StringBinding: 172.23.64.74[49666]
[+] StringBinding chosen: ncacn_ip_tcp:172.23.64.74[49666]

forever not stop! Help previously worked

**Comment by rafaelgov95** [comment]
it was like you said, kaspersky catching the executable fiel!

**Comment by asolino** [comment]
Thanks for checking @rafaelgov95 . Closing this issue.
