### ISSUE TITLE
Parsing NDRUniConformantArray

### ISSUE THREAD

**Issue by Gilks** [SecureAuthCorp/impacket#755]
I'm looking at reading event logs remotely. The test cases use the following code, which perfectly retrieves the event log from your target.

```
request = even.ElfrReadELW()
request['LogHandle'] = resp['LogHandle']
request['ReadFlags'] = even.EVENTLOG_SEQUENTIAL_READ | even.EVENTLOG_FORWARDS_READ
request['RecordOffset'] = 0
request['NumberOfBytesToRead'] = even.MAX_BATCH_BUFF
resp = dce.request(request)
```

Then when you perform a `resp.dump()` you will see the raw NDRUniConformantArray printed to the screen. The information that is returned needs to be parsed in order to make use of it.

Is there a way to parse NDRUniConformantArray's in impacket? If so, is there an example somewhere in the code base? I've been looking around but can't seem to find any examples.

**Comment by asolino** [comment]
Hey @Gilks 

Not sure what you're asking but yes, the information needs to be parsed. First off, you need to join the array into an array of bytes:
```Python
events = b''.join(resp['Buffer'])
from impacket.structure import hexdump
hexdump(events)
```
and then parse it according to the the [EVENTLOGRECORD](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-even/541de33d-cee4-4c16-976c-e1e2ea152e65) structure.

That structure is defined in the [even.py](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/dcerpc/v5/even.py#L86) file but it's not functional. You're more than welcome to implement it so records can be parsed ;)

Hope this helps.

**Comment by Gilks** [comment]
That's exactly what I was looking for. Thanks for the insight!
