### ISSUE TITLE
ValueError: chr() arg not in range(256)

### ISSUE THREAD

**Issue by Onefivefournine** [SecureAuthCorp/impacket#759]
### Configuration  
impacket version:  0.9.21.dev0
Python version:  2.7.17
Target OS:  Ubuntu 18.04

### Debug Output With Command String  
./secretsdump.py -debug -just-dc-ntlm domain/user:password@127.0.0.1  
```
[+] Entering NTDSHashes.__decryptHash
[+] ValueError exception on [67, 78, 61, 208, 159, 208, 190, 208, 187, 209, 140, 208, 183, 208, 190, 208, 178, 208, 176, 209, 130, 208, 181, 208, 187, 209, 140, 44, 79, 85, 61, 208, 146, 208, 189, 208, 181, 209, 136, 208, 189, 208, 184, 208, 181, 32, 208, 191, 208, 190, 208, 187, 209, 140, 208, 183, 208, 190, 208, 178, 208, 176, 209, 130, 208, 181, 208, 187, 208, 184, 44, 79, 85, 61, 208, 154, 208, 190, 208, 188, 208, 191, 208, 176, 208, 189, 208, 184, 209, 143, 44, 68, 67, 61, 100, 111, 109, 97, 105, 110, 44, 68, 67, 61, 104, 111, 115, 116, 44, 68, 67, 61, 99, 111, 109]
[+] Switching to unichr()
[-] Error while processing user!
[+] Exception
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/impacket/examples/secretsdump.py", line 2489, in dump
    hashesOutputFile)
  File "/home/user/.local/lib/python2.7/site-packages/impacket/examples/secretsdump.py", line 2167, in __decryptHash
    LOG.debug('Decrypting hash for user: %s' % record['pmsgOut'][replyVersion]['pNC']['StringName'][:-1])
  File "/home/user/.local/lib/python2.7/site-packages/impacket/dcerpc/v5/ndr.py", line 136, in __getitem__
    return self.fields[key]['Data']
  File "/home/user/.local/lib/python2.7/site-packages/impacket/dcerpc/v5/drsuapi.py", line 616, in __getitem__
    return ''.join([chr(i) for i in self.fields[key]])
ValueError: chr() arg not in range(256)
[-] chr() arg not in range(256)
```

### Additional context  
When dumping non-latin characters parser should switch to `unichr` instead of `chr`, but there is the same return statement as in `try` scope:
`impacket/dcerpc/v5/drsuapi.py` lines 611 through 616:
```python
try:
    return ''.join([chr(i) for i in self.fields[key]])
except ValueError:
    # We might have Unicode chars in here, let's use unichr instead
    LOG.debug('ValueError exception on %s' % self.fields[key])
    LOG.debug('Switching to unichr()')
    return ''.join([chr(i) for i in self.fields[key]])
```

Replace `chr` to `unichr` at line 616 and all works fine!

**Comment by asolino** [comment]
Thanks for bringing up this issue @Onefivefournine. 

Your fix makes sense for Python 2.x world.. as you tested. Do you have Python 3.x available? Can you run the same test (unpatched version as it is now) and tell me if the output works well? .. I think I'll need to add an exception just for Python 2.x use case.

**Comment by Onefivefournine** [comment]
When using Python 3.6.9 I get this weird exception, which is not related to `drsuapi.py`:
```
Traceback (most recent call last):
  File "./secretsdump.py", line 334, in <module>
    logger.init(options.ts)
TypeError: init() takes 0 positional arguments but 1 was given
```

**Comment by asolino** [comment]
You don't have the latest `impacket` version installed @Onefivefournine .  `logger.init` was changed in [this](https://github.com/SecureAuthCorp/impacket/commit/5a0edb3a36a5c7a5b5c12c1e545de70f2e101bcb#diff-caeb4f558148cc3d4725b39df2503589) commit. Please `git pull`, install and restest

**Comment by 0xdeaddood** [comment]
Hey folks! The change suggested by @Onefivefournine works well in Python 2.x and Python 3.x. 

The current try/except block can be used to handle the dumping. By default the script will try to use `chr()`, and in case of error (running Python 2.x) It will use ` unichr() `

**Comment by 0xdeaddood** [comment]
Hi @Onefivefournine, the Unicode issue was solved in [this](https://github.com/SecureAuthCorp/impacket/commit/e5e676d7db3ac6fe19212184b1fa61554c2d04ac) commit. Please `git pull`, install and check it.

**Comment by asolino** [comment]
No answer, closing
