### ISSUE TITLE
Version information is often ambiguous/un-updated

### ISSUE THREAD

**Issue by jsherwood0** [SecureAuthCorp/impacket#760]
### Configuration  
impacket version:  v0.9.21-dev
Python version:  v2.7.16+ and v3.7.4
Target OS:  Kali Linux x64 2019.3

### Debug Output With Command String  
N/A

### PCAP  
N/A

### Additional context  
Since the version number is not frequently updated, we've often run into the case where two versions (installed and git pull) do not have unambiguously different version numbers.  I will submit a pull request that fixes this by doing the following:
* Single source the version number so that the version in setup.py is used for the banner
* Standardize on Symantic + Pre-Release + Local versioning (see https://bit.ly/36QdfJX )
* Make setup.py detect whether it is in a git directory, and if so set the Local version to a date/time stamp corresponding to the last commit timestamp
* If not in a git directory, setup.py will not utilize the Local portion of the versioning

This ensures that no two git pulls will display the same version in the banner.

**Comment by asolino** [comment]
Closing as fixed in #761
