### ISSUE TITLE
problem when starting exe in c: \ windows

### ISSUE THREAD

**Issue by rafaelgov95** [SecureAuthCorp/impacket#776]
### Configuration  
impacket version:  0.9.20
Python version:  3.7
Target OS:  Arch Linux

### BUG
I need to run PsExec to upload the exe, not in c: \ windoows as usual, I need it installed in% Temp%. PsExec Tools works, when trying to use this from the impacket it creates in C: \ windows and my kaspersky is blocking it! Need help!

**Comment by asolino** [comment]
Hey @rafaelgov95 

That use case is not supported. If you want to install the service binary in a different location you will need to manually change the [ServiceInstall](https://github.com/SecureAuthCorp/impacket/blob/b91d2e3d4c5bd949d43f2ceee7112ae2a7a66a83/impacket/examples/serviceinstall.py#L25) class. 

That being said, Kaspersky will probably block it anyway.

Maybe you can try other remote exec methods like [wmiexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/wmiexec.py), [smbexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/smbexec.py)  [atexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/atexec.py) or [dcomexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/dcomexec.py).

Closing this issue.

**Comment by rafaelgov95** [comment]
> Hey @ rafaelgov95
> 
> Esse caso de uso não é suportado. Se você deseja instalar o binário de serviço em um local diferente, precisará alterar manualmente a classe [ServiceInstall](https://github.com/SecureAuthCorp/impacket/blob/b91d2e3d4c5bd949d43f2ceee7112ae2a7a66a83/impacket/examples/serviceinstall.py#L25) .
> 
> Dito isto, o Kaspersky provavelmente o bloqueará de qualquer maneira.
> 
> Talvez você possa tentar outros métodos exec remotos como [wmiexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/wmiexec.py) , [smbexec.py ](https://github.com/SecureAuthCorp/impacket/blob/master/examples/smbexec.py) [atexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/atexec.py) ou [dcomexec.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/dcomexec.py) .
> 
> Fechando esse problema.

However Psexec Tools on windows works! Wouldn't it be the same source code?

**Comment by asolino** [comment]
No it's not. `psexec.py` is based on [RemComSvc](https://github.com/kavika13/RemCom).

**Comment by rafaelgov95** [comment]
@asolino Even changing the path path does not work! Keep sending the file to C: \ windows even if you put C: \ in path!

` if self.share.lower() == 'admin$':
                        #path = '%systemroot%'
                          path = 'C:\\
                    else:
                        if serverName != '':
                           path = '\\\\%s\\%s' % (serverName, self.share)
                        else:
                           path = '\\\\127.0.0.1\\' + self.share 
                    service = self.createService(svcManager, self.share, path)
                    serviceCreated = True`
