### ISSUE TITLE
 smbexec.py gives an error - smb session error status object name not found (the object not found)

### ISSUE THREAD

**Issue by Anton19780301** [SecureAuthCorp/impacket#777]
downloaded impacket from git right now (latest version - v.0.9.21.dev1+2020020.181330.03cbe6e8).
I try - python smbexec.py DOMAIN\9999-00-202: Atdhfkm2020@192.10..0.10
And I get the error: smb session error status object name not found (the object not found)

192.10..0.10 - Windows7
DOMAIN - domain name
Atdhfkm2020 - password for 9999-00-202
9999-00-202 - my login in Windows7 , it's local admin on 192.10..0.10. Not domain admin.
Atack comp - Kali 2020-01-20

Sorry, I'm just learning, is this how it should be? I thought to get the CMB console.
![Снимок экрана от 2020-02-21 09-37-46](https://user-images.githubusercontent.com/51848186/75012444-08a24780-5493-11ea-8c89-66b531d7dafb.png)

**Comment by asolino** [comment]
Can you `smbclient.py` as Admin and access the C$ share?

Remember the separator between domain and username is `/` (not `\`)

Did you try `wmiexec.py` or `psexec.py`?

**Comment by cyberfreaq** [comment]
Today I got the same error with the latest impacket version:
![image](https://user-images.githubusercontent.com/55670396/102117018-123fd600-3e3e-11eb-8c41-a6c8911831a3.png)

It also happens with 0.9.22:
![image](https://user-images.githubusercontent.com/55670396/102117229-5cc15280-3e3e-11eb-92fb-e3f375ab88f5.png)

I ran it both times with:
`smbexec.py domain/administrator:secretpassword@192.168.1.2 -port 445`

Connecting via smbclient.py works:
![image](https://user-images.githubusercontent.com/55670396/102117335-79f62100-3e3e-11eb-9fc9-3b1a60011588.png)

Running wmiexec.py with `wmiexec.py domain/administrator:secretpassword@192.168.1.2` works also:
![image](https://user-images.githubusercontent.com/55670396/102117473-a5790b80-3e3e-11eb-9c0e-c0b3487a918f.png)

Has anyone an idea why this happens?

Bonus question: Is there any other tool I can run over proxychains to get code execution after getting a connection via ntlmrelayx? As far is I can remember, wmiexec uses parallel connections and therefore does not work.

**Comment by 0x5ECF4ULT** [comment]
cyberfreaq just tried this and got rpc_access_denied .

**Comment by mohemiv** [comment]
The STATUS_OBJECT_NAME_NOT_FOUND error should indicate that there is no `\PIPE\svcctl` pipe in the `IPC$` share for some reasons.

**Comment by ikspozd** [comment]
I'm getting the same error after running a successful -c "whoami". Not sure why subsequent commands error out.
![ERROR](https://user-images.githubusercontent.com/17556266/113005652-ab230480-9142-11eb-9d74-225eaa350219.PNG)

**Comment by 0xdeaddood** [comment]
`STATUS_OBJECT_NAME_NOT_FOUND` could also mean that an antivirus stopped the execution of the service that runs the commands and, therefore, there is no output file from which smbexec.py can get the results. If you find this error, check that there is no AV in the target.

**Comment by ChoboSyk** [comment]
Had the same issue in my lab on a Windows Server 2019 Core while it was working fine on another host will a full install of Windows Server 2019. After debugging I found out that when simulating what smbexec did via SC.exe the command on the Core server errored out on the del part of the command: 

%COMSPEC% /Q /c echo whoami ^> \\127.0.0.1\C$\__output 2^>^&1 > %TEMP%\execute.bat & %COMSPEC% /Q /c %TEMP%\execute.bat & **del %TEMP%\execute.bat**

An easy fix was to change the code to add %COMSPEC% /Q /c  in front of the DEL command. Not sure why core doesn't recognize the del command on it's own but it works on a full GUI installation. Adding it makes the command execute successfully on both install types. Hopefully this helps anyone that runs into the same issue. 

The full command ran at the end looks like this:

%COMSPEC% /Q /c echo whoami ^> \\127.0.0.1\C$\__output 2^>^&1 > %TEMP%\execute.bat & %COMSPEC% /Q /c %TEMP%\execute.bat & **%COMSPEC% /Q /c del %TEMP%\execute.bat**

Also a note that if you're having the same issue with ntlmrelayx the code to be modified can be found in secretsdump.py

**Comment by archidote** [comment]
> `STATUS_OBJECT_NAME_NOT_FOUND` could also mean that an antivirus stopped the execution of the service that runs the commands and, therefore, there is no output file from which smbexec.py can get the results. If you find this error, check that there is no AV in the target.

When I disable the real time protection of my ADDS, it works. Thank's !
