### ISSUE TITLE
psexec.py TGS (silver) ticket issue

### ISSUE THREAD

**Issue by Q1984** [SecureAuthCorp/impacket#779]
### Configuration  
impacket version:  Impacket v0.9.21-dev
Python version:  2.7
Target OS:  kali

(TGS generated by ticketer previously)
klist: Ticket cache: FILE:admin.ccache
Default principal: admin@redacted.local

Valid starting       Expires              Service principal
2020-02-21 15:07:08  2030-02-18 15:07:08  cifs/fserv.redacted.local@redacted.local
	renew until 2030-02-18 15:07:08

psexec.py redacted.local/admin@fserv.redacted.local -k -n -debug

Impacket v0.9.21-dev - Copyright 2019 SecureAuth Corporation

[+] StringBinding ncacn_np:fserv.redacted.local[\pipe\svcctl]
[+] Using Kerberos Cache: admin.ccache
[+] Returning cached credential for CIFS/fserv.redacted.local@redacted.local
[+] Using TGS from cache
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/impacket-0.9.21.dev0-py2.7.egg/EGG-INFO/scripts/psexec.py", line 118, in doStuff
  File "build/bdist.linux-x86_64/egg/impacket/dcerpc/v5/rpcrt.py", line 800, in connect
    return self._transport.connect()
  File "build/bdist.linux-x86_64/egg/impacket/dcerpc/v5/transport.py", line 410, in connect
    TGS=self._TGS)
  File "build/bdist.linux-x86_64/egg/impacket/smbconnection.py", line 348, in kerberosLogin
    raise SessionError(e.get_error_code(), e.get_error_packet())
SessionError: SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)
[-] SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)

**Comment by asolino** [comment]
Hey @Q1984 

`STATUS_MORE_PROCESSING_REQUIRED` could mean many different things. We tested generating a silver ticket here and seems to be working. Closing now. Feel free to open it again if you keep experiencing the same issue but we will need a better way to reproduce this problem

**Comment by jfmaes** [comment]
@asolino I have the same issue

**Comment by mohemiv** [comment]
@jfmaes, @Q1984, Most likely the your system's time is not synchronized with the time of the target.

Try to run ntpdate command with any NTP server available in the Internet, or with your Domain Controller address:
```
ntpdate europe.pool.ntp.org
ntpdate dc01.contoso.com
```
Don't forget to regenerate the ticket after this. Also consider to extract the target system's time by the smb2-time script in nmap or by any similar tool (requires no authentication).

**Comment by jfmaes** [comment]
@mohemiv  I have control over the DC and the WS, both are set to exactly the same time.

**Comment by mohemiv** [comment]
Is the system where you are running Impacket set to this time and timezone
as well?

**Comment by jfmaes** [comment]
yes, impacket is running on what I refer to as WS 👍

**Comment by jfmaes** [comment]
```
root@slingshot:/home/lab# smbclient.py -k -no-pass contoso.com/administrator@dc01.contoso.com -debug
Impacket v0.9.22.dev1+20200603.152956.fe40cb04 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python2.7/dist-packages/impacket
[+] Using Kerberos Cache: Administrator.ccache
[+] SPN CIFS/DC01.contoso.com@contoso.com not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for TIME/DC01.contoso.com@contoso.com
[+] Changing sname from TIME/DC01.contoso.com@contoso.com to cifs/DC01.contoso.com@contoso.com and hoping for the best
[+] Using TGS from cache
Traceback (most recent call last):
  File "/usr/local/bin/smbclient.py", line 103, in main
    smbClient.kerberosLogin(username, password, domain, lmhash, nthash, options.aesKey, options.dc_ip )
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbconnection.py", line 348, in kerberosLogin
    raise SessionError(e.get_error_code(), e.get_error_packet())
SessionError: SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)
[-] SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)

```

**Comment by jfmaes** [comment]
@mohemiv 

apparently it has to do with the delegation on the time service. 
I gave other delegation rights and now everything seems to work alright.

**Comment by rocketscientist911** [comment]
weird, I am having the same issue as well and testing this on WSL2 Ubuntu 20.04

**Comment by Hackndo** [comment]
Thank you @mohemiv , that was my issue, 15min time difference.

**Comment by ChenYun4164** [comment]
if you use some proxy , try to use `-target-ip ` to specify the target ip . is work to me 
![image](https://user-images.githubusercontent.com/45526365/141440559-d6a2d2b4-bd69-49f4-a2b2-387b66b08125.png)
![image](https://user-images.githubusercontent.com/45526365/141440588-8a6db785-faf3-4bf4-92e6-2d589476a1fb.png)

**Comment by Slava-Glv** [comment]
sudo timedatectl set-ntp off
sudo ntpdate <DC ip>

solved the problem for me, sometimes need to run in multiple times

**Comment by 0xWr417h** [comment]
Had this issue recently on an HTB machine. Time was sync'd. The issue was the OpenVPN connection. I killed it and reconnected and it started working as it should have w/o error.
