### ISSUE TITLE
Impacket Slack Workspace - JOIN US!

### ISSUE THREAD

**Issue by chenerlich** [SecureAuthCorp/impacket#789]
Hi everyone,

Since i'm using Impacket on a daily basis (so as other thousands of people and projects), I decided to start an Impacket Slack workspace to be used as a platform for asking questions, sharing helpful snippets, proposing new features and and more!

I believe it can make our community even bigger and enrich this awesome project.

You are more than welcome to join!
https://join.slack.com/t/impacket/shared_invite/zt-cieq209u-rx0aDugIErL_2Fh04NC78w

Chen.

**Comment by asolino** [comment]
Thanks @chenerlich 

Keep in mind there's an #impacket channel already in place in the [Bloodhound Gang Slack](https://bloodhoundgang.herokuapp.com/)

**Comment by chenerlich** [comment]
Thanks, I know.
Just a more organized place to discuss Impacket.

If the link has expired, whoever wants to join in is welcome to shoot me a message on Twitter - https://twitter.com/chen_erlich
