### ISSUE TITLE
Log records in ntlmrelayx

### ISSUE THREAD

**Issue by marevalo10** [SecureAuthCorp/impacket#790]
### Configuration  
impacket version:  0.9.20
Python version:  3.7.6
Target OS:  Linux Kali20 5.4.0

### Debug Output With Command String  
This is the command I run:
python3 /usr/share/doc/python3-impacket/examples/ntlmrelayx.py -tf SMBtarget.txt -c 'command'

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
I used this command to conduct a test in a network pentest an some problems arise so I'm trying to get the logs and time of the events to figure out if the command execution caused the problem. Is there a way to get logs of the actions executed by ntlmrelayx?

**Comment by asolino** [comment]
Try to run it with `-debug`, there might be more information.

Not sure what you're looking for tho. Reopen this ticket if you need further info (or share the output of the problems you're having).
