### ISSUE TITLE
Chinese system garbled please

### ISSUE THREAD

**Issue by klionsec** [SecureAuthCorp/impacket#793]
Can you help solve the problem that the Chinese system cannot display the execution results properly?

msf5 auxiliary(scanner/smb/impacket/wmiexec) > set command whoami /user
command => whoami /user
msf5 auxiliary(scanner/smb/impacket/wmiexec) > run

[*] Running for 192.168.159.149...
[*] 192.168.159.149 - SMBv2.1 dialect used
[-] 192.168.159.149 - 'utf8' codec can't decode byte 0xa8 in position 40: invalid start byte
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed

**Comment by asolino** [comment]
Similar answer as #795
