### ISSUE TITLE
Does not seem to support Chinese echo results, can you help update?

### ISSUE THREAD

**Issue by klionsec** [SecureAuthCorp/impacket#795]
msf5 auxiliary(scanner/smb/impacket/wmiexec) > show options 

Module options (auxiliary/scanner/smb/impacket/wmiexec):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   COMMAND    whoami           yes       The command to execute
   OUTPUT     true             yes       Get the output of the executed command
   RHOSTS     192.168.159.131  yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   SMBDomain  motoo            no        The Windows domain to use for authentication
   SMBPass    admin123!@#45    yes       The password for the specified username
   SMBUser    administrator    yes       The username to authenticate as
   THREADS    1                yes       The number of concurrent threads (max one per host)

msf5 auxiliary(scanner/smb/impacket/wmiexec) > run

[*] Running for 192.168.159.131...
[*] 192.168.159.131 - SMBv3.0 dialect used
[*] motoo\administrator

[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/impacket/wmiexec) > set command whoami /user
command => whoami /user
msf5 auxiliary(scanner/smb/impacket/wmiexec) > run

[*] Running for 192.168.159.131...
[*] 192.168.159.131 - SMBv3.0 dialect used
[-] 192.168.159.131 - 'utf8' codec can't decode byte 0xd3 in position 2: invalid continuation byte
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/impacket/wmiexec) >

**Comment by asolino** [comment]
We do not offer support for impacket bundled in other products. Please try to reproduce this issue with our example libraries and latest version. 
Closing.
