### ISSUE TITLE
smbrelayx.py init() errors

### ISSUE THREAD

**Issue by zZJH0222** [SecureAuthCorp/impacket#797]
This is what I always report when I run this program. i have no idea about it.thinks

Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation

Traceback (most recent call last):
  File "smbrelayx.py", line 1152, in <module>
    logger.init(options.ts)
TypeError: init() takes 0 positional arguments but 1 was given

**Comment by doantung99** [comment]
I delete the options.ts. It works:
logger.init()

**Comment by zZJH0222** [comment]
> 我删除了options.ts。它的工作原理是：
> logger.init（）

ok,think you,It seems that there is something wrong with the current version 0.9.21. I used version 0.9.20 without any error，it works.

**Comment by 0xdeaddood** [comment]
Hi @zZJH0222. It seems you didn't install the latest master branch. 
Please check #754

**Comment by asolino** [comment]
Closing as duplicate of #754
