### ISSUE TITLE
setup.py is missing install requirement six

### ISSUE THREAD

**Issue by mback2k** [SecureAuthCorp/impacket#798]
### Configuration  
impacket version:  impacket-0.9.20
Python version:  Python 3.7.7
Target OS:  MacOS

### Debug Output With Command String  

```
Traceback (most recent call last):
  File "curl/tests/smbserver.py", line 46, in <module>
    from impacket import smbserver as imp_smbserver
  File "/usr/local/lib/python3.7/site-packages/impacket/smbserver.py", line 44, in <module>
    from six import PY2, b, text_type
ModuleNotFoundError: No module named 'six'
```

I am trying to port our `smbserver.py` in the curl project to Python 3.
Now I noticed that your `setup.py` seems to be missing the requirement `six`.

**Comment by asolino** [comment]
Hey @mback2k:

`smbserver.py` should work with Python3. `six` is included as a requirement now ([here](https://github.com/SecureAuthCorp/impacket/blob/master/requirements.txt#L2) and [here](https://github.com/SecureAuthCorp/impacket/blob/master/setup.py#L61)). 

What am I missing here?

**Comment by mback2k** [comment]
@asolino Thanks. I was referring to the `smbserver.py` in our repo that wraps your `smbserver.py`.

I guess we somehow ended up with an older version (0.9.20) that did not yet list `six` as a requirement.
