### ISSUE TITLE
dpapi.py does not have a -no-pass option

### ISSUE THREAD

**Issue by aconite33** [SecureAuthCorp/impacket#804]
### Configuration  
impacket version:  v0.9.21.dev1+20200313.160519.0056b61c
Python version:  3
Target OS:  Windows server 2016

dpapi.py works with -k option when dealing with tickets, however it does not have a -no-pass option. While it still works, it does requires the user to enter a blank password for the authentication.

**Comment by darkoperator** [comment]
just replicated this issue in the case of backupkeys

**Comment by asolino** [comment]
Please `git pull` and re-test.
