### ISSUE TITLE
[-] Exception in HTTP request handler: 'HTTPMessage' object has no attribute 'getheader'

### ISSUE THREAD

**Issue by BalaDeveloper2094** [SecureAuthCorp/impacket#805]
### Configuration  
impacket version:  v0.9.21
Python version:  3.7.7
Target OS:  Kali linux

### Debug Output With Command String  root
Impacket v0.9.21.dev1+20200313.160519.0056b61c - Copyright 2020 SecureAuth Corporation
[+] Impacket Library Installation Path: /usr/local/lib/python3.7/dist-packages/impacket
[*] Protocol Client SMB loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client SMTP loaded..
[+] Protocol Attack MSSQL loaded..
[+] Protocol Attack SMB loaded..
[+] Protocol Attack HTTP loaded..
[+] Protocol Attack HTTPS loaded..
[+] Protocol Attack LDAP loaded..
[+] Protocol Attack LDAPS loaded..
[+] Protocol Attack IMAP loaded..
[+] Protocol Attack IMAPS loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] HTTPD: Received connection from 192.168.203.134, attacking target smb://192.168.203.135
[*] HTTPD: Received connection from 192.168.203.134, but there are no more targets left!
[*] HTTPD: Received connection from 192.168.203.134, attacking target smb://192.168.203.135
[+] Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 75, in handle_one_request
    http.server.SimpleHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.7/dist-packages/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 143, in do_PROPFIND
    if self.headers.getheader('Authorization') is None:
AttributeError: 'HTTPMessage' object has no attribute 'getheader'
[-] Exception in HTTP request handler: 'HTTPMessage' object has no attribute 'getheader'

**Comment by 0xdeaddood** [comment]
Hey @BalaDeveloper2094! What command are you running?

**Comment by BalaDeveloper2094** [comment]
I tried running the following command "ntlmrelayx.py -tf target.txt -smb2support".  I performed update, upgrade and install . on my VM which solved this error. Thank you for your response.

**Comment by asolino** [comment]
Thanks for your feedback @BalaDeveloper2094 , so looks like the error is solved. Closing.

**Comment by 0xdeaddood** [comment]
Good to know it!
