### ISSUE TITLE
Does secretsdump authenticate with nthash?

### ISSUE THREAD

**Issue by a6avind** [SecureAuthCorp/impacket#807]

**Comment by asolino** [comment]
Yes, you need to specify the LMHASH:NTHASH using the `-hashes` switch.

**Comment by a6avind** [comment]
what if I only have NTHASH?

**Comment by asolino** [comment]
If you only have the NTHASH, specify the LMHASH as empty. Something like `-hashes :NTHASH` should work (pay attention to the colon there). Let me know.

**Comment by a6avind** [comment]
It works with -hashes ':NTHASH'. Thank you

**Comment by asolino** [comment]
Great to know @a6avind
