### ISSUE TITLE
GetNPUsers - unable to enumerate targets with kerberos KRB5CC

### ISSUE THREAD

**Issue by Meatballs1** [SecureAuthCorp/impacket#809]
https://github.com/SecureAuthCorp/impacket/blob/7e50589280b07ce6814adf97a0492917dc5a6620/examples/GetNPUsers.py#L215-L221

If you are using a `KRB5CC` cache file to authenticate with `-k -nopass` then this module will not enumerate users and only checks the `target` user. 

You have to remove the `-nopass` arg and enter the password. But if you don't know the password you are stuffed :) 

It would be nice to be able to enumerate users even when `-nopass` is used.

**Comment by asolino** [comment]
Did you try not using `-no-pass` and then when password is prompted just hit Enter? 

This is a confusing usage indeed, I need to review the logic, but in the meantime it can work as a workaround.

**Comment by Meatballs1** [comment]
I think I tried a blank password but it just caused a PRE_AUTH failure (but I cant recall for certain).
