### ISSUE TITLE
psexec.py Keytab module missing

### ISSUE THREAD

**Issue by almemar8719** [SecureAuthCorp/impacket#811]
Hi all, 
I've tried previous versions, all got an error or so. However, the latest one resolved those errors but got missing module. 
am getting this error
--------------
File "psexec.py", line 33, in <module>
    from impacket.krb5.keytab import Keytab
ImportError: No module named keytab
---------------

Appreciate if you guide me to stable version. 

I've backed to six older version. all got issues

**Comment by asolino** [comment]
Can you send me the *full* output of what you are executing? Something tells me you have an old library version installed somewhere that is being loaded first.

**Comment by asolino** [comment]
No answer, closing. Reopen if needed.

**Comment by lockness-Ko** [comment]
@asolino 
`root@kali:~/Desktop/impacket/examples# ./psexec.py adminstrator@10.10.10.27
Traceback (most recent call last):
  File "./psexec.py", line 33, in <module>
    from impacket.krb5.keytab import Keytab
ImportError: No module named keytab
`

**Comment by asolino** [comment]
You're having an old impacket library installed. Either [0.9.21](https://github.com/SecureAuthCorp/impacket/blob/impacket_0_9_21/impacket/krb5/keytab.py) or [master](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/krb5/keytab.py) have that file committed.

**Comment by almemar8719** [comment]
Hi Alberto, I lost track where I used it. But it worked on that time. my
apologies for the late reply

Ali

**Comment by asolino** [comment]
Thanks for the update.

**Comment by EvanGertis** [comment]
I am getting the same issue. ```
File "psexec.py", line 33, in <module>
    from impacket.krb5.keytab import Keytab
ImportError: No module named keytab
```

**Comment by Southparkfan** [comment]
@lockness-Ko @EvanGertis In Kali I had this issue as well. What I found out is that using './psexec.py' does NOT work, but 'python3 psexec.py' does. Can you try that?
