### ISSUE TITLE
now versions relay problem

### ISSUE THREAD

**Issue by zsirlev** [SecureAuthCorp/impacket#814]
impacket version: 0.9.20 and 0.9.21 including the actual master
python 3.7.7
os: kali (fully updated, the included impacket-ntlmrelayx has the same issue for me)
relayed os: between two windows 2019 server, on virtualbox VM.

Hello!

I have a problem with the ntlmrelayx, with the version 0.9.20 and 0.9.21, the highest version works fine is the version 0.9.19 (python 2.7.17). The relay never successful, I always get failure (the -debug do not give any error message).

I did some network monitoring, and found the following: 
- In the not working version the relayed packet is smaller than the one it got (706 bytes versus 731 bytes)
The difference is coming from some differences in the Security BLOB, here are the copy of what it got, and what it forwarded as security BLOB:

got:
a182024530820241a0030a0101a2820224048202204e544c4d5353500003000000180018009000000068016801a800000012001200580000001a001a006a0000000c000c00840000001000100010020000158288e20a0063450000000fc2f2a16c7ea7d9956a4bd1ca5f74a0884d00590043004f004d00500041004e005900410064006d0069006e006900730074007200610074006f0072004400430032004b00310039000000000000000000000000000000000000000000000000001f9fd2b23debbe35a62858ad255e760c0101000000000000dc0db935fab3d4017d8e846bbd43c27400000000020012004d00590043004f004d00500041004e0059000100140053004500520056004500520032004b003100390004001e006d00790063006f006d00700061006e0079002e006c006f00630061006c000300340053006500720076006500720032006b00310039002e006d00790063006f006d00700061006e0079002e006c006f00630061006c0005001e006d00790063006f006d00700061006e0079002e006c006f00630061006c0007000800dc0db935fab3d401060004000200000008003000300000000000000000000000003000007241af7c907fdafa5e01074aac6f0516acbcb827ee6c95163292be9f79ba3c000a001000000000000000000000000000000000000900260063006900660073002f003100390032002e003100360038002e003100360038002e00370037000000000000000000000000007b37b56a767123dbde536bfdccf327c6a3120410010000004a996e31adf3e49800000000

forwarded
a182022c30820228xxxxxxxxxxa2820224048202204e544c4d5353500003000000180018009000000068016801a800000012001200580000001a001a006a0000000c000c00840000001000100010020000158288e20a0063450000000fc2f2a16c7ea7d9956a4bd1ca5f74a0884d00590043004f004d00500041004e005900410064006d0069006e006900730074007200610074006f0072004400430032004b00310039000000000000000000000000000000000000000000000000001f9fd2b23debbe35a62858ad255e760c0101000000000000dc0db935fab3d4017d8e846bbd43c27400000000020012004d00590043004f004d00500041004e0059000100140053004500520056004500520032004b003100390004001e006d00790063006f006d00700061006e0079002e006c006f00630061006c000300340053006500720076006500720032006b00310039002e006d00790063006f006d00700061006e0079002e006c006f00630061006c0005001e006d00790063006f006d00700061006e0079002e006c006f00630061006c0007000800dc0db935fab3d401060004000200000008003000300000000000000000000000003000007241af7c907fdafa5e01074aac6f0516acbcb827ee6c95163292be9f79ba3c000a001000000000000000000000000000000000000900260063006900660073002f003100390032002e003100360038002e003100360038002e00370037000000000000000000000000007b37b56a767123dbde536bfdccf327c6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

From the forwarded blob the following things are missing:
- negResult (it got 01, but did not forward it)
- 4 bytes before the negResult (wireshark do not name these bytes, for me it was a0030a01)
- the mechListMIC (16 bytes, for me 010000004a996e31adf3e49800000000)
- four bytes before the mechListMIC (the wireshark do not name these bytes, for me a3120410)

I attached 2 wireshark capture: good.pcapng is from version 0.9.19 as it works
bad.pcapng: with version 0.9.21 not works (for example packets 27 and 29 are the ones I wrote about)

[captures.zip](https://github.com/SecureAuthCorp/impacket/files/4428695/captures.zip)

**Comment by 0xdeaddood** [comment]
Hi @zsirlev! What command are you trying to run?

**Comment by Hackndo** [comment]
Maybe https://github.com/SecureAuthCorp/impacket/pull/822 fixes this issue.

**Comment by asolino** [comment]
No answer, closing.
