### ISSUE TITLE
Can't install impacket

### ISSUE THREAD

**Issue by Trixelit** [SecureAuthCorp/impacket#819]
When trying to run `sudo python setup.py install` after running `sudo python setup.py build` I get an error saying `AttributeError: 'NoneType' has no attribute 'clone'`

**Comment by asolino** [comment]
What version of impacket are you trying to install? 

Looks like you're not following the steps detailed [here](https://github.com/SecureAuthCorp/impacket/blob/master/README.md)

**Comment by asolino** [comment]
No answer, closing.
