### ISSUE TITLE
cant run ntlmrelayx.py 

### ISSUE THREAD

**Issue by bryanweielio** [SecureAuthCorp/impacket#820]
here's the output if i run ntlmrelayx.py with python 2.7 

Traceback (most recent call last):
  File "ntlmrelayx.py", line 321, in <module>
    from impacket.examples.ntlmrelayx.clients import PROTOCOL_CLIENTS
  File "/usr/local/lib/python2.7/dist-packages/impacket/examples/ntlmrelayx/clients/__init__.py", line 106, in <module>
    __import__(package + '.' + os.path.splitext(file)[0])
  File "/usr/local/lib/python2.7/dist-packages/impacket/examples/ntlmrelayx/clients/ldaprelayclient.py", line 22, in <module>
    from ldap3 import Server, Connection, ALL, NTLM, MODIFY_ADD
  File "/usr/local/lib/python2.7/dist-packages/ldap3/__init__.py", line 139, in <module>
    from .core.connection import Connection
  File "/usr/local/lib/python2.7/dist-packages/ldap3/core/connection.py", line 44, in <module>
    from ..operation.compare import compare_operation, compare_request_to_dict
  File "/usr/local/lib/python2.7/dist-packages/ldap3/operation/compare.py", line 28, in <module>
    from ..operation.search import ava_to_dict
  File "/usr/local/lib/python2.7/dist-packages/ldap3/operation/search.py", line 41, in <module>
    from pyasn1.error import PyAsn1UnicodeDecodeError
ImportError: cannot import name PyAsn1UnicodeDecodeError

I had ran pip install . and the setup script. Please help!

**Comment by 0xdeaddood** [comment]
Hi @bryanweielio! 

It seems a problem related with the pyasn1 package. What version of this package do you have installed? and what OS are you using?

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hey!

Same problem here with a Ubuntu 18.04 (fresh install). It seems to be a conflict between the version already installed / PATH / pip.

Performed commands:

```
$ sudo apt install python-pip3
$ sudo pip3 install -r requirements.txt 
$ sudo python3 setup.py install
```
 
The following command fixes the issue

`$ pip3 install pyasn1`

(without sudo)

:sunflower:

**Comment by 0xdeaddood** [comment]
I was digging into this and I found there is a conflict with the latest version of ldap3 (2.7.1) and  pyasn1 versions 0.4.5 and earlier resulting in: `ImportError: cannot import name PyAsn1UnicodeDecodeError`

If you are going to use ldap 2.7.1 you need to install pyasn1 0.4.6 or higher (which include PyAsn1UnicodeDecodeError). 

The impacket `requirements.txt` may need to be changed.

**Comment by mpgn** [comment]
The `requirements.txt` could be updated from if we follow the logic
```
ldap3>=2.5,!=2.5.2,!=2.5.0,!=2.6,!2.7
```
to
```
ldap3==2.5.1
```

https://github.com/cannatag/ldap3/releases

**Comment by exploide** [comment]
I think blacklisting v2.7 or even worse restricting to the old `ldap3==2.5.1` is not a good idea. If @0xdeaddood is right, then raising to `pyasn1>=0.4.6` is more appropriate. However, this would only be a workaround in impacket, because the actual fix would be to raise this version in [ldap3/requirements.txt](https://github.com/cannatag/ldap3/blob/master/requirements.txt) where it belongs. Someone who got the details could open an issue there.

---

> It seems to be a conflict between the version already installed / PATH / pip.

If you want to avoid this in future, you can do yourself a favour and don't `sudo pip`. System-wide installations should be done via the distribution's package manager, i.e. `apt`. When installing dependencies for projects cloned from git, install them inside a [virtualenv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/).

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
> If you want to avoid this in future, you can do yourself a favour and don't sudo pip. System-wide installations should be done via the distribution's package manager, i.e. apt. When installing dependencies for projects cloned from git, install them inside a virtualenv.

I know, I try to change this bad habit on my main machine, but it's harder on a throw away vm :smile:

**Comment by 0xdeaddood** [comment]
> I think blacklisting v2.7 or even worse restricting to the old ldap3==2.5.1 is not a good idea. If @0xdeaddood is right, then raising to pyasn1>=0.4.6 is more appropriate. However, this would only be a workaround in impacket, because the actual fix would be to raise this version in ldap3/requirements.txt where it belongs. Someone who got the details could open an issue there.

There is a [PR](https://github.com/cannatag/ldap3/pull/802) waiting in the ldap3 repository about this. In the meantime, I agree on what you say, It would be more appropriate to change the pyasn1 requirement. I'll do some tests to check that everything is OK with those versions before changing it.
