### ISSUE TITLE
Connection failed: Unable to fetch correct smb version for 2019 Windows Datacenter RODC

### ISSUE THREAD

**Issue by anikep** [SecureAuthCorp/impacket#829]
### Configuration  
impacket version:  0.9.14
Python version:  2.7.6
Target OS:  Windows Datacenter 2019 RODC

### Debug Output With Command String  
i.e.  
WMIEXEC("systeminfo", username, password, domain, None, None, 'ADMIN$', False, False).run(ip)
```
/opt/meridian/dc/embedded/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
Traceback (most recent call last):
  File "wmitest.py", line 3, in <module>
    executer.run('192.168.1.1')
  File "/opt/meridian/dc/embedded/lib/python2.7/site-packages/meridian_connectors/windows/wmiexec.py", line 68, in run
    smbConnection.login(self.__username, self.__password, self.__domain, self.__lmhash, self.__nthash)
  File "/opt/meridian/dc/embedded/lib/python2.7/site-packages/impacket/smbconnection.py", line 215, in login
    raise SessionError(e.get_error_code())
impacket.smbconnection.SessionError: SMB SessionError: STATUS_USER_SESSION_DELETED(The remote user session has been deleted.)
```

### Additional context  
Above execution failed, as it somehow fetched wrong smb version, i.e, smb3.0 and tried to connect, hence SMB SessionError: STATUS_USER_SESSION_DELETED(The remote user session has been deleted.)
While, remote server is configured to accept smb2.1 connections, not smb3.0
We checked by running this commands:
from impacket.smbconnection import *
USERNAME = 'Administrator'
PASSWORD = 'admin'
TARGET = '192.168.1.1'
s2 = SMBConnection(TARGET, TARGET, preferredDialect=SMB2_DIALECT_21)
s2.login(USERNAME, PASSWORD)
print "ALL GOOD"

Output of above script was success and it did connect with SMB2.1 Dialect, while it failed when trying to connect via WMIEXEC class.

**Comment by mpgn** [comment]
Hello,

Can you try with latest version 0.22 and python3, you are using a very old version of impacket.

**Comment by anikep** [comment]
Thanks @mpgn , we will try with latest version, although this is production environment so we certainly can't upgrade python here.

**Comment by mpgn** [comment]
No problem for python3, Impacket should also be compatible with Python2 :)

![image](https://user-images.githubusercontent.com/5891788/79880316-21c26880-83f0-11ea-8cc5-d2b25f7cddff.png)

**Comment by anikep** [comment]
Upgrading the library worked, Thanks @mpgn
