### ISSUE TITLE
mssqlclient.py  -- Missing required parameter 'digestmod'

### ISSUE THREAD

**Issue by natv** [SecureAuthCorp/impacket#850]
### Configuration  
impacket version:  impacket 0.9.21
Python version:  tried in python3.7 and 3.8
Target OS:  Kali Linux 2020:
Linux kali 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux

### Debug Output With Command String  

$ sudo python3.8 mssqlclient.py -p 1433 sql_svc@10.10.10.27 -windows-auth
Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation

Password:
[*] Encryption required, switching to TLS
[-] Missing required parameter 'digestmod'.

$ sudo python3.7 mssqlclient.py -p 1433 sql_svc@10.10.10.27 -windows-auth
Traceback (most recent call last):
  File "mssqlclient.py", line 25, in <module>
    from impacket import version, tds
  File "/usr/lib/python3/dist-packages/impacket/tds.py", line 35, in <module>
    from OpenSSL import SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'

### Additional context  

This worked some time ago from this same system, so I suspect the latest Kali updates perhaps changed something.

Thanks

**Comment by mpgn** [comment]
Try with `python3.7`

**Comment by natv** [comment]
Just some additional info, I also tried it in a completely different OS (Parrot Security OS) and am getting the same error.  Testing in Python 3.7 and 3.8



Here are both attempts


`
 $python3.7 mssqlclient.py sql_svc@10.10.10.27 -windows-auth
Traceback (most recent call last):
  File "mssqlclient.py", line 25, in <module>
    from impacket import version, tds
  File "/usr/lib/python3/dist-packages/impacket/tds.py", line 35, in <module>
    from OpenSSL import SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'


 $python3.8 mssqlclient.py sql_svc@10.10.10.27 -windows-auth
/usr/lib/python3/dist-packages/impacket/tds.py:778: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if lmhash is '' and nthash is '' and (aesKey is '' or aesKey is None) and TGT is None and TGS is None:
/usr/lib/python3/dist-packages/impacket/tds.py:778: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if lmhash is '' and nthash is '' and (aesKey is '' or aesKey is None) and TGT is None and TGS is None:
/usr/lib/python3/dist-packages/impacket/tds.py:778: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if lmhash is '' and nthash is '' and (aesKey is '' or aesKey is None) and TGT is None and TGS is None:
/usr/lib/python3/dist-packages/impacket/tds.py:813: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if lmhash is '' and nthash is '' and (aesKey is '' or aesKey is None) and TGT is None and TGS is None:
/usr/lib/python3/dist-packages/impacket/tds.py:813: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if lmhash is '' and nthash is '' and (aesKey is '' or aesKey is None) and TGT is None and TGS is None:
/usr/lib/python3/dist-packages/impacket/tds.py:813: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if lmhash is '' and nthash is '' and (aesKey is '' or aesKey is None) and TGT is None and TGS is None:
Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation

Password:
[*] Encryption required, switching to TLS
[-] Missing required parameter 'digestmod'.

`

**Comment by mpgn** [comment]
You need to use the latest version of impacket, you are using version v.0.9.20 while latest version is 0.9.21

**Comment by natv** [comment]
I just grabbed in again using
git clone https://github.com/SecureAuthCorp/impacket.git

is this master branch missing the latest mssqlclient.py script then?

**Comment by mpgn** [comment]
https://github.com/SecureAuthCorp/impacket/tree/master/examples

**Comment by natv** [comment]
I'm not sure what I'm doing wrong, but that's where I am download from, here is a screenshot of a fresh wget of both mssql scripts (grabbed the instance one too just in case) but it still shows "Impacket v0.9.20" as the version:

![mssqlclient](https://user-images.githubusercontent.com/1175232/81510444-bb8a8080-92df-11ea-8802-3b6e626a6fa7.jpg)

**Comment by mpgn** [comment]
`pip install impacket --upgrade --user`

**Comment by natv** [comment]
ahh thanks that updated it, appreciate the guidance

In my case I did
`pip3 install impacket --upgrade --user`

**Comment by mpgn** [comment]
Feel free to close the issue :)

**Comment by natv** [comment]
Resolved thanks!

**Comment by ExCH0nsiv3** [comment]
Thanks it's work!
