### ISSUE TITLE
rdp check raise　　no attribute 'NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY'

### ISSUE THREAD

**Issue by CptGuo** [SecureAuthCorp/impacket#854]
### Configuration  
impacket version:  last
Python version:  2.7
Target OS:  Windows 7

### Debug Output With Command String  
rdp_check.py
```
 'module' object has no attribute 'NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY'
```

**Comment by asolino** [comment]
Are you getting any version banner when you run the script? Sounds like a broken installation.

**Comment by CptGuo** [comment]
3Q, problem solved by reinstall impacket.
