### ISSUE TITLE
rdp_check.py - Windows 2008 R2 | Multiple TLS record layers in NTLMSSP_NEGOTIATE stage cause Internal Error

### ISSUE THREAD

**Issue by mortuis-intus** [SecureAuthCorp/impacket#875]
Connecting to Windows R2 2008 servers I get an error `OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error')]` in line 442 of file "rdp_check.py", in function check_rdp
`buff = tls.recv(4096)`
After examining the packages with Wireshark, I determined that multiple TLS layer records are being transmitted
![image](https://user-images.githubusercontent.com/66578131/83984615-991b6f80-a93e-11ea-9139-5169b73a79ae.png)
With other OS (Windows 7,10 etc) this does not happen and only one TLS layer record is transmitted
![image](https://user-images.githubusercontent.com/66578131/83984651-dbdd4780-a93e-11ea-9391-1a914c6b539e.png)
I am not an expert in OpenSSL and working with certificates and would like to know your guesses about solving this problem
In my opinion, there is a problem with a double certificate sent by the server, because the first TLS layer record is not decrypted if the server has a private key, and the second is decrypted on the contrary and there is a packet generated at the TSRequest stage
I am ready to conduct all possible tests and provide all the decrypted traffic to you
Also add that I use SSLv23 in `ctx = SSL.Context()` 
because it is important for me to support servers with TLS from 1.0 to 1.2

**Comment by mortuis-intus** [comment]
Perhaps the problem is not specific in Windows 2008 R2, but in the TLS 1.0 version that it mainly uses and there is nothing to do with certificates because at the Hanshake stage I get only one certificate. And most likely two TLS Record Layers encode one NTLMSSP_NEGOTIOATE packet. The only question is why this happens in TLS 1.0

**Comment by hatlord** [comment]
I think this could be related. I had various TLS/SSL issues against 2008R2 but earlier operating systems worked. https://github.com/SecureAuthCorp/impacket/issues/429

**Comment by yixiangwenhai** [comment]
Have you solved the problem

**Comment by w0shlzheNdecaI** [comment]
> 你有没有解决问题

brother，do you have any answers？

**Comment by 0xdeaddood** [comment]
Hey folks!

Please check [this](https://github.com/SecureAuthCorp/impacket/issues/1331#issuecomment-1171873260) and let me know if it works.

**Comment by yixiangwenhai** [comment]
没有，我还在寻找可以替代的其他方法
No, I'm still looking for the alternative to other methods



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SecureAuthCorp/impacket"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月2日(星期四) 中午1:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SecureAuthCorp/impacket] rdp_check.py - Windows 2008 R2 | Multiple TLS record layers in NTLMSSP_NEGOTIATE stage cause Internal Error (#875)





  
你有没有解决问题
  
brother，do you have any answers？
