### ISSUE TITLE
by default hElfrReadELW does not accept offset

### ISSUE THREAD

**Issue by spinenkoia** [SecureAuthCorp/impacket#882]
### Configuration  
impacket version:  0.9.21
Python version:  3.7
Target OS:  Arch Linux 5.4.6

### Additional context  
From the Readeventlog documentation, if EVENTLOG_SEEK_READ is omitted, offset is ignored, as a result, all events are returned from the beginning, instead of the necessary ones.

You must set readFlags=EVENTLOG_SEEK_READ|EVENT LOG_FORWARD_READ by default

**Comment by spinenkoia** [comment]
https://support.microsoft.com/en-us/help/177199/bug-readeventlog-fails-with-error-87

**Comment by spinenkoia** [comment]
Sometimes it can cause problems

**Comment by spinenkoia** [comment]
@asolino please take a look

**Comment by asolino** [comment]
Fixed at https://github.com/spinenkoia/impacket/commit/be64aa2899485502e9510b5d82b1c4cf3ab5b096
