### ISSUE TITLE
i cant install . impacket

### ISSUE THREAD

**Issue by EdgeLord69-something** [SecureAuthCorp/impacket#894]
when i try to pip install . it give me an error can someone please explain why this happens.

**Comment by asolino** [comment]
Maybe reporting the error to understand what's going on could help. Reopen when getting that data.

**Comment by EdgeLord69-something** [comment]
the error says bash: pip command not found

**Comment by EdgeLord69-something** [comment]
> Maybe reporting the error to understand what's going on could help. Reopen when getting that data.

my bad its pip3 install
