### ISSUE TITLE
RPC_E_INVALID_HEADER when using wmiexec.py

### ISSUE THREAD

**Issue by okiwoki** [SecureAuthCorp/impacket#896]
### Configuration  
impacket version:  Impacket v0.9.22.dev1+20200629.145357.5d4ad6cc
Python version:  3.8.3
Target OS:  Windows 10 19041 Version 2004

### Debug Output With Command String  

wmiexec.py nobody@192.168.162.130 -debug

```
Impacket v0.9.22.dev1+20200629.145357.5d4ad6cc - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20200629.145357.5d4ad6cc-py3.8.egg/impacket
Password:
[*] SMBv3.0 dialect used
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20200629.145357.5d4ad6cc-py3.8.egg/EGG-INFO/scripts/wmiexec.py", line 85, in run
    iInterface = dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20200629.145357.5d4ad6cc-py3.8.egg/impacket/dcerpc/v5/dcomrt.py", line 1061, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20200629.145357.5d4ad6cc-py3.8.egg/impacket/dcerpc/v5/dcomrt.py", line 1840, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20200629.145357.5d4ad6cc-py3.8.egg/impacket/dcerpc/v5/rpcrt.py", line 878, in request
    raise exception
impacket.dcerpc.v5.dcomrt.DCERPCSessionError: DCOM SessionError: code: 0x80010111 - RPC_E_INVALID_HEADER - OLE received a packet with an invalid header.
[-] DCOM SessionError: code: 0x80010111 - RPC_E_INVALID_HEADER - OLE received a packet with an invalid header.
```

### Additional context 
Windows FIrewall is disabled.
**smbexec.py** works fine
**dcomexec.py** presents the same issue

**Comment by ABCIFOGeowi40** [comment]
I've found the problem. its in dcomrt.py line 171, the MinorVersion is set to 6 instead of 7 (which is the version of this new windows)

**Comment by mpgn** [comment]
send a pull request @ABCIFOGeowi40  :)

**Comment by alxchk** [comment]
> I've found the problem. its in dcomrt.py line 171, the MinorVersion is set to 6 instead of 7 (which is the version of this new windows)

Faced with same error and this works.

**Comment by spinenkoia** [comment]
Good afternoon, but what about the old versions of the OS now
@asolino 
it's been fixed here before
https://github.com/SecureAuthCorp/impacket/pull/445

**Comment by spinenkoia** [comment]
RPC_E_VERSION_MISMATCH - The version of OLE on the client and server machines does not match.
On Windows2000
