### ISSUE TITLE
Getting error while installing through pip: "Building wheels for collected packages: future"

### ISSUE THREAD

**Issue by hash30** [SecureAuthCorp/impacket#903]
`Building wheel for future (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-D36jfE/future/setup.py'"'"'; __file__='"'"'/tmp/pip-install-D36jfE/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-UqC0z4                                                            
       cwd: /tmp/pip-install-D36jfE/future/                                               
  Complete output (6 lines):                                                              
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]                   
     or: setup.py --help [cmd1 cmd2 ...]                                                  
     or: setup.py --help-commands                                                         
     or: setup.py cmd --help                                                              
                                                                                          
  error: invalid command 'bdist_wheel'                                                    
  ----------------------------------------                                                
  ERROR: Failed building wheel for future
`
Please help me out!

**Comment by asolino** [comment]
Can't reproduce.
