### ISSUE TITLE
ImportError: No module named ldap

### ISSUE THREAD

**Issue by thiago6826** [SecureAuthCorp/impacket#905]
### Configuration  
impacket version:  
Python version:  3.8.2-3
Target OS:  Windows AD - SAUNA hack the box

### Debug Output With Command String  

root@kali:~/Desktop/SAUNA# python GetNPUsers.py EGOTISTICAL-BANK.LOCAL/ -usersfile users.txt -format john -outputfile sauna.txt -dc-ip 10.10.10.175
Traceback (most recent call last):
  File "GetNPUsers.py", line 45, in <module>
    from impacket.ldap import ldap, ldapasn1
ImportError: No module named ldap
root@kali:~/Desktop/SAUNA#

**Comment by asolino** [comment]
Doesn't look like you have `impacket` properly installed. It can't just load one of impacket's modules (ldap).
