### ISSUE TITLE
PROPFIND not working in NTLMRelayX (WebDAV)

### ISSUE THREAD

**Issue by mubix** [SecureAuthCorp/impacket#906]
### Configuration  
impacket version:  1e84ad6049197ee15d31dc077c25415f90a61683
Python version: Python 3.7.3
Target OS:  Debian 10

### Debug Output With Command String  

NTLMRelayX should hit this: https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/servers/httprelayserver.py#L135

but for some reason the connection is reset instead of responded to. Here is the command line used:

`python3 ./ntlmrelayx.py -smb2support -t ldaps://dc1.sittingduck.info -ts -debug -wh kali`

### PCAP  

[webdav.pcap.zip](https://github.com/SecureAuthCorp/impacket/files/4940716/webdav.pcap.zip)

<img width="801" alt="request1" src="https://user-images.githubusercontent.com/679319/87838312-9b89b700-c864-11ea-8b00-2359a0057bed.png">

<img width="1203" alt="request2" src="https://user-images.githubusercontent.com/679319/87838318-a0e70180-c864-11ea-9aa3-0249bc7e3a62.png">

**Comment by 0xdeaddood** [comment]
Closing. Reopen if needed.

**Comment by sro-nviso** [comment]
Heyho!

Same problem here today.
I get the response that is expected including the PROPFIND method:

```
OPTIONS /Archive HTTP/1.1
Host: internal.workstation.local:3389
Accept: */*
translate: f
User-Agent: Microsoft-WebDAV-MiniRedir/10.0.19044
Connection: Keep-Alive

* Mark bundle as not supporting multiuse
HTTP/1.1 200 OK
Server: SimpleHTTP/0.6 Python/3.8.10
Date: Wed, 25 Jan 2023 14:34:01 GMT
Allow: GET, HEAD, POST, PUT, DELETE, OPTIONS, PROPFIND, PROPPATCH, MKCOL, LOCK, UNLOCK, MOVE, COPY
Content-Length: 0
Connection: close

* Closing connection 0`
```

But I see no debug inside ntlmrelayx so it there a way I can support to fix this bug?

**Comment by sro-nviso** [comment]
The same behaviour once I use tcpdump to log the traffic:

![image](https://user-images.githubusercontent.com/110816430/214796086-04e09820-24b1-45ee-98dc-9da998b91c6b.png)

**Comment by 0xdeaddood** [comment]
Hi @sro-nviso!

I have some questions to clarify your issue:
What Impacket version are you using? How are you triggering the incoming WebDav connection? Are you running the Impacket machine on the same host as the victim? Could you share the PCAP capture?

Thanks

**Comment by sro-nviso** [comment]
Hey @0xdeaddood Thanks for getting back to me.

**What Impacket version are you using?**
I was using the latest version from origin/master (34229464dab9ed4e432fdde56d14a916baaac4db).

**How are you triggering the incoming WebDav connection?**
The incoming WebDAV connection has been triggered by a user visiting an LNK file on a network share and the ICO field pointing to an internal workstation.
For the connection I used the FQDN of the workstation and reverse port forwarded from the workstation to the team server where ntlmrelayx was running.
There was no message in ntlmrelayx not even with "debug" enabled.
If I run "ncat" I would at least see the OPTIONS request, but using tcpdump it seems that ntlmrelayx sent the expected response.

**Are you running the Impacket machine on the same host as the victim?**
No, as the WebDAV authentication request originates from a different workstation then the workstation that has the reverse port forward activated.

**Could you share the PCAP capture?**
Sadly it contains customer data and I am not sure yet with what approach I could clean it enough for sharing.
Any hints appreciated, until then I guess I could not, sorry. :(
