### ISSUE TITLE
psexec Something wen't wrong connecting the pipes

### ISSUE THREAD

**Issue by ffcommax** [SecureAuthCorp/impacket#919]
psexec - connecting to pipes error

Log:

Impacket v0.9.19 - Copyright 2019 SecureAuth Corporation

[*] Requesting shares on 10.10.10.10.....
[*] Found writable share ADMIN$
[*] Uploading file NZNFAXvY.exe
[*] Opening SVCManager on 10.10.10.10.....
[*] Creating service Gdwb on 10.10.10.10.....
[*] Starting service Gdwb.....
[*] Opening SVCManager on 10.10.10.10.....
[-] Something wen't wrong connecting the pipes(<class '__main__.RemoteStdInPipe'>), try again
[!] Press help for extra shell commands
[*] Stopping service Gdwb.....
[*] Removing service Gdwb.....
[-] Something wen't wrong connecting the pipes(<class '__main__.RemoteStdOutPipe'>), try again
[*] Removing file NZNFAXvY.exe.....
[-] Error performing the uninstallation, cleaning up
[-] Something wen't wrong connecting the pipes(<class '__main__.RemoteStdErrPipe'>), try again

**Comment by asolino** [comment]
That's probably an AV catching the `psexec.py` executable. Can't tell much more from the report.
