### ISSUE TITLE
How can I use wimexec.py with socket proxy to connect different network segments computer?

### ISSUE THREAD

**Issue by Su-yj** [SecureAuthCorp/impacket#925]
My company has different network segments. Machines in different network segments cannot access each other. So I want to use the socket proxy to relay.
But I looked at the examples files and can not find how to use. Could make some examples to show how can I use?

**Comment by asolino** [comment]
Hey @Su-yj 

Don't quite understand your scenario. Do you want to use impacket through a configured SOCKS proxy to access the different network segments or do you want to perform NTLM Relay Attack and later use the SOCKS functionality over the relayed connections?

**Comment by Su-yj** [comment]
> Hey @Su-yj
> 
> Don't quite understand your scenario. Do you want to use impacket through a configured SOCKS proxy to access the different network segments or do you want to perform NTLM Relay Attack and later use the SOCKS functionality over the relayed connections?

Hi @asolino
Thanks for your comment. I mean want to use impacket through a configured SOCKS proxy to access the different network segments, and use the wimexec.py to connect.
Now I use the wimexec.py can login the Windows to manage that in the same network segments. But cannot login the different network segments because my company refuse. If I login the machines in different network segments, I must use the specified machine and specified port. So I want to use sock proxy to relay. I can build a sock services on the specified machine. But I don`t know how to config a sock proxy to access.
