### ISSUE TITLE
[Question] Is there a way to set static challenge for NTLMv1 while using ntlmrelayx.py

### ISSUE THREAD

**Issue by fsacer** [SecureAuthCorp/impacket#927]
If I'm relaying NTLMv1 I would like to use the static challenge of `1122334455667788 ` so I can instantly crack the received hash. Is there already a way to set that with `ntlmrelayx.py` and if not could that switch be added?

**Comment by asolino** [comment]
Hey @fsacer 

`git pull` and check the latest commit. You should have that option now.
