### ISSUE TITLE
pip install gives me an error message

### ISSUE THREAD

**Issue by CynaxG** [SecureAuthCorp/impacket#929]
I know that this might not 100% fit here, but I can't find an online fix and this only happens when I want to install impacket

with the command "pip install setup.py" in the impacket directory, I get the message

"WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Could not find a version that satisfies the requirement setup.py (from versions: none)
ERROR: No matching distribution found for setup.py"

Any clue how I can fix that?

**Comment by CynaxG** [comment]
(I checked the links but it seems like I'm too dumb for that xD)

**Comment by aaronleshalock** [comment]
Did you try following the documentation for install?
```bash
pip install .
python setup.py install
```

**Comment by asolino** [comment]
No answer.. closing.
