### ISSUE TITLE
how can I get the windows xp sp version and lang type use the smb proto?

### ISSUE THREAD

**Issue by taomujian** [SecureAuthCorp/impacket#930]
### Configuration  
impacket version:  0.9.21
Python version:  3.8
Target OS:  widnows xp

how can I get the windows xp sp version and lang type use the smb proto?
I now get the os version,but can not get sp version and lang type.

**Comment by asolino** [comment]
Getting the XP SP version is a lil bit more complicated than just reading a string through SMB. You might want to check Metasploit or similar projects and the tricks they use to detect target SP specifically for XP OSes.
