### ISSUE TITLE
SMB relay server target selection broken in ntlmrelayx

### ISSUE THREAD

**Issue by dirkjanm** [SecureAuthCorp/impacket#954]
Hey,

The SMB relay server is currently not working. The new target selection breaks it.
More specifically, the `relayToHost` variable is deleted at the end of the `SmbSessionSetupAndX` function (https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/servers/smbrelayserver.py#L670). This code runs for type 1 messages, so after that the variable is deleted. When the type 3 message is sent to the SMB server the relay server thinks that it's already done with the target and tries to find another one (and fails if there is just 1 target). Commenting out that line fixes it but might break other target selection. Also I'm not sure if returning from within the type 1 parsing logic would break something.

I may submit a PR if I find the correct solution, but wanted to post it just in case it's something obvious to others :)

**Comment by asolino** [comment]
Hey @dirkjanm ...

That indeed just doesn't seem right.. Seems to be happening only with `SMB1` right?.. `SMB2+` code is deleting that variable right after relay succeeded and right before `do_attack()`.

Let me understand a lil bit better why that is there.. but looks like it should be moved (not commented)

**Comment by asolino** [comment]
Just be fixed now @dirkjanm. Thanks for bringing this up.

**Comment by dirkjanm** [comment]
thanks for the fix!
