### ISSUE TITLE
Can't install impacket

### ISSUE THREAD

**Issue by Username1b** [SecureAuthCorp/impacket#967]
Can't install impacket

i've downloaded this 'https://github.com/SecureAuthCorp/impacket.git'

and can't run pip install .

I get his message -bash: pip: command not found

**Comment by L1ghtn1ng** [comment]
you will want to install it with python3 so if you are on kali you will want to do sudo apt install python3-pip then you will be able to install with the pip3 install .

**Comment by aalborz** [comment]
I'ved installed python3.pip but when I run pip install . from the source files folder , i still get an error bash: pip: command not found

**Comment by Radiance37k** [comment]
Installing it in a docker container using ropnops blogpost I managed to make it work on my end

**Comment by asolino** [comment]
Updated installation instructions for Python3 at https://github.com/SecureAuthCorp/impacket/commit/da48cfe7fe0f8469c648ed31fcdda2991e59dc82. Closing.
