### ISSUE TITLE
NT_MS_PRINCIPAL error(?) from GetUserSPNs.py

### ISSUE THREAD

**Issue by EasiestOdin5** [SecureAuthCorp/impacket#969]
Probably not a bug but I couldn't find much info about this:
"[-] Principal: MARVEL.local\TestService - NT_MS_PRINCIPAL"

Does anyone have any idea what this is?  How to get the Service ticket?

FYI, running against Windows Server 2019.

Thank you!

Executing the following command for kerberoasting:

> python3 GetUserSPNs.py MARVEL.local/fcastle:<some password> -request -dc-ip 10.0.2.4

Impacket v0.9.21 - Copyright 2020 SecureAuth Corporation

ServicePrincipalName                    Name         MemberOf                                                     PasswordLastSet             LastLogon  Delegation 
--------------------------------------  -----------  -----------------------------------------------------------  --------------------------  ---------  ----------
SQLService/HYDRA-DC.MARVEL.local:60111  SQLService   CN=Group Policy Creator Owners,OU=Groups,DC=MARVEL,DC=local  2020-08-19 03:36:55.280075  <never>               

TestService/HYDRA-DC.MARVEL.local       TestService                                                               2020-10-01 16:08:12.477245  <never>               

[-] Principal: MARVEL.local\SQLService - NT_MS_PRINCIPAL
[-] Principal: MARVEL.local\TestService - NT_MS_PRINCIPAL

**Comment by rmaksimov** [comment]
It looks like you are using a new version of the GetUserSPNs.py script with an old version of Impacket
Try to update and install the latest version of the Impacket library as described [here](https://github.com/SecureAuthCorp/impacket/blob/master/README.md#installing)

**Comment by EasiestOdin5** [comment]
Thank you!! @rmaksimov 
Followed your instructions and fully updated all the packages.
After that executed "sudo python3 setup.py install"
And it is working now.
