### ISSUE TITLE
smbserver broken when authentication is used

### ISSUE THREAD

**Issue by exploide** [SecureAuthCorp/impacket#974]
### Configuration  
impacket version:  All since b923413fc8737efdb84f08a791cc655f9e5113e0
Python version:  Python 3.8.5
Target OS:  Fedora 32

### Issue description

I noticed that accessing a share provided by `smbserver.py` fails once it requires authentication. For example:

```
> smbserver.py -smb2support -username foo -password foo tmp /tmp/smb
Impacket v0.9.22.dev1+20200929.152157.fe642b24 - Copyright 2020 SecureAuth Corporation

[*] Config file parsed
[*] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
[*] Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
[*] Config file parsed
[*] Config file parsed
[*] Config file parsed
[*] Incoming connection (127.0.0.1,52860)
[*] AUTHENTICATE_MESSAGE (SAMBA\foo,HACK)
[*] Could not authenticate user!
[*] Closing down connection (127.0.0.1,52860)
[*] Remaining connections []
```

when trying to access with

```
> smbclient \\\\127.0.0.1\\tmp -c ls -U foo foo
session setup failed: NT_STATUS_LOGON_FAILURE
```

Username and password are correctly set to foo but authentication fails.

`git bisect` found commit b923413fc8737efdb84f08a791cc655f9e5113e0 being responsible. Maybe some byte string madness.

**Comment by wrighterase** [comment]
can confirm.  having the same issue.

**Comment by asolino** [comment]
Hey @exploide and @wrighterase 

Nice catch.. can you `git pull` and re-test?

**Comment by wrighterase** [comment]
confirmed.  all good on v0.9.22.dev1+20201015.130615.81eec85a

**Comment by asolino** [comment]
Thanks for the confirmation, closing.
