### ISSUE TITLE
VSS Shadow Deletion

### ISSUE THREAD

**Issue by phefley** [SecureAuthCorp/impacket#981]
### Configuration  
impacket version:  python3-impacket/kali-rolling,now 0.9.21-2
Python version:  python3
Target OS:  Kali

### Additional context  
If the last shadow copy created was made AFTER impacket tries to create one on a different drive OR (a shadow copy already exists for the target drive AND the most recent shadow copy is on another drive) then all of the shadow copies on the wrong drive are deleted.

Recommend looking at targeted shadow deletion and looking for the last shadow on the target drive as opposed to all drives.

**Comment by asolino** [comment]
Solved at https://github.com/SecureAuthCorp/impacket/pull/982
