### ISSUE TITLE
rpcdump "TypeError: PrintStringBinding() takes exactly 1 argument (2 given)"

### ISSUE THREAD

**Issue by davehouser1** [SecureAuthCorp/impacket#993]
### Configuration  
impacket version:  v0.9.22.dev1+20200909.150738.15f3df26
Python version:  2.7.18
Target OS:  Kali 2020.2

### Debug Output With Command String  
```
$ rpcdump.py domain.com/bob:bobspassword123@10.10.10.123 -debug
Impacket v0.9.22.dev1+20200909.150738.15f3df26 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python2.7/dist-packages/impacket-0.9.22.dev1+20200909.150738.15f3df26-py2.7.egg/impacket
[*] Retrieving endpoint list from 10.10.10.100
[+] StringBinding ncacn_ip_tcp:10.10.10.100
Traceback (most recent call last):
  File "/home/dave/.local/bin/rpcdump.py", line 183, in <module>
    dumper.dump(remoteName, options.target_ip)
  File "/home/dave/.local/bin/rpcdump.py", line 77, in dump
    binding = epm.PrintStringBinding(entry['tower']['Floors'], rpctransport.getRemoteHost())
TypeError: PrintStringBinding() takes exactly 1 argument (2 given)

```

**Comment by mohemiv** [comment]
Hi @davehouser1,

It looks like you are using an old version of the rpcdump.py script with the latest version of the Impacket library. Try to update your examples.

Related issue: https://github.com/SecureAuthCorp/impacket/issues/969

**Comment by davehouser1** [comment]
@mohemiv thanks for the quick reply.
I git cloned the repo, then went into examples. and ran directory, that worked.
Is it safe to just copy all the examples scripts into my path `/home/me/.local/bin/`?
Is there a way to see the version of running scripts?
If not, maybe an idea for enhancement, -v and --version for script versions.

**Comment by mohemiv** [comment]
This should work, but I'm not sure if it's a right way to test Impacket:
```
git clone https://github.com/SecureAuthCorp/impacket
cd impacket/
python setup.py egg_info
mv impacket impacket.egg-info examples/
./examples/rpcdump.py
```

**Comment by asolino** [comment]
Best way to test impacket is to clone and install the library into a [Virtual Environment](https://docs.python.org/3/tutorial/venv.html). This helps avoiding any potential mix of different versions.

@davehouser1, did you solve this issue based on @mohemiv recommendation?

**Comment by 0xdeaddood** [comment]
No answer, closing.
