### ISSUE TITLE
Doesn't suporrt IP V6

### ISSUE THREAD

**Issue by CptGuo** [SecureAuthCorp/impacket#996]
It raise error when i use ip v6 address.

error msg : **socket.gaierror: [Errno -9] Address family for hostname not supported**

**Comment by asolino** [comment]
Hey @CptGuo 

Hard to reproduce this issue without more data. Closing this one. Please create a new one with the proper [template](https://github.com/SecureAuthCorp/impacket/issues/new?assignees=&labels=&template=bug_report.md&title=).
